[[item]]
id = "base_large_battle_axe"
base_id = "base_item"
item_id = 5114
name = "large battle axe"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x13fb"
item_id = 5115
rarity = "common"
hue = 0

[[item]]
id = "base_two_handed_axe"
base_id = "base_item"
item_id = 5186
name = "two handed axe"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x1443"
item_id = 5187
rarity = "common"
hue = 0

[[item]]
id = "base_hatchet"
base_id = "base_item"
item_id = 3907
name = "hatchet"
rarity = "common"
movable = true
layer = "one_handed"
decays = true
hue = 0

[[item]]
id = "0x0f44"
item_id = 3908
rarity = "common"
hue = 0

[[item]]
id = "base_executioners_axe"
base_id = "base_item"
item_id = 3909
name = "executioner's axe"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x0f46"
item_id = 3910
rarity = "common"
hue = 0

[[item]]
id = "base_battle_axe"
base_id = "base_item"
item_id = 3911
name = "battle axe"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x0f48"
item_id = 3912
rarity = "common"
hue = 0

[[item]]
id = "base_axe"
base_id = "base_item"
item_id = 3913
name = "axe"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x0f4a"
item_id = 3914
rarity = "common"
hue = 0

[[item]]
id = "base_double_axe"
base_id = "base_item"
item_id = 3915
name = "double axe"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x0f4c"
item_id = 3916
rarity = "common"
hue = 0

[[item]]
id = "base_ornate_axe"
base_id = "base_item"
item_id = 11560
name = "ornate axe"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x2d34"
item_id = 11572
rarity = "common"
hue = 0

[[item]]
id = "base_gargish_battle_axe"
base_id = "base_item"
item_id = 18608
name = "gargish battle axe"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x48b1"
item_id = 18609
rarity = "common"
hue = 0

[[item]]
id = "base_dual_short_axes"
base_id = "base_item"
item_id = 2301
name = "dual short axes"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x4068"
item_id = 16488
rarity = "common"
hue = 0

[[item]]
id = "base_gargish_axe"
base_id = "base_item"
item_id = 18610
name = "gargish axe"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x48b3"
item_id = 18611
rarity = "common"
hue = 0
