[[item]]
id = "0x26ac_bola"
base_id = "base_item"
item_id = 9900
name = "bola"
rarity = "common"
movable = true
weight = 4.0
buy_price = 46
sell_price = 23
decays = true
hue = 0

[[item]]
id = "base_fukiya"
base_id = "base_item"
item_id = 10154
name = "fukiya"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x27f5"
item_id = 10229
rarity = "common"
hue = 0
