[[item]]
id = "practice_skinning_knife"
item_id = 3780
name = "a skinning knife (practice weapon)"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "practice_hatchet"
item_id = 3907
name = "a hatchet (practice weapon)"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "practice_axe"
item_id = 3911
name = "a battle axe (practice weapon)"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "practice_mace"
item_id = 3932
name = "a mace (practice weapon)"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "practice_longsword"
item_id = 3937
name = "a longsword (practice weapon)"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "practice_spear"
item_id = 3939
name = "a spear (practice weapon)"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "practice_bow"
item_id = 5042
name = "a bow (practice weapon)"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "practice_club"
item_id = 5043
name = "a club (practice weapon)"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "practice_crook"
item_id = 5109
name = "a crook (practice weapon)"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "practice_gnarled_staff"
item_id = 5112
name = "a gnarled staff (practice weapon)"
rarity = "common"
movable = false
hue = 0
