[[item]]
id = "base_crook"
base_id = "base_item"
item_id = 5108
name = "crook"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x13f5"
item_id = 5109
rarity = "common"
hue = 0

[[item]]
id = "base_shepherds_crook"
base_id = "base_item"
item_id = 3713
name = "shepherd's crook"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x0e82"
item_id = 3714
rarity = "common"
hue = 0

[[item]]
id = "base_gnarled_staff"
base_id = "base_item"
item_id = 5112
name = "gnarled staff"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x13f9"
item_id = 5113
rarity = "common"
hue = 0

[[item]]
id = "base_black_staff"
base_id = "base_item"
item_id = 3568
name = "black staff"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x0df1"
item_id = 3569
rarity = "common"
hue = 0

[[item]]
id = "base_quarter_staff"
base_id = "base_item"
item_id = 3721
name = "quarter staff"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x0e8a"
item_id = 3722
rarity = "common"
hue = 0

[[item]]
id = "base_halberd"
base_id = "base_item"
item_id = 5182
name = "halberd"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x143f"
item_id = 5183
rarity = "common"
hue = 0

[[item]]
id = "guardhalberd"
base_id = "base_item"
item_id = 5183
name = "a guard's halberd"
rarity = "common"
movable = true
weight = 16.0
layer = "two_handed"
buy_price = 40
sell_price = 20
decays = true
loot_type = "newbied"
hue = 0

[[item]]
id = "base_bardiche"
base_id = "base_item"
item_id = 3917
name = "bardiche"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x0f4e"
item_id = 3918
rarity = "common"
hue = 0

[[item]]
id = "base_scythe"
base_id = "base_item"
item_id = 9914
name = "scythe"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x26c4"
item_id = 9924
rarity = "common"
hue = 0

[[item]]
id = "base_bladed_staff"
base_id = "base_item"
item_id = 9917
name = "bladed staff"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x26c7"
item_id = 9927
rarity = "common"
hue = 0

[[item]]
id = "base_double_bladed_staff"
base_id = "base_item"
item_id = 9919
name = "double bladed staff"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x26c9"
item_id = 9929
rarity = "common"
hue = 0

[[item]]
id = "base_wild_staff"
base_id = "base_item"
item_id = 11557
name = "wild staff"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x2d31"
item_id = 11569
rarity = "common"
hue = 0

[[item]]
id = "base_gargish_bardiche"
base_id = "base_item"
item_id = 18612
name = "gargish bardiche"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x48b5"
item_id = 18613
rarity = "common"
hue = 0

[[item]]
id = "base_gargish_scythe"
base_id = "base_item"
item_id = 18628
name = "gargish scythe"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x48c5"
item_id = 18629
rarity = "common"
hue = 0

[[item]]
id = "base_serpentstone_staff"
base_id = "base_item"
item_id = 2310
name = "serpentstone staff"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x406f"
item_id = 16495
rarity = "common"
hue = 0

[[item]]
id = "base_gargish_gnarled_staff"
base_id = "base_item"
item_id = 18616
name = "gargish gnarled staff"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x48b9"
item_id = 18617
rarity = "common"
hue = 0

[[item]]
id = "base_glass_staff"
base_id = "base_item"
item_id = 2309
name = "glass staff"
rarity = "common"
movable = true
layer = "two_handed"
decays = true
hue = 0

[[item]]
id = "0x4070"
item_id = 16496
rarity = "common"
hue = 0
