[[item]]
id = "base_crook"
base_id = "base_item"
item_id = 5108
name = "crook"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "mace"
decays = true

[[item]]
id = "0x13f4"
base_id = "0x13f4_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x13f5"
base_id = "0x13f4_lbr"
item_id = 5109
rarity = "common"
weapon_type = "mace"

[[item]]
id = "base_shepherds_crook"
base_id = "base_item"
item_id = 3713
name = "shepherd's crook"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "mace"
decays = true

[[item]]
id = "0x0e81"
base_id = "0x0e81_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x0e82"
base_id = "0x0e81_lbr"
item_id = 3714
rarity = "common"
weapon_type = "mace"

[[item]]
id = "base_gnarled_staff"
base_id = "base_item"
item_id = 5112
name = "gnarled staff"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "mace"
decays = true

[[item]]
id = "0x13f8"
base_id = "0x13f8_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x13f9"
base_id = "0x13f8_lbr"
item_id = 5113
rarity = "common"
weapon_type = "mace"

[[item]]
id = "base_black_staff"
base_id = "base_item"
item_id = 3568
name = "black staff"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "mace"
decays = true

[[item]]
id = "0x0df0"
base_id = "0x0df0_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x0df1"
base_id = "0x0df0_lbr"
item_id = 3569
rarity = "common"
weapon_type = "mace"

[[item]]
id = "base_quarter_staff"
base_id = "base_item"
item_id = 3721
name = "quarter staff"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "mace"
decays = true

[[item]]
id = "0x0e89"
base_id = "0x0e89_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x0e8a"
base_id = "0x0e89_lbr"
item_id = 3722
rarity = "common"
weapon_type = "mace"

[[item]]
id = "base_halberd"
base_id = "base_item"
script_id = "blade"
item_id = 5182
name = "halberd"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "sword"
decays = true

[[item]]
id = "0x143e"
base_id = "0x143e_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x143f"
base_id = "0x143e_lbr"
script_id = "blade"
item_id = 5183
rarity = "common"
weapon_type = "sword"

[[item]]
id = "guardhalberd"
base_id = "base_item"
script_id = "blade"
item_id = 5183
name = "a guard's halberd"
rarity = "common"
movable = true
weight = 16.0
layer = "two_handed"
two_handed_weapon = true
weapon_type = "sword"
damage_min = 75
damage_max = 150
speed = 60
strength_required = 120
max_hits = 80
buy_price = 40
sell_price = 20
decays = true
loot_type = "newbied"

[[item]]
id = "base_bardiche"
base_id = "base_item"
script_id = "blade"
item_id = 3917
name = "bardiche"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "pole_arm"
decays = true

[[item]]
id = "0x0f4d"
base_id = "0x0f4d_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x0f4e"
base_id = "0x0f4d_lbr"
script_id = "blade"
item_id = 3918
rarity = "common"
weapon_type = "pole_arm"

[[item]]
id = "base_scythe"
base_id = "base_item"
script_id = "blade"
item_id = 9914
name = "scythe"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "pole_arm"
decays = true

[[item]]
id = "0x26ba"
base_id = "0x26ba_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x26c4"
base_id = "0x26ba_lbr"
script_id = "blade"
item_id = 9924
rarity = "common"
weapon_type = "pole_arm"

[[item]]
id = "base_bladed_staff"
base_id = "base_item"
script_id = "blade"
item_id = 9917
name = "bladed staff"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "sword"
decays = true

[[item]]
id = "0x26bd"
base_id = "0x26bd_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x26c7"
base_id = "0x26bd_lbr"
script_id = "blade"
item_id = 9927
rarity = "common"
weapon_type = "sword"

[[item]]
id = "base_double_bladed_staff"
base_id = "base_item"
item_id = 9919
name = "double bladed staff"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "fencing"
decays = true

[[item]]
id = "0x26bf"
base_id = "0x26bf_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x26c9"
base_id = "0x26bf_lbr"
item_id = 9929
rarity = "common"
weapon_type = "fencing"

[[item]]
id = "base_wild_staff"
base_id = "base_item"
item_id = 11557
name = "wild staff"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "mace"
decays = true

[[item]]
id = "0x2d25"
base_id = "0x2d25_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x2d31"
base_id = "0x2d25_lbr"
item_id = 11569
rarity = "common"
weapon_type = "mace"

[[item]]
id = "base_gargish_bardiche"
base_id = "base_item"
script_id = "blade"
item_id = 18612
name = "gargish bardiche"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "pole_arm"
decays = true

[[item]]
id = "0x48b4"
base_id = "0x48b4_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x48b5"
base_id = "0x48b4_lbr"
script_id = "blade"
item_id = 18613
rarity = "common"
weapon_type = "pole_arm"

[[item]]
id = "base_gargish_scythe"
base_id = "base_item"
script_id = "blade"
item_id = 18628
name = "gargish scythe"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "pole_arm"
decays = true

[[item]]
id = "0x48c4"
base_id = "0x48c4_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x48c5"
base_id = "0x48c4_lbr"
script_id = "blade"
item_id = 18629
rarity = "common"
weapon_type = "pole_arm"

[[item]]
id = "base_serpentstone_staff"
base_id = "base_item"
item_id = 2310
name = "serpentstone staff"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "mace"
decays = true

[[item]]
id = "0x0906"
base_id = "0x0906_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x406f"
base_id = "0x0906_lbr"
item_id = 16495
rarity = "common"
weapon_type = "mace"

[[item]]
id = "base_gargish_gnarled_staff"
base_id = "base_item"
item_id = 18616
name = "gargish gnarled staff"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
decays = true

[[item]]
id = "0x48b8"
base_id = "0x48b8_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x48b9"
base_id = "0x48b8_lbr"
item_id = 18617
rarity = "common"

[[item]]
id = "base_glass_staff"
base_id = "base_item"
item_id = 2309
name = "glass staff"
rarity = "common"
movable = true
layer = "two_handed"
two_handed_weapon = true
weapon_type = "mace"
decays = true

[[item]]
id = "0x0905"
base_id = "0x0905_lbr"
item_id = 0
rarity = "common"

[[item]]
id = "0x4070"
base_id = "0x0905_lbr"
item_id = 16496
rarity = "common"
weapon_type = "mace"
