[[item]]
id = "0x13f2_va"
item_id = 5106
rarity = "common"
hue = 0

[[item]]
id = "0x13ed_va"
item_id = 5101
rarity = "common"
hue = 0

[[item]]
id = "0x13ef_va"
item_id = 5103
rarity = "common"
hue = 0

[[item]]
id = "0x13f1_va"
item_id = 5105
rarity = "common"
hue = 0

[[item]]
id = "0x13c0_va"
item_id = 5056
rarity = "common"
hue = 0

[[item]]
id = "0x13c3_va"
item_id = 5059
rarity = "common"
hue = 0

[[item]]
id = "0x13c4_va"
item_id = 5060
rarity = "common"
hue = 0

[[item]]
id = "0x1c05_va"
item_id = 7173
rarity = "common"
hue = 0

[[item]]
id = "0x1417_va"
item_id = 5143
rarity = "common"
hue = 0

[[item]]
id = "0x141a_va"
item_id = 5146
rarity = "common"
hue = 0

[[item]]
id = "0x1418_va"
item_id = 5144
rarity = "common"
hue = 0

[[item]]
id = "0x1416_va"
item_id = 5142
rarity = "common"
hue = 0

[[item]]
id = "0x27c2_va"
item_id = 10178
rarity = "common"
hue = 0

[[item]]
id = "0x27c3_va"
item_id = 10179
rarity = "common"
hue = 0

[[item]]
id = "0x27c8_va"
item_id = 10184
rarity = "common"
hue = 0

[[item]]
id = "0x27cb_va"
item_id = 10187
rarity = "common"
hue = 0

[[item]]
id = "0x27cc_va"
item_id = 10188
rarity = "common"
hue = 0

[[item]]
id = "0x27cf_va"
item_id = 10191
rarity = "common"
hue = 0

[[item]]
id = "0x27d0_va"
item_id = 10192
rarity = "common"
hue = 0

[[item]]
id = "0x27d3_va"
item_id = 10195
rarity = "common"
hue = 0

[[item]]
id = "0x27d4_va"
item_id = 10196
rarity = "common"
hue = 0

[[item]]
id = "0x236d_va"
item_id = 9069
rarity = "common"
hue = 0

[[item]]
id = "0x27d8_va"
item_id = 10200
rarity = "common"
hue = 0

[[item]]
id = "0x27c0_va"
item_id = 10176
rarity = "common"
hue = 0

[[item]]
id = "0x27bf_va"
item_id = 10175
rarity = "common"
hue = 0

[[item]]
id = "0x27c4_va"
item_id = 10180
rarity = "common"
hue = 0

[[item]]
id = "0x1409_va"
item_id = 5129
rarity = "common"
hue = 0

[[item]]
id = "0x140b_va"
base_id = "0x140b_va"
item_id = 5131
rarity = "common"
hue = 0

[[item]]
id = "0x140d_va"
item_id = 5133
rarity = "common"
hue = 0

[[item]]
id = "0x140f_va"
item_id = 5135
rarity = "common"
hue = 0

[[item]]
id = "0x1419_va"
item_id = 5145
rarity = "common"
hue = 0

[[item]]
id = "0x1b79_va"
item_id = 7033
rarity = "common"
hue = 0

[[item]]
id = "0x1bc5_va"
base_id = "0x1bc5_va"
item_id = 7109
rarity = "common"
hue = 0
