using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Moongate.Server.PacketHandlers.Generators.Data.Internal;

namespace Moongate.Server.PacketHandlers.Generators;

[Generator]
public sealed class ConsoleCommandRegistrationGenerator : IIncrementalGenerator
{
    private const string RegisterConsoleCommandAttributeName =
        "Moongate.Server.Attributes.RegisterConsoleCommandAttribute";

    private const string CommandExecutorInterfaceName =
        "Moongate.Server.Interfaces.Services.Console.ICommandExecutor";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            RegisterConsoleCommandAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntaxContext, _) => CreateModel(syntaxContext)
        );

        var registrationModels = candidates
                                 .Where(static model => model is not null)
                                 .Collect();

        context.RegisterSourceOutput(
            registrationModels,
            static (productionContext, models) =>
            {
                var registrations = models
                                    .Where(static model => model is not null)
                                    .Distinct()
                                    .OrderBy(static model => model.CommandName, StringComparer.Ordinal)
                                    .ThenBy(static model => model.ExecutorTypeName, StringComparer.Ordinal)
                                    .ToArray();

                if (registrations.Length == 0)
                {
                    return;
                }

                var source = BuildSource(registrations!);
                productionContext.AddSource(
                    "BootstrapConsoleCommandRegistration.Generated.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
            }
        );
    }

    private static string BuildSource(IReadOnlyList<ConsoleCommandRegistrationModel> registrations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("using DryIoc;");
        sb.AppendLine("using Moongate.Server.Interfaces.Services.Console;");
        sb.AppendLine("using Moongate.Server.Types.Commands;");
        sb.AppendLine("using Moongate.UO.Data.Types;");
        sb.AppendLine();
        sb.AppendLine("namespace Moongate.Server.Bootstrap.Internal;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class BootstrapConsoleCommandRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    static partial void RegisterServicesGenerated(Container container)");
        sb.AppendLine("    {");

        foreach (var registration in registrations)
        {
            sb.Append("        container.Register<");
            sb.Append(registration.ExecutorTypeName);
            sb.AppendLine(">(Reuse.Singleton);");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine(
            "    static partial void RegisterCommandsGenerated(Container container, ICommandSystemService commandSystemService)"
        );
        sb.AppendLine("    {");

        foreach (var registration in registrations)
        {
            var escapedName = registration.CommandName.Replace("\"", "\\\"");
            var escapedDescription = registration.Description.Replace("\"", "\\\"");
            sb.Append("        var executor_");
            sb.Append(GetIdentifier(registration.ExecutorTypeName));
            sb.Append(" = container.Resolve<");
            sb.Append(registration.ExecutorTypeName);
            sb.AppendLine(">();");
            sb.Append("        commandSystemService.RegisterCommand(");
            sb.Append('"');
            sb.Append(escapedName);
            sb.Append("\", executor_");
            sb.Append(GetIdentifier(registration.ExecutorTypeName));
            sb.Append(".ExecuteCommandAsync, \"");
            sb.Append(escapedDescription);
            sb.Append("\", (CommandSourceType)");
            sb.Append(registration.SourceValue.ToString(CultureInfo.InvariantCulture));
            sb.Append(", (AccountType)");
            sb.Append(registration.MinimumAccountTypeValue.ToString(CultureInfo.InvariantCulture));
            sb.Append(", ((ICommandExecutor)executor_");
            sb.Append(GetIdentifier(registration.ExecutorTypeName));
            sb.AppendLine(").AutocompleteProvider);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static ConsoleCommandRegistrationModel? CreateModel(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol || typeSymbol.IsAbstract)
        {
            return null;
        }

        if (!typeSymbol.AllInterfaces.Any(i => i.ToDisplayString() == CommandExecutorInterfaceName))
        {
            return null;
        }

        if (context.Attributes.Length == 0)
        {
            return null;
        }

        var attribute = context.Attributes[0];

        if (attribute.ConstructorArguments.Length == 0 ||
            attribute.ConstructorArguments[0].Value is not string commandName ||
            string.IsNullOrWhiteSpace(commandName))
        {
            return null;
        }

        var description = attribute.ConstructorArguments.Length > 1 &&
                          attribute.ConstructorArguments[1].Value is string descriptionValue
                              ? descriptionValue
                              : string.Empty;

        var sourceValue = attribute.ConstructorArguments.Length > 2 &&
                          attribute.ConstructorArguments[2].Value is int sourceValueArg
                              ? sourceValueArg
                              : 1;

        var minimumAccountTypeValue = attribute.ConstructorArguments.Length > 3 &&
                                      attribute.ConstructorArguments[3].Value is int minimumAccountTypeArg
                                          ? minimumAccountTypeArg
                                          : 2;

        var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var normalizedTypeName = fullTypeName.StartsWith("global::", StringComparison.Ordinal)
                                     ? fullTypeName.Substring("global::".Length)
                                     : fullTypeName;

        return new(
            normalizedTypeName,
            commandName,
            description,
            sourceValue,
            minimumAccountTypeValue
        );
    }

    private static string GetIdentifier(string typeName)
    {
        var chars = typeName.Select(static c => char.IsLetterOrDigit(c) ? c : '_').ToArray();

        return new(chars);
    }
}
