using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Moongate.Server.PacketHandlers.Generators.Data.Internal;

namespace Moongate.Server.PacketHandlers.Generators;

[Generator]
public sealed class FileLoaderRegistrationGenerator : IIncrementalGenerator
{
    private const string RegisterFileLoaderAttributeName =
        "Moongate.Server.Attributes.RegisterFileLoaderAttribute";

    private const string FileLoaderInterfaceName =
        "Moongate.UO.Data.Interfaces.FileLoaders.IFileLoader";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            RegisterFileLoaderAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntaxContext, _) => CreateModel(syntaxContext)
        );

        var registrationModels = candidates
                                 .Where(static model => model is not null)
                                 .Collect();

        context.RegisterSourceOutput(
            registrationModels,
            static (productionContext, models) =>
            {
                var registrations = models
                                    .Where(static model => model is not null)
                                    .Distinct()
                                    .OrderBy(static model => model.Order)
                                    .ThenBy(static model => model.LoaderTypeName, StringComparer.Ordinal)
                                    .ToArray();

                if (registrations.Length == 0)
                {
                    return;
                }

                var source = BuildSource(registrations);
                productionContext.AddSource(
                    "BootstrapFileLoaderRegistration.Generated.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
            }
        );
    }

    private static string BuildSource(IReadOnlyList<FileLoaderRegistrationModel> registrations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("namespace Moongate.Server.Bootstrap.Internal;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class BootstrapFileLoaderRegistration");
        sb.AppendLine("{");
        sb.AppendLine(
            "    static partial void RegisterGenerated(Moongate.Server.Interfaces.Services.Files.IFileLoaderService fileLoaderService)"
        );
        sb.AppendLine("    {");

        foreach (var registration in registrations)
        {
            sb.Append("        fileLoaderService.AddFileLoader<");
            sb.Append(registration.LoaderTypeName);
            sb.AppendLine(">();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static FileLoaderRegistrationModel? CreateModel(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        if (typeSymbol.IsAbstract)
        {
            return null;
        }

        if (!typeSymbol.AllInterfaces.Any(i => i.ToDisplayString() == FileLoaderInterfaceName))
        {
            return null;
        }

        if (context.Attributes.Length == 0)
        {
            return null;
        }

        var attribute = context.Attributes[0];

        if (attribute.ConstructorArguments.Length != 1)
        {
            return null;
        }

        var orderValue = attribute.ConstructorArguments[0].Value;

        if (orderValue is null)
        {
            return null;
        }

        var order = Convert.ToInt32(orderValue, CultureInfo.InvariantCulture);

        var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var normalizedTypeName = fullTypeName.StartsWith("global::", StringComparison.Ordinal)
                                     ? fullTypeName.Substring("global::".Length)
                                     : fullTypeName;

        return new(normalizedTypeName, order);
    }
}
