using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Moongate.Server.PacketHandlers.Generators.Data.Internal;

namespace Moongate.Server.PacketHandlers.Generators;

[Generator]
public sealed class GameEventListenerRegistrationGenerator : IIncrementalGenerator
{
    private const string RegisterGameEventListenerAttributeName =
        "Moongate.Server.Attributes.RegisterGameEventListenerAttribute";

    private const string GameEventListenerInterfaceName =
        "Moongate.Server.Interfaces.Services.Events.IGameEventListener<TEvent>";

    private const string MoongateServiceInterfaceName =
        "Moongate.Abstractions.Interfaces.Services.Base.IMoongateService";

    private const int DefaultPriority = 200;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            RegisterGameEventListenerAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntaxContext, _) => CreateModels(syntaxContext)
        );

        var registrationModels = candidates.SelectMany(static (models, _) => models ?? []);

        var collected = registrationModels
                        .Where(static model => model is not null)
                        .Collect();

        context.RegisterSourceOutput(
            collected,
            static (productionContext, models) =>
            {
                var registrations = models
                                    .Where(static model => model is not null)
                                    .Distinct()
                                    .OrderBy(static model => model.ListenerTypeName, StringComparer.Ordinal)
                                    .ThenBy(static model => model.EventTypeName, StringComparer.Ordinal)
                                    .ToArray();

                if (registrations.Length == 0)
                {
                    return;
                }

                var source = BuildSource(registrations);
                productionContext.AddSource(
                    "BootstrapGameEventListenerRegistration.Generated.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
            }
        );
    }

    private static void BuildRegisterServicesMethod(
        StringBuilder sb,
        IReadOnlyList<GameEventListenerRegistrationModel> registrations
    )
    {
        sb.AppendLine("    static partial void RegisterServicesGenerated(Container container)");
        sb.AppendLine("    {");

        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var registration in registrations)
        {
            if (!seen.Add(registration.ListenerTypeName))
            {
                continue;
            }

            if (registration.ImplementsMoongateService)
            {
                sb.Append("        container.RegisterMoongateService<");
                sb.Append(registration.ListenerTypeName);
                sb.Append(">(");
                sb.Append(registration.Priority);
                sb.AppendLine(");");
            }
            else
            {
                sb.Append("        container.Register<");
                sb.Append(registration.ListenerTypeName);
                sb.AppendLine(">(Reuse.Singleton);");
            }
        }

        sb.AppendLine("    }");
    }

    private static string BuildSource(IReadOnlyList<GameEventListenerRegistrationModel> registrations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("using DryIoc;");
        sb.AppendLine("using Moongate.Abstractions.Extensions;");
        sb.AppendLine();
        sb.AppendLine("namespace Moongate.Server.Bootstrap.Internal;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class BootstrapGameEventListenerRegistration");
        sb.AppendLine("{");

        BuildRegisterServicesMethod(sb, registrations);
        sb.AppendLine();
        BuildSubscribeMethod(sb, registrations);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void BuildSubscribeMethod(
        StringBuilder sb,
        IReadOnlyList<GameEventListenerRegistrationModel> registrations
    )
    {
        sb.AppendLine("    static partial void SubscribeGenerated(Container container)");
        sb.AppendLine("    {");

        foreach (var registration in registrations)
        {
            sb.Append("        RegisterListener<");
            sb.Append(registration.ListenerTypeName);
            sb.Append(", ");
            sb.Append(registration.EventTypeName);
            sb.AppendLine(">(container);");
        }

        sb.AppendLine("    }");
    }

    private static bool CheckImplementsMoongateService(INamedTypeSymbol typeSymbol)
    {
        foreach (var interfaceSymbol in typeSymbol.AllInterfaces)
        {
            if (interfaceSymbol.ToDisplayString() == MoongateServiceInterfaceName)
            {
                return true;
            }
        }

        return false;
    }

    private static IReadOnlyList<GameEventListenerRegistrationModel>? CreateModels(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol || typeSymbol.IsAbstract)
        {
            return null;
        }

        var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var normalizedTypeName = fullTypeName.StartsWith("global::", StringComparison.Ordinal)
                                     ? fullTypeName.Substring("global::".Length)
                                     : fullTypeName;

        var priority = ExtractPriority(context);
        var implementsMoongateService = CheckImplementsMoongateService(typeSymbol);

        var models = new List<GameEventListenerRegistrationModel>();

        foreach (var interfaceSymbol in typeSymbol.AllInterfaces)
        {
            if (interfaceSymbol.OriginalDefinition.ToDisplayString() != GameEventListenerInterfaceName)
            {
                continue;
            }

            if (interfaceSymbol.TypeArguments.Length != 1)
            {
                continue;
            }

            var eventType = interfaceSymbol.TypeArguments[0]
                                           .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var normalizedEventType = eventType.StartsWith("global::", StringComparison.Ordinal)
                                          ? eventType.Substring("global::".Length)
                                          : eventType;

            models.Add(new(normalizedTypeName, normalizedEventType, priority, implementsMoongateService));
        }

        return models;
    }

    private static int ExtractPriority(GeneratorAttributeSyntaxContext context)
    {
        foreach (var attributeData in context.Attributes)
        {
            if (attributeData.AttributeClass?.ToDisplayString() != RegisterGameEventListenerAttributeName)
            {
                continue;
            }

            if (attributeData.ConstructorArguments.Length > 0 &&
                attributeData.ConstructorArguments[0].Value is int priority)
            {
                return priority;
            }
        }

        return DefaultPriority;
    }
}
