using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Moongate.Server.PacketHandlers.Generators.Data.Internal;

namespace Moongate.Server.PacketHandlers.Generators;

[Generator]
public sealed class GameEventListenerRegistrationGenerator : IIncrementalGenerator
{
    private const string RegisterGameEventListenerAttributeName =
        "Moongate.Server.Attributes.RegisterGameEventListenerAttribute";

    private const string GameEventListenerInterfaceName =
        "Moongate.Server.Interfaces.Services.Events.IGameEventListener<TEvent>";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            RegisterGameEventListenerAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntaxContext, _) => CreateModels(syntaxContext)
        );

        var registrationModels = candidates.SelectMany(static (models, _) => models ?? []);

        var collected = registrationModels
                        .Where(static model => model is not null)
                        .Collect();

        context.RegisterSourceOutput(
            collected,
            static (productionContext, models) =>
            {
                var registrations = models
                                    .Where(static model => model is not null)
                                    .Distinct()
                                    .OrderBy(static model => model.ListenerTypeName, StringComparer.Ordinal)
                                    .ThenBy(static model => model.EventTypeName, StringComparer.Ordinal)
                                    .ToArray();

                if (registrations.Length == 0)
                {
                    return;
                }

                var source = BuildSource(registrations);
                productionContext.AddSource(
                    "BootstrapGameEventListenerRegistration.Generated.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
            }
        );
    }

    private static string BuildSource(IReadOnlyList<GameEventListenerRegistrationModel> registrations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("using DryIoc;");
        sb.AppendLine();
        sb.AppendLine("namespace Moongate.Server.Bootstrap.Internal;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class BootstrapGameEventListenerRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    static partial void SubscribeGenerated(Container container)");
        sb.AppendLine("    {");

        foreach (var registration in registrations)
        {
            sb.Append("        RegisterListener<");
            sb.Append(registration.ListenerTypeName);
            sb.Append(", ");
            sb.Append(registration.EventTypeName);
            sb.AppendLine(">(container);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static IReadOnlyList<GameEventListenerRegistrationModel>? CreateModels(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol || typeSymbol.IsAbstract)
        {
            return null;
        }

        var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var normalizedTypeName = fullTypeName.StartsWith("global::", StringComparison.Ordinal)
                                     ? fullTypeName.Substring("global::".Length)
                                     : fullTypeName;

        var models = new List<GameEventListenerRegistrationModel>();

        foreach (var interfaceSymbol in typeSymbol.AllInterfaces)
        {
            if (interfaceSymbol.OriginalDefinition.ToDisplayString() != GameEventListenerInterfaceName)
            {
                continue;
            }

            if (interfaceSymbol.TypeArguments.Length != 1)
            {
                continue;
            }

            var eventType = interfaceSymbol.TypeArguments[0]
                                           .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var normalizedEventType = eventType.StartsWith("global::", StringComparison.Ordinal)
                                          ? eventType.Substring("global::".Length)
                                          : eventType;

            models.Add(new(normalizedTypeName, normalizedEventType));
        }

        return models;
    }
}
