using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Moongate.Server.PacketHandlers.Generators.Data.Internal;

namespace Moongate.Server.PacketHandlers.Generators;

[Generator]
public sealed class LuaUserDataRegistrationGenerator : IIncrementalGenerator
{
    private const string RegisterLuaUserDataAttributeName =
        "Moongate.Server.Attributes.RegisterLuaUserDataAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            RegisterLuaUserDataAttributeName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (syntaxContext, _) => CreateModel(syntaxContext)
        );

        var collected = candidates
            .Where(static model => model is not null)
            .Collect()
            .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName));

        context.RegisterSourceOutput(
            collected,
            static (productionContext, payload) =>
            {
                var assemblyName = payload.Right;

                if (!string.Equals(assemblyName, "Moongate.Server", StringComparison.Ordinal))
                {
                    return;
                }

                var registrations = payload.Left
                    .Where(static model => model is not null)
                    .Distinct()
                    .OrderBy(static model => model.TypeName, StringComparer.Ordinal)
                    .ToArray();

                var source = BuildSource(registrations);
                productionContext.AddSource(
                    "BootstrapLuaUserDataRegistration.Generated.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
            }
        );
    }

    private static string BuildSource(IReadOnlyList<LuaUserDataRegistrationModel> registrations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("using DryIoc;");
        sb.AppendLine("using Moongate.Scripting.Extensions.Scripts;");
        sb.AppendLine();
        sb.AppendLine("namespace Moongate.Server.Bootstrap.Internal;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class BootstrapLuaUserDataRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    static partial void RegisterGenerated(IContainer container)");
        sb.AppendLine("    {");

        foreach (var registration in registrations)
        {
            sb.Append("        container.RegisterLuaUserData<");
            sb.Append(registration.TypeName);
            sb.AppendLine(">();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static LuaUserDataRegistrationModel? CreateModel(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        if (typeSymbol.IsAbstract || typeSymbol.IsGenericType)
        {
            return null;
        }

        var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var normalizedTypeName = fullTypeName.StartsWith("global::", StringComparison.Ordinal)
            ? fullTypeName.Substring("global::".Length)
            : fullTypeName;

        return new(normalizedTypeName);
    }
}
