using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Moongate.Server.PacketHandlers.Generators.Data.Internal;

namespace Moongate.Server.PacketHandlers.Generators;

[Generator]
public sealed class ScriptModuleRegistrationGenerator : IIncrementalGenerator
{
    private const string ScriptModuleAttributeName = "Moongate.Scripting.Attributes.Scripts.ScriptModuleAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            ScriptModuleAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntaxContext, _) => CreateModel(syntaxContext)
        );

        var collected = candidates
                        .Where(static model => model is not null)
                        .Collect()
                        .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName));

        context.RegisterSourceOutput(
            collected,
            static (productionContext, payload) =>
            {
                var assemblyName = payload.Right;

                if (!IsSupportedAssembly(assemblyName))
                {
                    return;
                }

                var registrations = payload.Left
                                           .Where(static model => model is not null)
                                           .Distinct()
                                           .OrderBy(static model => model.ModuleTypeName, StringComparer.Ordinal)
                                           .ToArray();

                var source = BuildSource(registrations, assemblyName!);
                productionContext.AddSource(
                    "BootstrapScriptModuleRegistration.Generated.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
            }
        );
    }

    private static string BuildSource(IReadOnlyList<ScriptModuleRegistrationModel> registrations, string assemblyName)
    {
        var sb = new StringBuilder();
        var targetNamespace = assemblyName + ".Generated";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("using DryIoc;");
        sb.AppendLine("using Moongate.Scripting.Extensions.Scripts;");
        sb.AppendLine();
        sb.Append("namespace ");
        sb.Append(targetNamespace);
        sb.AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("public static class ScriptModuleRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static void Register(IContainer container)");
        sb.AppendLine("    {");

        foreach (var registration in registrations)
        {
            sb.Append("        container.RegisterScriptModule<");
            sb.Append(registration.ModuleTypeName);
            sb.AppendLine(">();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static ScriptModuleRegistrationModel? CreateModel(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        if (typeSymbol.IsAbstract || typeSymbol.IsGenericType)
        {
            return null;
        }

        var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var normalizedTypeName = fullTypeName.StartsWith("global::", StringComparison.Ordinal)
                                     ? fullTypeName.Substring("global::".Length)
                                     : fullTypeName;

        return new(normalizedTypeName);
    }

    private static bool IsSupportedAssembly(string? assemblyName)
        => string.Equals(assemblyName, "Moongate.Scripting", StringComparison.Ordinal) ||
           string.Equals(assemblyName, "Moongate.Server", StringComparison.Ordinal);
}
