using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Moongate.Server.PacketHandlers.Generators;

[Generator]
public sealed class VersionUtilsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var versionData = context.AnalyzerConfigOptionsProvider
                                 .Combine(context.CompilationProvider)
                                 .Select(
                                     static (value, _) => CreateVersionSource(
                                         value.Left,
                                         value.Right.AssemblyName
                                     )
                                 );

        context.RegisterSourceOutput(
            versionData,
            static (productionContext, source) =>
            {
                if (source is null)
                {
                    return;
                }

                productionContext.AddSource(
                    "VersionUtils.Generated.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
            }
        );
    }

    private static string? CreateVersionSource(AnalyzerConfigOptionsProvider provider, string? assemblyName)
    {
        if (!string.Equals(assemblyName, "Moongate.Server", StringComparison.Ordinal))
        {
            return null;
        }

        if (!provider.GlobalOptions.TryGetValue("build_property.MoongateCodename", out var codename) ||
            string.IsNullOrWhiteSpace(codename))
        {
            return null;
        }

        provider.GlobalOptions.TryGetValue("build_property.MoongateVersion", out var version);
        version = string.IsNullOrWhiteSpace(version) ? "0.0.0" : version;

        var escapedVersion = Escape(version);
        var escapedCodename = Escape(codename);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("namespace Moongate.Server.Data.Version;");
        sb.AppendLine();
        sb.AppendLine("public static class VersionUtils");
        sb.AppendLine("{");
        sb.Append("    public const string Version = \"");
        sb.Append(escapedVersion);
        sb.AppendLine("\";");
        sb.Append("    public const string Codename = \"");
        sb.Append(escapedCodename);
        sb.AppendLine("\";");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
}
