[[item]]
id = "0x1bd7_board"
base_id = "base_item"
item_id = 7127
name = "board"
rarity = "common"
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
decays = true
hue = 0

[[item]]
id = "0x1bda_board"
base_id = "base_item"
item_id = 7130
name = "board"
rarity = "common"
weight = 1.0
stackable = true
buy_price = 1
sell_price = 1
decays = true
hue = 0
