[[item]]
id = "0x103f_cookie_mix"
base_id = "base_item"
item_id = 4159
name = "cookie mix"
rarity = "common"
weight = 1.0
hue = 0

[[item]]
id = "cake_mix"
base_id = "base_item"
item_id = 4159
name = "cake mix"
rarity = "common"
weight = 1.0
hue = 0

[[item]]
id = "0x103d_dough"
base_id = "base_item"
item_id = 4157
name = "dough"
rarity = "common"
weight = 1.0
stackable = true
hue = 0

[[item]]
id = "sweet_dough"
base_id = "base_item"
item_id = 4157
name = "sweet dough"
rarity = "common"
weight = 1.0
stackable = true
hue = 0

[[item]]
id = "0x1039_sack_of_flour"
base_id = "base_item"
item_id = 4153
name = "sack of flour"
rarity = "common"
weight = 1.0
hue = 0

[[item]]
id = "0x1045_sack_of_flour"
base_id = "base_item"
item_id = 4165
name = "sack of flour"
rarity = "common"
weight = 1.0
hue = 0

[[item]]
id = "0x1046_open_sack_of_flour"
base_id = "base_item"
item_id = 4166
name = "open sack of flour"
rarity = "common"
weight = 1.0
hue = 0

[[item]]
id = "0x103a_open_sack_of_flour"
base_id = "base_item"
item_id = 4154
name = "open sack of flour"
rarity = "common"
weight = 1.0
hue = 0

[[item]]
id = "0x0a1e_bowl_of_flour"
item_id = 2590
name = "bowl of flour"
rarity = "common"
weight = 4.0
buy_price = 8
sell_price = 4
hue = 0

[[item]]
id = "0x1ebd_#"
base_id = "base_item"
item_id = 7869
name = "#"
rarity = "common"
weight = 1.0
stackable = true
buy_price = 2
sell_price = 1
hue = 0
