[[item]]
id = "base_magic_fish"
item_id = 3542
rarity = "common"
movable = false
hue = 0

[[item]]
id = "big_fish"
base_id = "base_item"
item_id = 2508
name = "big fish"
rarity = "common"
movable = false
hue = 1420

[[item]]
id = "messageinabottle"
base_id = "base_item"
item_id = 2463
name = "message in a bottle"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "waterstainedsos"
base_id = "base_item"
item_id = 5358
name = "waterstained SOS"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "waterstainedsos_tol"
base_id = "waterstainedsos"
item_id = 41740
rarity = "common"
movable = false
hue = 0
