[[item]]
id = "0x1bd1_feather"
base_id = "base_item"
item_id = 7121
name = "feather"
rarity = "common"
weight = 0.1
stackable = true
buy_price = 2
sell_price = 1
decays = true
hue = 0

[[item]]
id = "0x1bd4_shaft"
base_id = "base_item"
item_id = 7124
name = "shaft"
rarity = "common"
weight = 0.1
stackable = true
buy_price = 3
sell_price = 1
decays = true
hue = 0

[[item]]
id = "0x1bd4_5_shaft"
base_id = "base_item"
item_id = 7124
name = "shaft"
rarity = "common"
weight = 0.1
amount = 5
stackable = true
buy_price = 3
sell_price = 1
decays = true
hue = 0

[[item]]
id = "0x1bd4_20_shaft"
base_id = "base_item"
item_id = 7124
name = "shaft"
rarity = "common"
weight = 0.1
amount = 20
stackable = true
buy_price = 3
sell_price = 1
decays = true
hue = 0

[[item]]
id = "0x1bd4_50_shaft"
base_id = "base_item"
item_id = 7124
name = "shaft"
rarity = "common"
weight = 0.1
amount = 50
stackable = true
buy_price = 3
sell_price = 1
decays = true
hue = 0
