[[item]]
id = "0x0fa0_spool_of_thread"
base_id = "base_item"
item_id = 4000
name = "spool of thread"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0fa1_spool_of_thread"
base_id = "base_item"
item_id = 4001
name = "spool of thread"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1420_roll_of_string"
base_id = "base_item"
item_id = 5152
name = "roll of string"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1421_roll_of_string"
base_id = "base_item"
item_id = 5153
name = "roll of string"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x101f_pile_of_wool"
base_id = "base_item"
item_id = 4127
name = "pile of wool"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0df8_pile_of_wool"
base_id = "base_item"
item_id = 3576
name = "pile of wool"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0def_raw_cotton"
base_id = "base_item"
item_id = 3567
name = "raw cotton"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x0df9_bale_of_cotton"
base_id = "base_item"
item_id = 3577
name = "bale of cotton"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1a9c_flax_bundle"
base_id = "base_item"
item_id = 6812
name = "flax bundle"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1a9d_flax_bundle"
base_id = "base_item"
item_id = 6813
name = "flax bundle"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0e1d_ball_of_yarn"
base_id = "base_item"
item_id = 3613
name = "ball of yarn"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0e1e_ball_of_yarn"
base_id = "base_item"
item_id = 3614
name = "ball of yarn"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0e1f_ball_of_yarn"
base_id = "base_item"
item_id = 3615
name = "ball of yarn"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0f95_bolt_of_cloth"
base_id = "base_item"
item_id = 3989
name = "bolt of cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0f98_bolt_of_cloth"
base_id = "base_item"
item_id = 3992
name = "bolt of cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0f99_bolt_of_cloth"
base_id = "base_item"
item_id = 3993
name = "bolt of cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0f9a_bolt_of_cloth"
base_id = "base_item"
item_id = 3994
name = "bolt of cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x175d_folded_cloth"
base_id = "base_item"
item_id = 5981
name = "folded cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x175e_folded_cloth"
base_id = "base_item"
item_id = 5982
name = "folded cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x175f_folded_cloth"
base_id = "base_item"
item_id = 5983
name = "folded cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1760_folded_cloth"
base_id = "base_item"
item_id = 5984
name = "folded cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1761_folded_cloth"
base_id = "base_item"
item_id = 5985
name = "folded cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1762_folded_cloth"
base_id = "base_item"
item_id = 5986
name = "folded cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1763_folded_cloth"
base_id = "base_item"
item_id = 5987
name = "folded cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1764_folded_cloth"
base_id = "base_item"
item_id = 5988
name = "folded cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1765_cloth"
base_id = "base_item"
item_id = 5989
name = "cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1766_cut_cloth"
base_id = "base_item"
item_id = 5990
name = "cut cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1767_cloth"
base_id = "base_item"
item_id = 5991
name = "cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1768_cut_cloth"
base_id = "base_item"
item_id = 5992
name = "cut cloth"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0df6_knitting"
base_id = "base_item"
item_id = 3574
name = "knitting"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0df7_knitting"
base_id = "base_item"
item_id = 3575
name = "knitting"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "arcane_gem"
base_id = "base_item"
item_id = 7847
name = "arcane gem"
rarity = "common"
movable = false
hue = 0
