[[item]]
id = "0x105b_axle"
base_id = "base_item"
item_id = 4187
name = "axle"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1051_axle_with_gears"
base_id = "base_item"
item_id = 4177
name = "axle with gears"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1db7_barrel_hoop"
base_id = "base_item"
item_id = 7607
name = "barrel hoop"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1db8_barrel_lid"
base_id = "base_item"
item_id = 7608
name = "barrel lid"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1eb2_barrel_stave"
base_id = "base_item"
item_id = 7858
name = "barrel stave"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1004_barrel_tap"
base_id = "base_item"
item_id = 4100
name = "barrel tap"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x104b_clock"
base_id = "base_item"
item_id = 4171
name = "clock"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x104c_clock"
base_id = "base_item"
item_id = 4172
name = "clock"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x104d_clock_frame"
base_id = "base_item"
item_id = 4173
name = "clock frame"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x104e_clock_frame"
base_id = "base_item"
item_id = 4174
name = "clock frame"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x104f_clock_parts"
base_id = "base_item"
item_id = 4175
name = "clock parts"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1053_gears"
base_id = "base_item"
item_id = 4179
name = "gears"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1047_globe"
base_id = "base_item"
item_id = 4167
name = "globe"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1048_globe"
base_id = "base_item"
item_id = 4168
name = "globe"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1055_hinge"
base_id = "base_item"
item_id = 4181
name = "hinge"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1851_scales"
base_id = "base_item"
item_id = 6225
name = "scales"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1852_scales"
base_id = "base_item"
item_id = 6226
name = "scales"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1057_sextant"
base_id = "base_item"
item_id = 4183
name = "sextant"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1059_sextant_parts"
base_id = "base_item"
item_id = 4185
name = "sextant parts"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x105d_springs"
base_id = "base_item"
item_id = 4189
name = "springs"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "power_crystal"
base_id = "base_item"
item_id = 7964
name = "power crystal"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "clockwork_assembly"
base_id = "base_item"
item_id = 7848
name = "clockwork assembly"
rarity = "common"
movable = false
hue = 0
