"""``uox-spells``: the 64 spells of UOX3 (``dfndata/spells/spells.dfn``) into ``data/spells.toml``.

A spell keeps what the casting engine reads from data: the client's number, the key a script is named by, the circle, the words of
power, the animation, the reagents as item templates, what it asks to be aimed at, its flags, its sound and its graphics, the prompt of
the target cursor and the scroll that holds it. The mana and the skill windows are the classic tables of the server, not data.
"""

from __future__ import annotations

import os
import re
import tomllib
from pathlib import Path
from typing import TextIO

from . import dfn, tomlout
from .textutil import read_lines, trim, write_text

FILE = "spells.toml"
SPELLS_FILE = "spells.dfn"
SPELL_COUNT = 64

HEADER = """# ==============================================================================
# Moongate - spells.toml
#
# What it is for:
#   The 64 spells of Magery: what a spell is called, its circle, the words of power, the reagents, what the target cursor
#   asks for, its flags and its sound and graphics, and the scroll that holds it. The mana and the skill window of a spell
#   come from its circle, in the server. What a spell does is a script, scripts/spells/<key>.lua; a spell with no script
#   cannot be cast yet. Generated by moongate-convert uox-spells.
#
# Fields:
#   [[spell]]          one spell, in the order of the client's spellbook
#     id               the client's number, 1 to 64: the bit of the spellbook and what a cast request names
#     key              the name of its script and of the spell in scripts, a lower-case identifier
#     name             the name players read
#     circle           1 to 8
#     mantra           the words of power said over the caster's head
#     action           the animation of the caster: 16 or 17 for a human
#     reagents         the item templates and how many of each a cast takes from the backpack
#     target           what the cursor asks for: none, mobile, item or location
#     harmful          a spell that hurts or curses: the cursor is the harmful one and the caster may become a criminal
#     resistable       Resisting Spells may weaken it
#     reflectable      Magic Reflection may turn it back
#     sound            the sound of the spell, 0 for none
#     effect           the graphic played on the target, 0 for none; effect_duration is its length
#     projectile       the graphic that flies from the caster to the target, 0 for none; projectile_speed is its speed
#     prompt           the text of the target cursor, empty for a spell with no target
#     scroll           the item template of the scroll that holds the spell
#     enabled          false takes the spell out of the game
# ==============================================================================
"""

# The name of a spell in UOX3 -> (key, name shown): the spelling the client uses.
NAMES = {
    "Reactive Armour": ("reactive_armor", "Reactive Armor"),
    "Flamestrike": ("flame_strike", "Flame Strike"),
}

# The words of a spell by its key where UOX3 has a typo; every other spell keeps the words of its file.
MANTRAS = {
    "create_food": "In Mani Ylem",
    "flame_strike": "Kal Vas Flam",
}

# The reagents of UOX3, by the field that counts them, as the item templates of this server.
REAGENTS: list[tuple[str, str]] = [
    ("PEARL", "0x0f7a_black_pearl"),
    ("MOSS", "0x0f7b_blood_moss"),
    ("GARLIC", "0x0f84_garlic"),
    ("GINSENG", "0x0f85_ginseng"),
    ("DRAKE", "0x0f86_mandrake_root"),
    ("SHADE", "0x0f88_nightshade"),
    ("ASH", "0x0f8c_sulfurous_ash"),
    ("SILK", "0x0f8d_spider_silk"),
]

# What the cursor of a spell asks for when its flags do not say well enough, by the client's number: the area spells and the
# ones that take a rune or a field are aimed at a place or an item, though UOX3 flags them as a character.
TARGETS: dict[int, str] = {
    13: "item",
    14: "item",
    19: "item",
    21: "item",
    22: "location",
    23: "item",
    24: "location",
    25: "location",
    26: "location",
    28: "location",
    32: "item",
    33: "location",
    34: "item",
    35: "none",
    36: "none",
    39: "location",
    40: "none",
    45: "item",
    46: "location",
    47: "location",
    48: "location",
    49: "location",
    50: "location",
    52: "item",
    54: "location",
    55: "location",
    56: "none",
    57: "none",
    58: "location",
    60: "none",
    61: "none",
    62: "none",
    63: "none",
    64: "none",
}

# Spells UOX3 flags as aggressive that are not harmful: they block, or call a creature.
NOT_HARMFUL = {24, 33, 50, 58, 60, 61, 62, 63, 64}

# The scroll of Reactive Armor comes before the others of the first circle in the client's items.
_SCROLL_FIRST = 0x1F2D
_REACTIVE_ARMOR = 7
_FLAG_REQUIRES_TARGET = 0x1
_FLAG_ITEM = 0x2
_FLAG_LOCATION = 0x4
_FLAG_CHARACTER = 0x8
_FLAG_REFLECTABLE = 0x40
_FLAG_AGGRESSIVE = 0x80
_FLAG_RESISTABLE = 0x100
_ID_LINE = re.compile(r'^id\s*=\s*"([^"]+)"', re.MULTILINE)


class ConversionError(Exception):
    """A source file or a template the converter cannot do without."""


def scroll_graphic(spell_id: int) -> int:
    """The graphic of the scroll of a spell: 0x1F2D is Reactive Armor, 0x1F2E Clumsy, and the rest follow the client's numbers."""
    if spell_id == _REACTIVE_ARMOR:
        return _SCROLL_FIRST

    return _SCROLL_FIRST + spell_id if spell_id < _REACTIVE_ARMOR else _SCROLL_FIRST + spell_id - 1


def scroll_templates(items: Path) -> dict[int, str]:
    """The canonical scroll templates of this server (the ones whose id starts with the graphic) by their graphic."""
    found: dict[int, str] = {}

    for path in sorted(items.rglob("*.toml")):
        for entry in tomllib.loads(path.read_text(encoding="utf-8")).get("item", []):
            identifier = entry.get("id", "")
            graphic = entry.get("item_id", 0)

            if isinstance(graphic, int) and graphic and identifier.startswith("0x") and identifier.endswith("_scroll"):
                found.setdefault(graphic, identifier)

    return found


def template_ids(items: Path) -> set[str]:
    """The ids of the item templates of this server."""
    ids: set[str] = set()

    for path in items.rglob("*.toml"):
        ids.update(_ID_LINE.findall(path.read_text(encoding="utf-8")))

    return ids


def key_of(name: str) -> tuple[str, str]:
    """The key and the name shown of a spell, from its name in UOX3."""
    if name in NAMES:
        return NAMES[name]

    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_"), name


def kind_of(spell_id: int, flags: int) -> str:
    """What the cursor of a spell asks for."""
    if spell_id in TARGETS:
        return TARGETS[spell_id]

    if not flags & _FLAG_REQUIRES_TARGET and not flags & (_FLAG_ITEM | _FLAG_LOCATION | _FLAG_CHARACTER):
        return "none"

    if flags & _FLAG_CHARACTER:
        return "mobile"

    if flags & _FLAG_LOCATION:
        return "location"

    return "item" if flags & _FLAG_ITEM else "none"


def effect_of(text: str | None) -> tuple[int, int]:
    """The graphic and the length of a STATFX line, such as ``37 6A 00 20``; zeros for a spell with none."""
    if text is None:
        return 0, 0

    parts = text.split()

    if len(parts) < 4:
        return 0, 0

    return int(parts[0] + parts[1], 16), int(parts[3], 16)


def projectile_of(text: str | None) -> tuple[int, int]:
    """The graphic and the speed of a MOVEFX line, such as ``36 E4 05 00 00``; zeros for a spell with none."""
    if text is None:
        return 0, 0

    parts = text.split()

    if len(parts) < 3:
        return 0, 0

    return int(parts[0] + parts[1], 16), int(parts[2], 16)


def number(text: str | None, default: int = 0) -> int:
    """A UOX3 number, decimal or ``0x`` hex; the default for a missing or bad one."""
    value = dfn.uox_number(text) if text is not None else None

    return default if value is None else value


def read(source: Path, scrolls: dict[int, str], templates: set[str]) -> list[dict]:
    """The spells of a ``spells.dfn``, as the dictionaries of the file, by the client's number."""
    spells: dict[int, dict] = {}

    for block in dfn.parse(read_lines(source)):
        parts = block.header.split()

        if len(parts) != 2 or parts[0].upper() != "SPELL" or not parts[1].isdigit():
            continue

        spell_id = int(parts[1])

        if not 1 <= spell_id <= SPELL_COUNT:
            raise ConversionError(f"the spell number {spell_id} is out of 1 to {SPELL_COUNT}")

        fields = block.fields

        if "NAME" not in fields:
            raise ConversionError(f"the spell {spell_id} has no NAME")

        key, name = key_of(trim(fields["NAME"]))
        flags = number(fields.get("FLAGS"))
        kind = kind_of(spell_id, flags)
        graphic = scroll_graphic(spell_id)

        if graphic not in scrolls:
            raise ConversionError(f"no scroll template has the graphic 0x{graphic:04X} of {name}")

        reagents = []

        for field, template in REAGENTS:
            amount = number(fields.get(field))

            if amount > 0:
                if template not in templates:
                    raise ConversionError(f"the reagent template {template} of {name} is not in the item templates")

                reagents.append({"template": template, "amount": amount})

        effect, effect_duration = effect_of(fields.get("STATFX"))
        projectile, projectile_speed = projectile_of(fields.get("MOVEFX"))
        spells[spell_id] = {
            "id": spell_id,
            "key": key,
            "name": name,
            "circle": number(fields.get("CIRCLE")),
            "mantra": MANTRAS.get(key) or trim(fields.get("MANTRA", "")),
            "action": number(fields.get("ACTION")),
            "reagents": reagents,
            "target": kind,
            "harmful": bool(flags & _FLAG_AGGRESSIVE) and spell_id not in NOT_HARMFUL,
            "resistable": bool(flags & _FLAG_RESISTABLE),
            "reflectable": bool(flags & _FLAG_REFLECTABLE),
            "sound": number(fields.get("SOUNDFX")),
            "effect": effect,
            "effect_duration": effect_duration,
            "projectile": projectile,
            "projectile_speed": projectile_speed,
            "prompt": trim(fields.get("TARG", "")) if kind != "none" else "",
            "scroll": scrolls[graphic],
            "enabled": number(fields.get("ENABLE"), 1) != 0,
        }

    missing = [spell_id for spell_id in range(1, SPELL_COUNT + 1) if spell_id not in spells]

    if missing:
        raise ConversionError(f"the spells {missing} are not in {source.name}")

    return [spells[spell_id] for spell_id in sorted(spells)]


def _hex(value: int) -> str:
    """A graphic or a sound as the hex the client files and the scripts use; 0 stays 0."""
    return f"0x{value:04X}" if value else "0"


def write(spells: list[dict]) -> str:
    """The text of ``spells.toml``."""
    lines = [HEADER.rstrip("\n"), ""]

    for index, spell in enumerate(spells):
        if index:
            lines.append("")

        lines.append("[[spell]]")
        lines.append(f"id = {spell['id']}")
        lines.append(f"key = {tomlout.basic(spell['key'])}")
        lines.append(f"name = {tomlout.basic(spell['name'])}")
        lines.append(f"circle = {spell['circle']}")
        lines.append(f"mantra = {tomlout.basic(spell['mantra'])}")
        lines.append(f"action = {spell['action']}")
        reagents = ", ".join(
            f"{{ template = {tomlout.basic(reagent['template'])}, amount = {reagent['amount']} }}" for reagent in spell["reagents"]
        )
        lines.append(f"reagents = [{reagents}]")
        lines.append(f"target = {tomlout.basic(spell['target'])}")
        lines.append(f"harmful = {str(spell['harmful']).lower()}")
        lines.append(f"resistable = {str(spell['resistable']).lower()}")
        lines.append(f"reflectable = {str(spell['reflectable']).lower()}")
        lines.append(f"sound = {_hex(spell['sound'])}")
        lines.append(f"effect = {_hex(spell['effect'])}")
        lines.append(f"effect_duration = {spell['effect_duration']}")
        lines.append(f"projectile = {_hex(spell['projectile'])}")
        lines.append(f"projectile_speed = {spell['projectile_speed']}")
        lines.append(f"prompt = {tomlout.basic(spell['prompt'])}")
        lines.append(f"scroll = {tomlout.basic(spell['scroll'])}")
        lines.append(f"enabled = {str(spell['enabled']).lower()}")

    return "\n".join(lines) + "\n"


def run(source: Path, items: Path, destination: Path, output: TextIO, error: TextIO) -> int:
    """Converts the ``spells.dfn`` of ``source`` (UOX3's ``dfndata/spells`` folder, or the file) into ``destination/spells.toml``."""
    source, items, destination = (Path(os.path.abspath(path)) for path in (source, items, destination))
    path = source / SPELLS_FILE if source.is_dir() else source

    if not path.is_file():
        error.write(f"{SPELLS_FILE} is missing from {source}\n")

        return 2

    try:
        spells = read(path, scroll_templates(items), template_ids(items))
    except (ConversionError, OSError, tomllib.TOMLDecodeError) as exception:
        error.write(f"Spells conversion failed: {exception}\n")

        return 2

    write_text(destination / FILE, write(spells))
    output.write(f"{FILE}: {len(spells)} spell(s)\n")

    return 0
