using System.Data.Common;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using Moongate.Core.Attributes;
using Moongate.Core.Interfaces.Entities;
using Moongate.Core.Primitives;
using Npgsql;

namespace Moongate.Persistence.Internal;

/// <summary>
///     Manages serial sequences through schema migrations and resolves them through column ownership.
/// </summary>
internal static class PersistenceSerialSequence
{
    public static async Task<string> CompareAsync(
        PostgreSqlDatabase database,
        IEnumerable<Type> entityTypes,
        CancellationToken cancellationToken
    )
    {
        var sql = new StringBuilder();
        await using var connection = new NpgsqlConnection(database.SchemaConnectionString);
        await connection.OpenAsync(cancellationToken).ConfigureAwait(false);

        foreach (var type in entityTypes)
        {
            var table = database.Orm.CodeFirst.GetTableByEntity(type);
            var column = table.ColumnsByCs[nameof(IMoongateEntity.Id)];
            var parts = table.DbName.Split('.', 2);
            var quotedTable = Quote(parts[0]) + "." + Quote(parts[1]);
            var quotedColumn = Quote(column.Attribute.Name);

            // An entity whose serials live in a range (world items) starts its sequence at the range minimum; rows
            // already stored continue after the highest id, as for every other entity.
            var first = type.GetCustomAttribute<SerialRangeAttribute>()?.Min ?? 1;
            await using var command = new NpgsqlCommand(
                """
                SELECT s.seqmin, s.seqmax, s.seqincrement, s.seqcycle, s.seqrelid::regclass::text
                FROM pg_sequence s
                WHERE s.seqrelid = CASE WHEN to_regclass(@table) IS NULL THEN NULL
                    ELSE pg_get_serial_sequence(@table, (
                        SELECT attname FROM pg_attribute
                        WHERE attrelid = to_regclass(@table) AND attnum > 0 AND NOT attisdropped
                            AND attname IN (@column, @old_column)
                        ORDER BY (attname = @column) DESC LIMIT 1
                    ))::regclass END
                """,
                connection
            );
            command.Parameters.AddWithValue("table", table.DbName);
            command.Parameters.AddWithValue("column", column.Attribute.Name);
            command.Parameters.AddWithValue("old_column", column.Attribute.OldName ?? column.Attribute.Name);
            await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);

            if (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                if (reader.GetInt64(0) != 1 ||
                    reader.GetInt64(1) != uint.MaxValue ||
                    reader.GetInt64(2) != 1 ||
                    reader.GetBoolean(3))
                {
                    throw new InvalidOperationException(
                        $"The Serial sequence for '{table.DbName}' must use MINVALUE 1, MAXVALUE {uint.MaxValue}, INCREMENT 1 and NO CYCLE."
                    );
                }

                var existing = reader.GetString(4);
                await reader.DisposeAsync().ConfigureAwait(false);

                // A sequence created before its entity declared a range (a development database generated by an
                // older version) would keep handing out serials below it; move it forward, never back.
                if (first > 1 && await NextValueAsync(connection, existing, cancellationToken).ConfigureAwait(false) < first)
                {
                    existing = existing.Replace("'", "''", StringComparison.Ordinal);
                    sql.AppendLine(
                        $$"""
                          DO $moongate_serial$
                          DECLARE highest_id bigint;
                          BEGIN
                              LOCK TABLE {{quotedTable}} IN SHARE ROW EXCLUSIVE MODE;
                              SELECT COALESCE(MAX({{quotedColumn}}), 0) INTO highest_id FROM {{quotedTable}};
                              PERFORM setval('{{existing}}'::regclass, GREATEST(highest_id, {{first}}), highest_id >= {{first}});
                          END
                          $moongate_serial$;
                          """
                    );
                }

                continue;
            }

            var name = parts[1] + "_" + column.Attribute.Name + "_seq";

            if (name.Length > 63)
            {
                var suffix = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(name)))[..16];
                name = name[..46] + "_" + suffix;
            }

            var sequence = Quote(parts[0]) + "." + Quote(name);

            // A DO statement is atomic even in the legacy schema-sync path. Do not adopt unrelated existing objects.
            sql.AppendLine(
                $$"""
                  DO $moongate_serial$
                  DECLARE highest_id bigint;
                  BEGIN
                      LOCK TABLE {{quotedTable}} IN SHARE ROW EXCLUSIVE MODE;
                      SELECT COALESCE(MAX({{quotedColumn}}), 0) INTO highest_id FROM {{quotedTable}};
                      IF highest_id < 0 OR highest_id > {{uint.MaxValue}} THEN
                          RAISE EXCEPTION 'Existing identity is outside the Serial range';
                      END IF;
                      CREATE SEQUENCE {{sequence}} AS bigint MINVALUE 1 MAXVALUE {{uint.MaxValue}} START WITH {{first}} NO CYCLE;
                      ALTER SEQUENCE {{sequence}} OWNED BY {{quotedTable}}.{{quotedColumn}};
                      PERFORM setval('{{sequence.Replace("'", "''", StringComparison.Ordinal)}}'::regclass,
                          GREATEST(highest_id, {{first}}), highest_id >= {{first}});
                  END
                  $moongate_serial$;
                  """
            );
        }

        return sql.ToString();
    }

    public static async Task<Serial> ReserveAsync<T>(
        IFreeSql orm,
        DbTransaction? transaction,
        CancellationToken cancellationToken
    ) where T : class, IMoongateEntity
    {
        var table = orm.CodeFirst.GetTableByEntity(typeof(T));
        var column = table.ColumnsByCs[nameof(IMoongateEntity.Id)];
        var value = await orm.Ado
            .CommandFluent(
                "SELECT nextval(pg_get_serial_sequence(@table, @column)::regclass)",
                new { table = table.DbName, column = column.Attribute.Name }
            )
            .WithTransaction(transaction)
            .ExecuteScalarAsync(cancellationToken)
            .ConfigureAwait(false);

        if (value is null or DBNull)
        {
            throw new InvalidOperationException(
                $"No Serial sequence is attached to '{table.DbName}.{column.Attribute.Name}'. Generate and apply its SQL migration."
            );
        }

        var serial = Convert.ToInt64(value);

        if (serial <= 0 || serial > uint.MaxValue)
        {
            throw new InvalidOperationException("The sequence returned a value outside the nonzero Serial range.");
        }

        return new((uint)serial);
    }

    /// <summary>
    ///     The value <c>nextval</c> would return, read from the sequence itself: <c>pg_sequences.last_value</c> is null
    ///     until the sequence is first used or after <c>setval(..., false)</c>.
    /// </summary>
    private static async Task<long> NextValueAsync(
        NpgsqlConnection connection,
        string sequence,
        CancellationToken cancellationToken
    )
    {
        // The name is the sequence's own regclass text, already quoted where needed.
        await using var command = new NpgsqlCommand(
            $"SELECT CASE WHEN is_called THEN last_value + 1 ELSE last_value END FROM {sequence}",
            connection
        );

        // Safe: the sequence query always returns a bigint scalar.
        return (long)(await command.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false))!;
    }

    private static string Quote(string identifier)
    {
        return '"' + identifier.Replace("\"", "\"\"", StringComparison.Ordinal) + '"';
    }
}
