require("ai.behavior")
require("ai.behaviors")
require("ai.brains.guard")
require("ai.brains.utility_npc")
require("ai.orion")
require("ai.vega")
require("commands.gm.eclipse")
require("commands.gm.set_world_light")
require("commands.gm.spawn_tools")
require("commands.gm.teleports")
require("items.apple")
require("items.brick")
require("items.door")
require("items.dye_box")
require("items.dye_tub")
require("items.spawn")
require("items.teleport")

function on_player_connected(p)
    log.info("Anvedi che s'e connesso un client")
end

function on_ready()
    log.info("Random direction is " .. random.direction())
end
