<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DryIoc.dll" Version="5.4.3"/>
        <PackageReference Include="Humanizer.Core" Version="3.0.10">
            <ExcludeAssets>buildTransitive;analyzers</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="ShaiRandom" Version="0.0.2"/>
        <PackageReference Include="Tomlyn" Version="2.10.1" />
        <PackageReference Include="ZLinq" Version="1.5.6"/>
        <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.401">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>

    </ItemGroup>


    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <DebugType Condition="'$(Configuration)' == 'Release'">portable</DebugType>
        <PackageId>Moongate.Core</PackageId>
        <Description>Shared primitives, geometry, collections, configuration helpers, and utilities for Moongate applications.</Description>
        <PackageTags>moongate;ultima-online;utilities;geometry</PackageTags>
    </PropertyGroup>

</Project>
