[[item]]
id = "base_map"
base_id = "0x14ec_blank_map"
item_id = 5356
name = "map"
rarity = "common"

[[item]]
id = "smallworldmap"
base_id = "base_map"
item_id = 0
name = "small world map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "1"
map_width = "200"
map_height = "200"
map_x1 = "0"
map_y1 = "0"
map_x2 = "5119"
map_y2 = "4095"
map_facet = "0"

[[item]]
id = "largeworldmap"
base_id = "base_map"
item_id = 0
name = "large world map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "2"
map_width = "400"
map_height = "400"
map_x1 = "0"
map_y1 = "0"
map_x2 = "5119"
map_y2 = "4095"
map_facet = "0"

[[item]]
id = "britainmap"
base_id = "base_map"
item_id = 0
name = "britain map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "3"
map_width = "200"
map_height = "200"
map_x1 = "1092"
map_y1 = "1396"
map_x2 = "1736"
map_y2 = "1924"
map_facet = "0"

[[item]]
id = "britaintoskarabraemap"
base_id = "base_map"
item_id = 0
name = "britain to skara brae map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "4"
map_width = "200"
map_height = "200"
map_x1 = "256"
map_y1 = "1792"
map_x2 = "1736"
map_y2 = "2560"
map_facet = "0"

[[item]]
id = "britaintotrinsicmap"
base_id = "base_map"
item_id = 0
name = "britain to trinsic map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "5"
map_width = "200"
map_height = "200"
map_x1 = "1024"
map_y1 = "1280"
map_x2 = "2304"
map_y2 = "3072"
map_facet = "0"

[[item]]
id = "bucsdenmap"
base_id = "base_map"
item_id = 0
name = "bucs den map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "6"
map_width = "200"
map_height = "200"
map_x1 = "2500"
map_y1 = "1900"
map_x2 = "3000"
map_y2 = "2400"
map_facet = "0"

[[item]]
id = "bucsdentomaginciamap"
base_id = "base_map"
item_id = 0
name = "bucs den to magincia map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "7"
map_width = "200"
map_height = "200"
map_x1 = "2560"
map_y1 = "1792"
map_x2 = "3840"
map_y2 = "2560"
map_facet = "0"

[[item]]
id = "bucsdentoocllomap"
base_id = "base_map"
item_id = 0
name = "bucs den to ocllo map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "8"
map_width = "200"
map_height = "200"
map_x1 = "2560"
map_y1 = "1792"
map_x2 = "3840"
map_y2 = "3072"
map_facet = "0"

[[item]]
id = "jhelommap"
base_id = "base_map"
item_id = 0
name = "jhelom map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "9"
map_width = "200"
map_height = "200"
map_x1 = "1088"
map_y1 = "3572"
map_x2 = "1528"
map_y2 = "4056"
map_facet = "0"

[[item]]
id = "maginciamap"
base_id = "base_map"
item_id = 0
name = "magincia map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "10"
map_width = "200"
map_height = "200"
map_x1 = "3530"
map_y1 = "2022"
map_x2 = "3818"
map_y2 = "2298"
map_facet = "0"

[[item]]
id = "maginciatoocllomap"
base_id = "base_map"
item_id = 0
name = "magincia to ocllo map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "11"
map_width = "200"
map_height = "200"
map_x1 = "3328"
map_y1 = "1792"
map_x2 = "3840"
map_y2 = "2304"
map_facet = "0"

[[item]]
id = "minocmap"
base_id = "base_map"
item_id = 0
name = "minoc map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "12"
map_width = "200"
map_height = "200"
map_x1 = "2360"
map_y1 = "356"
map_x2 = "2706"
map_y2 = "702"
map_facet = "0"

[[item]]
id = "minoctoyewmap"
base_id = "base_map"
item_id = 0
name = "minoc to yew map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "13"
map_width = "200"
map_height = "200"
map_x1 = "0"
map_y1 = "256"
map_x2 = "2304"
map_y2 = "3072"
map_facet = "0"

[[item]]
id = "minoctovespermap"
base_id = "base_map"
item_id = 0
name = "minoc to vesper map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "14"
map_width = "200"
map_height = "200"
map_x1 = "2467"
map_y1 = "572"
map_x2 = "2878"
map_y2 = "746"
map_facet = "0"

[[item]]
id = "moonglowmap"
base_id = "base_map"
item_id = 0
name = "moonglow map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "15"
map_width = "200"
map_height = "200"
map_x1 = "4156"
map_y1 = "808"
map_x2 = "4732"
map_y2 = "1528"
map_facet = "0"

[[item]]
id = "moonglowtonujelmmap"
base_id = "base_map"
item_id = 0
name = "moonglow to nujelm map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "16"
map_width = "200"
map_height = "200"
map_x1 = "3328"
map_y1 = "768"
map_x2 = "4864"
map_y2 = "1536"
map_facet = "0"

[[item]]
id = "nujelmmap"
base_id = "base_map"
item_id = 0
name = "nujelm map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "17"
map_width = "200"
map_height = "200"
map_x1 = "3446"
map_y1 = "1030"
map_x2 = "3832"
map_y2 = "1424"
map_facet = "0"

[[item]]
id = "nujelmtomaginciamap"
base_id = "base_map"
item_id = 0
name = "nujelm to magincia map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "18"
map_width = "200"
map_height = "200"
map_x1 = "3328"
map_y1 = "1024"
map_x2 = "3840"
map_y2 = "2304"
map_facet = "0"

[[item]]
id = "occlomap"
base_id = "base_map"
item_id = 0
name = "occlo map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "19"
map_width = "200"
map_height = "200"
map_x1 = "3582"
map_y1 = "2456"
map_x2 = "3770"
map_y2 = "2742"
map_facet = "0"

[[item]]
id = "serpentsholdmap"
base_id = "base_map"
item_id = 0
name = "serpents hold map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "20"
map_width = "200"
map_height = "200"
map_x1 = "2714"
map_y1 = "3329"
map_x2 = "3100"
map_y2 = "3639"
map_facet = "0"

[[item]]
id = "serpentsholdtoocllomap"
base_id = "base_map"
item_id = 0
name = "serpents hold to ocllo map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "21"
map_width = "200"
map_height = "200"
map_x1 = "2560"
map_y1 = "2560"
map_x2 = "3840"
map_y2 = "3840"
map_facet = "0"

[[item]]
id = "skarabraemap"
base_id = "base_map"
item_id = 0
name = "skara brae map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "22"
map_width = "200"
map_height = "200"
map_x1 = "524"
map_y1 = "2064"
map_x2 = "960"
map_y2 = "2452"
map_facet = "0"

[[item]]
id = "trinsicmap"
base_id = "base_map"
item_id = 0
name = "trinsic map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "23"
map_width = "200"
map_height = "200"
map_x1 = "1792"
map_y1 = "2630"
map_x2 = "2118"
map_y2 = "2952"
map_facet = "0"

[[item]]
id = "trinsictobucsdenmap"
base_id = "base_map"
item_id = 0
name = "trinsic to bucs den map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "24"
map_width = "200"
map_height = "200"
map_x1 = "1792"
map_y1 = "1792"
map_x2 = "3072"
map_y2 = "3072"
map_facet = "0"

[[item]]
id = "trinsictojhelommap"
base_id = "base_map"
item_id = 0
name = "trinsic to jhelom map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "25"
map_width = "200"
map_height = "200"
map_x1 = "256"
map_y1 = "1792"
map_x2 = "2304"
map_y2 = "4095"
map_facet = "0"

[[item]]
id = "vespermap"
base_id = "base_map"
item_id = 0
name = "vesper map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "26"
map_width = "200"
map_height = "200"
map_x1 = "2636"
map_y1 = "592"
map_x2 = "3064"
map_y2 = "1012"
map_facet = "0"

[[item]]
id = "vespertonujelmmap"
base_id = "base_map"
item_id = 0
name = "vesper to nujelm map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "27"
map_width = "200"
map_height = "200"
map_x1 = "2636"
map_y1 = "592"
map_x2 = "3840"
map_y2 = "1536"
map_facet = "0"

[[item]]
id = "yewmap"
base_id = "base_map"
item_id = 0
name = "yew map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "28"
map_width = "200"
map_height = "200"
map_x1 = "236"
map_y1 = "741"
map_x2 = "766"
map_y2 = "1269"
map_facet = "0"

[[item]]
id = "yewtobritainmap"
base_id = "base_map"
item_id = 0
name = "yew to britain map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "29"
map_width = "200"
map_height = "200"
map_x1 = "0"
map_y1 = "512"
map_x2 = "1792"
map_y2 = "2048"
map_facet = "0"

[[item]]
id = "tokunomap"
base_id = "base_map"
item_id = 0
name = "tokunomap"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "30"
map_width = "400"
map_height = "400"
map_x1 = "0"
map_y1 = "0"
map_x2 = "1448"
map_y2 = "1430"
map_facet = "4"

[[item]]
id = "malasmap"
base_id = "base_map"
item_id = 0
name = "malas map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "31"
map_width = "400"
map_height = "400"
map_x1 = "520"
map_y1 = "0"
map_x2 = "2580"
map_y2 = "2050"
map_facet = "3"

[[item]]
id = "ilshenarmap"
base_id = "base_map"
item_id = 0
name = "ilshenar map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "32"
map_width = "400"
map_height = "400"
map_x1 = "130"
map_y1 = "136"
map_x2 = "1927"
map_y2 = "1468"
map_facet = "2"

[[item]]
id = "termurmap"
base_id = "base_map"
item_id = 0
name = "termur map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "33"
map_width = "400"
map_height = "400"
map_x1 = "260"
map_y1 = "2780"
map_x2 = "1280"
map_y2 = "4090"
map_facet = "5"

[[item]]
id = "craftedlocalmap"
base_id = "base_map"
item_id = 0
name = "local map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "50"

[[item]]
id = "craftedcitymap"
base_id = "base_map"
item_id = 0
name = "city map"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "50"

[[item]]
id = "craftedseachart"
base_id = "base_map"
item_id = 0
name = "sea chart"
rarity = "common"
script_id = "map_item"
[item.tags]
Map = "50"
