namespace Moongate.UO.Data.Types;

/// <summary>
/// The canonical Ultima Online skill identifiers. Values match the skill ids used as keys in
/// <c>MobileEntity.Skills</c> and the <c>Id</c> field of the server rules in <c>data/skills.yaml</c>.
/// This is the stable identity of a skill; the balancing rules live in the YAML data.
/// </summary>
public enum SkillName
{
    Alchemy = 0,
    Anatomy = 1,
    AnimalLore = 2,
    ItemIdentification = 3,
    ArmsLore = 4,
    Parrying = 5,
    Begging = 6,
    Blacksmithy = 7,
    BowcraftFletching = 8,
    Peacemaking = 9,
    Camping = 10,
    Carpentry = 11,
    Cartography = 12,
    Cooking = 13,
    DetectingHidden = 14,
    Discordance = 15,
    EvaluatingIntelligence = 16,
    Healing = 17,
    Fishing = 18,
    ForensicEvaluation = 19,
    Herding = 20,
    Hiding = 21,
    Provocation = 22,
    Inscription = 23,
    Lockpicking = 24,
    Magery = 25,
    ResistingSpells = 26,
    Tactics = 27,
    Snooping = 28,
    Musicianship = 29,
    Poisoning = 30,
    Archery = 31,
    SpiritSpeak = 32,
    Stealing = 33,
    Tailoring = 34,
    AnimalTaming = 35,
    TasteIdentification = 36,
    Tinkering = 37,
    Tracking = 38,
    Veterinary = 39,
    Swordsmanship = 40,
    MaceFighting = 41,
    Fencing = 42,
    Wrestling = 43,
    Lumberjacking = 44,
    Mining = 45,
    Meditation = 46,
    Stealth = 47,
    RemoveTrap = 48,
    Necromancy = 49,
    Focus = 50,
    Chivalry = 51,
    Bushido = 52,
    Ninjitsu = 53,
    Spellweaving = 54,
    Mysticism = 55,
    Imbuing = 56,
    Throwing = 57
}
