[[item]]
id = "0x0f62_t2a"
base_id = "base_spear"
item_id = 0
rarity = "common"
weight = 7.0
damage_min = 2
damage_max = 36
speed = 46
strength_required = 30
max_hits = 80
buy_price = 38
sell_price = 36

[[item]]
id = "tribalspear_t2a"
base_id = "base_spear"
item_id = 0
rarity = "common"
weight = 7.0
damage_min = 4
damage_max = 40
speed = 46
strength_required = 30
max_hits = 80
buy_price = 38
sell_price = 36

[[item]]
id = "0x1400_t2a"
base_id = "base_kryss"
item_id = 0
rarity = "common"
weight = 1.0
damage_min = 3
damage_max = 28
speed = 53
strength_required = 10
max_hits = 90
buy_price = 42
sell_price = 21

[[item]]
id = "0x1402_t2a"
base_id = "base_short_spear"
item_id = 0
rarity = "common"
weight = 4.0
damage_min = 4
damage_max = 32
speed = 50
strength_required = 15
max_hits = 70
buy_price = 32
sell_price = 16

[[item]]
id = "0x1404_t2a"
base_id = "base_war_fork"
item_id = 0
rarity = "common"
weight = 9.0
damage_min = 4
damage_max = 32
speed = 45
strength_required = 35
max_hits = 110
buy_price = 30
sell_price = 15

[[item]]
id = "0x0e87_t2a"
base_id = "base_pitchfork"
item_id = 0
rarity = "common"
weight = 10.0
damage_min = 4
damage_max = 16
speed = 45
strength_required = 15
max_hits = 60
buy_price = 25
sell_price = 12

[[item]]
id = "0x26be_t2a"
base_id = "base_pike"
item_id = 0
rarity = "common"
weight = 8.0
damage_min = 4
damage_max = 28
speed = 37
strength_required = 20
max_hits = 110
buy_price = 51
sell_price = 31

[[item]]
id = "0x26c0_t2a"
base_id = "base_lance"
item_id = 0
rarity = "common"
weight = 12.0
damage_min = 5
damage_max = 37
speed = 26
strength_required = 40
max_hits = 110
buy_price = 44
sell_price = 27

[[item]]
id = "0x27a7_t2a"
base_id = "base_lajatang"
item_id = 0
rarity = "common"
weight = 12.0
damage_min = 4
damage_max = 32
speed = 32
strength_required = 30
max_hits = 95
buy_price = 141
sell_price = 87

[[item]]
id = "0x27ab_t2a"
base_id = "base_tekagi"
item_id = 0
rarity = "common"
weight = 5.0
damage_min = 3
damage_max = 22
speed = 56
strength_required = 5
max_hits = 60
buy_price = 72
sell_price = 35

[[item]]
id = "0x27ad_t2a"
base_id = "base_kama"
item_id = 0
rarity = "common"
weight = 7.0
damage_min = 3
damage_max = 22
speed = 56
strength_required = 10
max_hits = 60
buy_price = 80
sell_price = 48

[[item]]
id = "0x27af_t2a"
base_id = "base_sai"
item_id = 0
rarity = "common"
weight = 7.0
damage_min = 3
damage_max = 22
speed = 56
strength_required = 10
max_hits = 60
buy_price = 73
sell_price = 45

[[item]]
id = "0x2d23_t2a"
base_id = "base_war_cleaver"
item_id = 0
rarity = "common"
weight = 5.0
damage_min = 3
damage_max = 22
speed = 50
strength_required = 10
max_hits = 60
buy_price = 39
sell_price = 20

[[item]]
id = "0x2d20_t2a"
base_id = "base_elven_spellblade"
item_id = 0
rarity = "common"
weight = 5.0
damage_min = 3
damage_max = 25
speed = 45
strength_required = 15
max_hits = 60
buy_price = 73
sell_price = 37

[[item]]
id = "0x48be_t2a"
base_id = "base_gargish_war_fork"
item_id = 0
rarity = "common"
weight = 9.0
damage_min = 4
damage_max = 32
speed = 45
strength_required = 35
max_hits = 110
buy_price = 30
sell_price = 15

[[item]]
id = "0x0907_t2a"
base_id = "base_shortblade"
item_id = 0
rarity = "common"
weight = 7.0
damage_min = 3
damage_max = 23
speed = 49
strength_required = 5
max_hits = 120
buy_price = 77
sell_price = 41

[[item]]
id = "0x08fe_t2a"
base_id = "base_bloodblade"
item_id = 0
rarity = "common"
weight = 3.0
damage_min = 3
damage_max = 15
speed = 55
strength_required = 5
max_hits = 95
buy_price = 63
sell_price = 34

[[item]]
id = "0x48bc_t2a"
base_id = "base_gargish_kryss"
item_id = 0
rarity = "common"
weight = 1.0
damage_min = 3
damage_max = 28
speed = 53
strength_required = 10
max_hits = 90
buy_price = 42
sell_price = 21

[[item]]
id = "0x48ca_t2a"
base_id = "base_gargish_lance"
item_id = 0
rarity = "common"
weight = 12.0
damage_min = 5
damage_max = 37
speed = 26
strength_required = 40
max_hits = 110
buy_price = 44
sell_price = 27

[[item]]
id = "0x48c8_t2a"
base_id = "base_gargish_pike"
item_id = 0
rarity = "common"
weight = 8.0
damage_min = 4
damage_max = 28
speed = 37
strength_required = 20
max_hits = 110
buy_price = 51
sell_price = 31

[[item]]
id = "0x0904_t2a"
base_id = "base_dual_pointed_spear"
item_id = 0
rarity = "common"
weight = 7.0
damage_min = 3
damage_max = 23
speed = 50
strength_required = 20
max_hits = 80
buy_price = 70
sell_price = 35

[[item]]
id = "0x48ce_t2a"
base_id = "base_gargish_tekagi"
item_id = 0
rarity = "common"
weight = 5.0
damage_min = 3
damage_max = 22
speed = 56
strength_required = 5
max_hits = 60
buy_price = 72
sell_price = 35

[[item]]
id = "0xa28a_t2a"
base_id = "base_spiked_whip"
item_id = 0
rarity = "common"
weight = 6.0
damage_min = 4
damage_max = 27
speed = 40
strength_required = 5
max_hits = 50
buy_price = 27
sell_price = 14
