[[item]]
id = "0x1440_t2a"
base_id = "base_cutlass"
item_id = 0
rarity = "common"
weight = 8.0
buy_price = 32
sell_price = 27
hue = 0

[[item]]
id = "0x13fe_t2a"
base_id = "base_katana"
item_id = 0
rarity = "common"
weight = 6.0
buy_price = 42
sell_price = 21
hue = 0

[[item]]
id = "0x0f5e_t2a"
base_id = "base_broadsword"
item_id = 0
rarity = "common"
weight = 6.0
buy_price = 44
sell_price = 22
hue = 0

[[item]]
id = "0x0f60_t2a"
base_id = "base_longsword"
item_id = 0
rarity = "common"
weight = 7.0
buy_price = 60
sell_price = 30
hue = 0

[[item]]
id = "0x13b7_t2a"
base_id = "base_long_sword"
item_id = 0
rarity = "common"
weight = 1.0
buy_price = 33
sell_price = 33
hue = 0

[[item]]
id = "0x13b5_t2a"
base_id = "base_scimitar"
item_id = 0
rarity = "common"
weight = 5.0
buy_price = 43
sell_price = 21
hue = 0

[[item]]
id = "0x13b9_t2a"
base_id = "base_viking_sword"
item_id = 0
rarity = "common"
weight = 6.0
buy_price = 66
sell_price = 33
hue = 0

[[item]]
id = "0x26bb_t2a"
base_id = "base_bone_harvester"
item_id = 0
rarity = "common"
weight = 3.0
buy_price = 44
sell_price = 21
hue = 0

[[item]]
id = "0x26c1_t2a"
base_id = "base_crescent_blade"
item_id = 0
rarity = "common"
weight = 1.0
buy_price = 49
sell_price = 25
hue = 0

[[item]]
id = "0x26ce_t2a"
base_id = "base_paladin_sword"
item_id = 0
rarity = "common"
weight = 6.0
buy_price = 45
sell_price = 23
hue = 0

[[item]]
id = "0x27a2_t2a"
base_id = "base_no_dachi"
item_id = 0
rarity = "common"
weight = 10.0
buy_price = 91
sell_price = 50
hue = 0

[[item]]
id = "0x27a4_t2a"
base_id = "base_wakizashi"
item_id = 0
rarity = "common"
weight = 5.0
buy_price = 48
sell_price = 24
hue = 0

[[item]]
id = "0x27a8_t2a"
base_id = "base_bokuto"
item_id = 0
rarity = "common"
weight = 7.0
buy_price = 26
sell_price = 13
hue = 0

[[item]]
id = "0x27a9_t2a"
base_id = "base_daisho"
item_id = 0
rarity = "common"
weight = 8.0
buy_price = 74
sell_price = 41
hue = 0

[[item]]
id = "0x2d29_t2a"
base_id = "base_elven_machete"
item_id = 0
rarity = "common"
weight = 6.0
buy_price = 24
sell_price = 12
hue = 0

[[item]]
id = "0x2d26_t2a"
base_id = "base_rune_blade"
item_id = 0
rarity = "common"
weight = 7.0
buy_price = 49
sell_price = 25
hue = 0

[[item]]
id = "0x090b_t2a"
base_id = "base_dread_sword"
item_id = 0
rarity = "common"
weight = 7.0
buy_price = 24
sell_price = 12
hue = 0

[[item]]
id = "0x48c6_t2a"
base_id = "base_gargish_bone_harvester"
item_id = 0
rarity = "common"
weight = 3.0
buy_price = 44
sell_price = 21
hue = 0

[[item]]
id = "0x090c_t2a"
base_id = "base_glass_sword"
item_id = 0
rarity = "common"
weight = 6.0
buy_price = 35
sell_price = 18
hue = 0

[[item]]
id = "0x48ae_t2a"
base_id = "base_gargish_cleaver"
item_id = 0
rarity = "common"
weight = 1.0
buy_price = 24
sell_price = 12
hue = 0

[[item]]
id = "0x48ba_t2a"
base_id = "base_gargish_katana"
item_id = 0
rarity = "common"
weight = 6.0
buy_price = 42
sell_price = 21
hue = 0

[[item]]
id = "0x48b6_t2a"
base_id = "base_gargish_butcher_knife"
item_id = 0
rarity = "common"
weight = 1.0
buy_price = 21
sell_price = 10
hue = 0

[[item]]
id = "0x0900_t2a"
base_id = "base_stone_war_sword"
item_id = 0
rarity = "common"
weight = 6.0
buy_price = 24
sell_price = 12
hue = 0

[[item]]
id = "0x0908_t2a"
base_id = "base_gargish_talwar"
item_id = 0
rarity = "common"
weight = 16.0
buy_price = 70
sell_price = 38
hue = 0

[[item]]
id = "0x48d0_t2a"
base_id = "base_gargish_daisho"
item_id = 0
rarity = "common"
weight = 8.0
buy_price = 74
sell_price = 41
hue = 0

[[item]]
id = "0xa28b_t2a"
base_id = "base_bladed_whip"
item_id = 0
rarity = "common"
weight = 5.0
buy_price = 24
sell_price = 12
hue = 0
