[[item]]
id = "0x090a_t2a"
base_id = "base_soul_glaive"
item_id = 0
rarity = "common"
weight = 9.0
damage_min = 8
damage_max = 39
speed = 21
strength_required = 45
max_hits = 95
buy_price = 77
sell_price = 39

[[item]]
id = "0x08ff_t2a"
base_id = "base_boomerang"
item_id = 0
rarity = "common"
weight = 4.0
damage_min = 5
damage_max = 29
speed = 30
strength_required = 20
max_hits = 85
buy_price = 32
sell_price = 16

[[item]]
id = "0x0901_t2a"
base_id = "base_cyclone"
item_id = 0
rarity = "common"
weight = 6.0
damage_min = 6
damage_max = 33
speed = 26
strength_required = 30
max_hits = 85
buy_price = 53
sell_price = 26
