[[item]]
id = "0x0df2_t2a"
base_id = "base_wand"
item_id = 0
rarity = "common"
weight = 2.0
damage_min = 2
damage_max = 6
speed = 35
strength_required = 1
max_hits = 70
buy_price = 30
sell_price = 15
