[[item]]
id = "0x2540_wall"
base_id = "base_item"
item_id = 9536
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2541_wall"
base_id = "base_item"
item_id = 9537
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2542_wall"
base_id = "base_item"
item_id = 9538
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2543_wall"
base_id = "base_item"
item_id = 9539
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2544_wall"
base_id = "base_item"
item_id = 9540
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2545_wall"
base_id = "base_item"
item_id = 9541
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2546_wall"
base_id = "base_item"
item_id = 9542
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2547_wall"
base_id = "base_item"
item_id = 9543
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2548_wall"
base_id = "base_item"
item_id = 9544
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2549_wall"
base_id = "base_item"
item_id = 9545
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x254a_wall"
base_id = "base_item"
item_id = 9546
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x254b_wall"
base_id = "base_item"
item_id = 9547
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x254c_wall"
base_id = "base_item"
item_id = 9548
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x254d_wall"
base_id = "base_item"
item_id = 9549
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x254e_wall"
base_id = "base_item"
item_id = 9550
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x254f_wall"
base_id = "base_item"
item_id = 9551
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2550_wall"
base_id = "base_item"
item_id = 9552
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2551_wall"
base_id = "base_item"
item_id = 9553
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2552_wall"
base_id = "base_item"
item_id = 9554
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x2553_wall"
base_id = "base_item"
item_id = 9555
name = "wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3ef2_jungle_wall"
base_id = "base_item"
item_id = 16114
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3ef3_jungle_wall"
base_id = "base_item"
item_id = 16115
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3ef4_jungle_wall"
base_id = "base_item"
item_id = 16116
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3ef5_jungle_wall"
base_id = "base_item"
item_id = 16117
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3ef6_jungle_wall"
base_id = "base_item"
item_id = 16118
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3ef7_jungle_wall"
base_id = "base_item"
item_id = 16119
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3ef9_jungle_wall"
base_id = "base_item"
item_id = 16121
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3efa_jungle_wall"
base_id = "base_item"
item_id = 16122
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3efb_jungle_wall"
base_id = "base_item"
item_id = 16123
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3efc_jungle_wall"
base_id = "base_item"
item_id = 16124
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3efd_jungle_wall"
base_id = "base_item"
item_id = 16125
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3efe_jungle_wall"
base_id = "base_item"
item_id = 16126
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3eff_jungle_wall"
base_id = "base_item"
item_id = 16127
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3f00_jungle_wall"
base_id = "base_item"
item_id = 16128
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3f01_jungle_wall"
base_id = "base_item"
item_id = 16129
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3f02_jungle_wall"
base_id = "base_item"
item_id = 16130
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3f03_jungle_wall"
base_id = "base_item"
item_id = 16131
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3f04_jungle_wall"
base_id = "base_item"
item_id = 16132
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3f05_jungle_wall"
base_id = "base_item"
item_id = 16133
name = "jungle wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3f06_window"
base_id = "base_item"
item_id = 16134
name = "window"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x121d_wall_carving"
base_id = "base_item"
item_id = 4637
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x121e_wall_carving"
base_id = "base_item"
item_id = 4638
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x121f_wall_carving"
base_id = "base_item"
item_id = 4639
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1220_wall_carving"
base_id = "base_item"
item_id = 4640
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1221_wall_carving"
base_id = "base_item"
item_id = 4641
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1222_wall_carving"
base_id = "base_item"
item_id = 4642
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1231_wall_carving"
base_id = "base_item"
item_id = 4657
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1232_wall_carving"
base_id = "base_item"
item_id = 4658
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1233_wall_carving"
base_id = "base_item"
item_id = 4659
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1234_wall_carving"
base_id = "base_item"
item_id = 4660
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1235_wall_carving"
base_id = "base_item"
item_id = 4661
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1237_wall_carving"
base_id = "base_item"
item_id = 4663
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1238_wall_carving"
base_id = "base_item"
item_id = 4664
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1239_wall_carving"
base_id = "base_item"
item_id = 4665
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x123a_wall_carving"
base_id = "base_item"
item_id = 4666
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x123b_wall_carving"
base_id = "base_item"
item_id = 4667
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x123c_wall_carving"
base_id = "base_item"
item_id = 4668
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x123d_wall_carving"
base_id = "base_item"
item_id = 4669
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x123e_wall_carving"
base_id = "base_item"
item_id = 4670
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1240_wall_carving"
base_id = "base_item"
item_id = 4672
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1241_wall_carving"
base_id = "base_item"
item_id = 4673
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1242_wall_carving"
base_id = "base_item"
item_id = 4674
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1243_wall_carving"
base_id = "base_item"
item_id = 4675
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1244_wall_carving"
base_id = "base_item"
item_id = 4676
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1265_wall_carving"
base_id = "base_item"
item_id = 4709
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1266_wall_carving"
base_id = "base_item"
item_id = 4710
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1267_wall_carving"
base_id = "base_item"
item_id = 4711
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x12cc_wall_carving"
base_id = "base_item"
item_id = 4812
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x12cd_wall_carving"
base_id = "base_item"
item_id = 4813
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x12ce_wall_carving"
base_id = "base_item"
item_id = 4814
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x12cf_wall_carving"
base_id = "base_item"
item_id = 4815
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x12d0_wall_carving"
base_id = "base_item"
item_id = 4816
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x12d2_wall_carving"
base_id = "base_item"
item_id = 4818
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x12d3_wall_carving"
base_id = "base_item"
item_id = 4819
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x12d4_wall_carving"
base_id = "base_item"
item_id = 4820
name = "wall carving"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03a5_pier"
base_id = "base_item"
item_id = 933
name = "pier"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03a6_rope"
base_id = "base_item"
item_id = 934
name = "rope"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03a7_rope"
base_id = "base_item"
item_id = 935
name = "rope"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03a8_rope"
base_id = "base_item"
item_id = 936
name = "rope"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03a9_rope"
base_id = "base_item"
item_id = 937
name = "rope"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03aa_pier"
base_id = "base_item"
item_id = 938
name = "pier"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03ab_pier"
base_id = "base_item"
item_id = 939
name = "pier"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03ac_pier"
base_id = "base_item"
item_id = 940
name = "pier"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03ad_pier"
base_id = "base_item"
item_id = 941
name = "pier"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03ae_pier"
base_id = "base_item"
item_id = 942
name = "pier"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03af_pier"
base_id = "base_item"
item_id = 943
name = "pier"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03b0_pier"
base_id = "base_item"
item_id = 944
name = "pier"
rarity = "common"
movable = false
hue = 0
