[[item]]
id = "0x0149_plaster_wall"
item_id = 329
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x014a_plaster_wall"
item_id = 330
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x014b_plaster_wall"
item_id = 331
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x014c_plaster_wall"
item_id = 332
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x014d_plaster_wall"
item_id = 333
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x014e_plaster_wall"
item_id = 334
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x014f_plaster_wall"
item_id = 335
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0150_plaster_wall"
item_id = 336
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0151_plaster_wall"
item_id = 337
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0152_plaster_wall"
item_id = 338
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0153_plaster_wall"
item_id = 339
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0154_window"
item_id = 340
name = "window"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0155_window"
item_id = 341
name = "window"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0156_window"
item_id = 342
name = "window"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0157_window"
item_id = 343
name = "window"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0127_plaster_wall"
item_id = 295
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0128_plaster_wall"
item_id = 296
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0129_plaster_wall"
item_id = 297
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x012a_wooden_post"
item_id = 298
name = "wooden post"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x012c_plaster_wall"
item_id = 300
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x012d_plaster_wall"
item_id = 301
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x012e_plaster_wall"
item_id = 302
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x012f_plaster_wall"
item_id = 303
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0130_plaster_wall"
item_id = 304
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0131_plaster_wall"
item_id = 305
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0132_plaster_wall"
item_id = 306
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0133_plaster_wall"
item_id = 307
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0134_plaster_wall"
item_id = 308
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0135_plaster_wall"
item_id = 309
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0136_plaster_wall"
item_id = 310
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0137_plaster_wall"
item_id = 311
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0138_plaster_wall"
item_id = 312
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0139_plaster_wall"
item_id = 313
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x13a_window"
item_id = 314
name = "window"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x013b_window"
item_id = 315
name = "window"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x013c_archway"
item_id = 316
name = "archway"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x013d_archway"
item_id = 317
name = "archway"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x013e_archway"
item_id = 318
name = "archway"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x013f_archway"
item_id = 319
name = "archway"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0140_archway"
item_id = 320
name = "archway"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0141_wooden_beam"
item_id = 321
name = "wooden beam"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0142_wooden_beam"
item_id = 322
name = "wooden beam"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0143_wooden_beam"
item_id = 323
name = "wooden beam"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0144_wooden_beam"
item_id = 324
name = "wooden beam"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x01ff_plaster_wall"
item_id = 511
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0200_plaster_wall"
item_id = 512
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0201_plaster_wall"
item_id = 513
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0202_sandstone"
item_id = 514
name = "sandstone"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0203_plaster_wall"
item_id = 515
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0204_plaster_wall"
item_id = 516
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0205_plaster_wall"
item_id = 517
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0206_plaster_wall"
item_id = 518
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0207_window"
item_id = 519
name = "window"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0208_window"
item_id = 520
name = "window"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0209_window"
item_id = 521
name = "window"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x020a_window"
item_id = 522
name = "window"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x020b_plaster_wall"
item_id = 523
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x020c_plaster_wall"
item_id = 524
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x037f_plaster_wall"
item_id = 895
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0380_plaster_wall"
item_id = 896
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0381_plaster_wall"
item_id = 897
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0382_wooden_post"
item_id = 898
name = "wooden post"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0383_plaster_wall"
item_id = 899
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0384_plaster_wall"
item_id = 900
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0385_plaster_wall"
item_id = 901
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0386_plaster_wall"
item_id = 902
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0387_plaster_wall"
item_id = 903
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0388_plaster_wall"
item_id = 904
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0389_plaster_wall"
item_id = 905
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x038a_plaster_wall"
item_id = 906
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x038b_plaster_wall"
item_id = 907
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x038c_plaster_wall"
item_id = 908
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x038d_plaster_wall"
item_id = 909
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x038e_plaster_wall"
item_id = 910
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x038f_plaster_wall"
item_id = 911
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0390_plaster_wall"
item_id = 912
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0391_plaster_wall"
item_id = 913
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0392_plaster_wall"
item_id = 914
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0393_plaster_wall"
item_id = 915
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0394_plaster_wall"
item_id = 916
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0395_plaster_wall"
item_id = 917
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0396_plaster_wall"
item_id = 918
name = "plaster wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0397_archway"
item_id = 919
name = "archway"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0398_archway"
item_id = 920
name = "archway"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0399_archway"
item_id = 921
name = "archway"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x039a_archway"
item_id = 922
name = "archway"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x039b_archway"
item_id = 923
name = "archway"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x039c_wooden_beam"
item_id = 924
name = "wooden beam"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x039d_wooden_beast"
item_id = 925
name = "wooden beast"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x039e_wooden_beam"
item_id = 926
name = "wooden beam"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x039f_wooden_beam"
item_id = 927
name = "wooden beam"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x03a0_archway"
item_id = 928
name = "archway"
rarity = "common"
movable = false
hue = 0
