[[item]]
id = "0x01f0_tent_wall"
base_id = "base_item"
item_id = 496
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x01f1_tent_wall"
base_id = "base_item"
item_id = 497
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x01f2_tent_wall"
base_id = "base_item"
item_id = 498
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x01f3_tent_pole"
base_id = "base_item"
item_id = 499
name = "tent pole"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x01f4_tent_wall"
base_id = "base_item"
item_id = 500
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x01f5_tent_wall"
base_id = "base_item"
item_id = 501
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x01f6_tent_wall"
base_id = "base_item"
item_id = 502
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x01f7_tent_wall"
base_id = "base_item"
item_id = 503
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x01f8_tent_wall"
base_id = "base_item"
item_id = 504
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x01f9_tent_wall"
base_id = "base_item"
item_id = 505
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0230_tent_wall"
base_id = "base_item"
item_id = 560
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0231_tent_wall"
base_id = "base_item"
item_id = 561
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0232_tent_wall"
base_id = "base_item"
item_id = 562
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0233_tent_pole"
base_id = "base_item"
item_id = 563
name = "tent pole"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0234_tent_wall"
base_id = "base_item"
item_id = 564
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0235_tent_wall"
base_id = "base_item"
item_id = 565
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0236_tent_wall"
base_id = "base_item"
item_id = 566
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0237_tent_wall"
base_id = "base_item"
item_id = 567
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0238_tent_wall"
base_id = "base_item"
item_id = 568
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0239_tent_wall"
base_id = "base_item"
item_id = 569
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02de_tent_wall"
base_id = "base_item"
item_id = 734
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02df_tent_wall"
base_id = "base_item"
item_id = 735
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02e0_tent_wall"
base_id = "base_item"
item_id = 736
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02e1_wooden_pole"
base_id = "base_item"
item_id = 737
name = "wooden pole"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02e2_tent_wall"
base_id = "base_item"
item_id = 738
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02e3_tent_wall"
base_id = "base_item"
item_id = 739
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02e4_tent_wall"
base_id = "base_item"
item_id = 740
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02e5_tent_wall"
base_id = "base_item"
item_id = 741
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02e6_tent_wall"
base_id = "base_item"
item_id = 742
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02e7_tent_wall"
base_id = "base_item"
item_id = 743
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02e8_tent_wall"
base_id = "base_item"
item_id = 744
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02e9_tent_wall"
base_id = "base_item"
item_id = 745
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02ea_tent_wall"
base_id = "base_item"
item_id = 746
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02eb_tent_wall"
base_id = "base_item"
item_id = 747
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02ec_tent_wall"
base_id = "base_item"
item_id = 748
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02ef_patch"
base_id = "base_item"
item_id = 751
name = "patch"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02f0_patch"
base_id = "base_item"
item_id = 752
name = "patch"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02f1_patch"
base_id = "base_item"
item_id = 753
name = "patch"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02f2_patch"
base_id = "base_item"
item_id = 754
name = "patch"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02f3_patch"
base_id = "base_item"
item_id = 755
name = "patch"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x02f4_patch"
base_id = "base_item"
item_id = 756
name = "patch"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0368_tent_wall"
base_id = "base_item"
item_id = 872
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0369_tent_wall"
base_id = "base_item"
item_id = 873
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x036a_tent_wall"
base_id = "base_item"
item_id = 874
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x036b_tent_pole"
base_id = "base_item"
item_id = 875
name = "tent pole"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x036c_tent_wall"
base_id = "base_item"
item_id = 876
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x036d_tent_wall"
base_id = "base_item"
item_id = 877
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0365e_tent_wall"
base_id = "base_item"
item_id = 878
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x036f_tent_wall"
base_id = "base_item"
item_id = 879
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0370_tent_wall"
base_id = "base_item"
item_id = 880
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0371_tent_wall"
base_id = "base_item"
item_id = 881
name = "tent wall"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0372_patch"
base_id = "base_item"
item_id = 882
name = "patch"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0373_patch"
base_id = "base_item"
item_id = 883
name = "patch"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0374_patch"
base_id = "base_item"
item_id = 884
name = "patch"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0375_patch"
base_id = "base_item"
item_id = 885
name = "patch"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0376_patch"
base_id = "base_item"
item_id = 886
name = "patch"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0378_dagges"
base_id = "base_item"
item_id = 888
name = "dagges"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x037a_dagges"
base_id = "base_item"
item_id = 890
name = "dagges"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x037b_dagges"
base_id = "base_item"
item_id = 891
name = "dagges"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x037c_dagges"
base_id = "base_item"
item_id = 892
name = "dagges"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x037d_dagges"
base_id = "base_item"
item_id = 893
name = "dagges"
rarity = "common"
movable = false
hue = 0
