[[item]]
id = "0x1605_a_large_wooden_bowl"
base_id = "base_item"
item_id = 5637
name = "a large wooden bowl"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x15fd_a_pewter_bowl"
base_id = "base_item"
item_id = 5629
name = "a pewter bowl"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x0995_ceramic_mug"
base_id = "base_item"
item_id = 2453
name = "ceramic mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0996_ceramic_mug"
base_id = "base_item"
item_id = 2454
name = "ceramic mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0997_ceramic_mug"
base_id = "base_item"
item_id = 2455
name = "ceramic mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0998_ceramic_mug"
base_id = "base_item"
item_id = 2456
name = "ceramic mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0999_ceramic_mug"
base_id = "base_item"
item_id = 2457
name = "ceramic mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x099a_goblet"
base_id = "base_item"
item_id = 2458
name = "goblet"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09a7_glass_pitcher"
base_id = "base_item"
item_id = 2471
name = "glass pitcher"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x09ae_dirty_plate"
base_id = "base_item"
item_id = 2478
name = "dirty plate"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09ca_ceramic_mug"
base_id = "base_item"
item_id = 2506
name = "ceramic mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09cb_goblet"
base_id = "base_item"
item_id = 2507
name = "goblet"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09d6_pitcher"
base_id = "base_item"
item_id = 2518
name = "pitcher"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09d7_plate"
base_id = "base_item"
item_id = 2519
name = "plate"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09da_dirty_plate"
base_id = "base_item"
item_id = 2522
name = "dirty plate"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09de_dirty_frypan"
base_id = "base_item"
item_id = 2526
name = "dirty frypan"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09e8_dirty_pan"
base_id = "base_item"
item_id = 2536
name = "dirty pan"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09ed_kettle"
base_id = "base_item"
item_id = 2541
name = "kettle"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09f3_pan"
base_id = "base_item"
item_id = 2547
name = "pan"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0a19_dirty_plate"
base_id = "base_item"
item_id = 2585
name = "dirty plate"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0e78_basin"
base_id = "base_item"
item_id = 3704
name = "basin"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0ff6_glass_pitcher"
base_id = "base_item"
item_id = 4086
name = "glass pitcher"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0ff7_glass_pitcher"
base_id = "base_item"
item_id = 4087
name = "glass pitcher"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0ffa_bucket_of_water"
base_id = "base_item"
item_id = 4090
name = "bucket of water"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0ffb_skull_mug"
base_id = "base_item"
item_id = 4091
name = "skull mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0ffc_skull_mug"
base_id = "base_item"
item_id = 4092
name = "skull mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0ffd_skull_mug"
base_id = "base_item"
item_id = 4093
name = "skull mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0ffe_skull_mug"
base_id = "base_item"
item_id = 4094
name = "skull mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0fff_pewter_mug"
base_id = "base_item"
item_id = 4095
name = "pewter mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1000_pewter_mug"
base_id = "base_item"
item_id = 4096
name = "pewter mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1001_pewter_mug"
base_id = "base_item"
item_id = 4097
name = "pewter mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1002_pewter_mug"
base_id = "base_item"
item_id = 4098
name = "pewter mug"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1003_spittoon"
base_id = "base_item"
item_id = 4099
name = "spittoon"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1005_empty_jar"
base_id = "base_item"
item_id = 4101
name = "empty jar"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1006_full_jar"
base_id = "base_item"
item_id = 4102
name = "full jar"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1007_half_empty_jar"
base_id = "base_item"
item_id = 4103
name = "half empty jar"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1008_wash_basin"
base_id = "base_item"
item_id = 4104
name = "wash basin"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1009_basin"
base_id = "base_item"
item_id = 4105
name = "basin"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x10e3_dough_bowl"
base_id = "base_item"
item_id = 4323
name = "dough bowl"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e88_skinned_goat"
base_id = "base_item"
item_id = 7816
name = "skinned goat"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e89_skinned_goat"
base_id = "base_item"
item_id = 7817
name = "skinned goat"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e8a_lard"
base_id = "base_item"
item_id = 7818
name = "lard"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e8b_plucked_chicken"
base_id = "base_item"
item_id = 7819
name = "plucked chicken"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e8c_pig's_feet"
base_id = "base_item"
item_id = 7820
name = "pig's feet"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e8d_pig's_feet"
base_id = "base_item"
item_id = 7821
name = "pig's feet"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e8e_pig's_head"
base_id = "base_item"
item_id = 7822
name = "pig's head"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e8f_pig's_head"
base_id = "base_item"
item_id = 7823
name = "pig's head"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e90_skinned_deer"
base_id = "base_item"
item_id = 7824
name = "skinned deer"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e91_skinned_deer"
base_id = "base_item"
item_id = 7825
name = "skinned deer"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e92_skinned_rabbit"
base_id = "base_item"
item_id = 7826
name = "skinned rabbit"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e93_skinned_rabbit"
base_id = "base_item"
item_id = 7827
name = "skinned rabbit"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e94_chicken_on_a_spit"
base_id = "base_item"
item_id = 7828
name = "chicken on a spit"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e95_rabbit_on_a_spit"
base_id = "base_item"
item_id = 7829
name = "rabbit on a spit"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e96_spit"
base_id = "base_item"
item_id = 7830
name = "spit"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e97_chicken_on_a_spit"
base_id = "base_item"
item_id = 7831
name = "chicken on a spit"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e98_rabbit_on_a_spit"
base_id = "base_item"
item_id = 7832
name = "rabbit on a spit"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e99_spit"
base_id = "base_item"
item_id = 7833
name = "spit"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f81_glass"
base_id = "base_item"
item_id = 8065
name = "glass"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f82_glass"
base_id = "base_item"
item_id = 8066
name = "glass"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f83_glass"
base_id = "base_item"
item_id = 8067
name = "glass"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f84_glass"
base_id = "base_item"
item_id = 8068
name = "glass"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1882_winnowing_basket"
base_id = "base_item"
item_id = 6274
name = "winnowing basket"
rarity = "common"
movable = true
hue = 0
