using System.Globalization;
using System.Text;
using Moongate.Scripting.Binding;
using Moongate.Scripting.Data.Binding;
using Moongate.Scripting.Data.Luarc;

namespace Moongate.Scripting.Utils;

/// <summary>
///     Writes the Lua language server files that give editors completion for every bound module, constant and enum.
/// </summary>
internal static class LuaDefinitionsGenerator
{
    private const string DefinitionsFile = "definitions.lua";
    private const string LuarcFile = ".luarc.json";

    /// <summary>
    ///     Renders the LuaLS annotation text for every module, its functions and constants, every enum, and the
    ///     built-in <c>wait</c>.
    /// </summary>
    /// <param name="modules">
    ///     Every module bound at startup, in any order.
    /// </param>
    /// <param name="enums">
    ///     Every enum published as a global table, in any order.
    /// </param>
    /// <param name="eventNames">
    ///     The names published with <c>AddScriptEvent</c>; they become the <c>EventName</c> alias, which falls back to
    ///     <c>string</c> when there are none.
    /// </param>
    /// <returns>
    ///     The contents of <c>definitions.lua</c>. Always uses <c>\n</c> line endings, regardless of platform.
    /// </returns>
    public static string Render(
        IReadOnlyList<BoundModule> modules,
        IReadOnlyList<Type> enums,
        IReadOnlyList<string>? eventNames = null
    )
    {
        ArgumentNullException.ThrowIfNull(modules);
        ArgumentNullException.ThrowIfNull(enums);
        var builder = new StringBuilder();
        builder.Append("---@meta").Append('\n');
        builder.Append("-- Generated by Moongate at startup. Do not edit: every entry comes from a C# attribute.")
            .Append('\n');
        builder.Append('\n');
        builder.Append("---Suspends the running coroutine and resumes it on the game loop after the given seconds.")
            .Append('\n');
        builder.Append("---@param seconds number").Append('\n');
        builder.Append("---@return number seconds The seconds actually waited.").Append('\n');
        builder.Append("function wait(seconds) end").Append('\n');
        builder.Append('\n');

        var names = (eventNames ?? []).Order(StringComparer.Ordinal).ToList();
        builder.Append("---@alias EventName ")
            .Append(names.Count == 0 ? "string" : string.Join('|', names.Select(name => $"\"{name}\"")))
            .Append('\n');
        builder.Append('\n');

        foreach (var enumType in enums.OrderBy(type => type.Name, StringComparer.Ordinal))
        {
            builder.Append("---@enum ").Append(enumType.Name).Append('\n');
            builder.Append(enumType.Name).Append(" = {").Append('\n');

            foreach (var name in Enum.GetNames(enumType))
            {
                var value = Convert.ToInt64(Enum.Parse(enumType, name), CultureInfo.InvariantCulture);
                builder.Append("    ")
                    .Append(name)
                    .Append(" = ")
                    .Append(value.ToString(CultureInfo.InvariantCulture))
                    .Append(',')
                    .Append('\n');
            }

            builder.Append('}').Append('\n');
            builder.Append('\n');
        }

        foreach (var module in modules.OrderBy(module => module.Name, StringComparer.Ordinal))
        {
            if (module.HelpText is not null)
            {
                AppendHelp(builder, module.HelpText);
            }

            builder.Append("---@class ").Append(module.Name).Append('\n');

            var constants = module.Constants.OrderBy(constant => constant.LuaName, StringComparer.Ordinal).ToList();

            foreach (var constant in constants)
            {
                builder.Append("---@field ")
                    .Append(constant.LuaName)
                    .Append(' ')
                    .Append(LuaFunctionDescriber.LuaTypeName(constant.Type))
                    .Append('\n');
            }

            builder.Append(module.Name).Append(" = {}").Append('\n');

            foreach (var constant in constants)
            {
                builder.Append(module.Name)
                    .Append('.')
                    .Append(constant.LuaName)
                    .Append(" = ")
                    .Append(LuaFunctionDescriber.LuaLiteral(constant.Value, constant.Type))
                    .Append('\n');
            }

            builder.Append('\n');

            foreach (var function in module.Functions.OrderBy(function => function.LuaName, StringComparer.Ordinal))
            {
                AppendFunction(builder, module.Name, function);
            }
        }

        return builder.ToString();
    }

    /// <summary>
    ///     Writes <c>definitions.lua</c> and <c>.luarc.json</c> under <paramref name="scriptsDirectory" />, creating
    ///     the
    ///     directory if needed.
    /// </summary>
    /// <param name="scriptsDirectory">
    ///     Directory holding the scripts; the two files are written directly under it.
    /// </param>
    /// <param name="modules">
    ///     Every module bound at startup, in any order.
    /// </param>
    /// <param name="enums">
    ///     Every enum published as a global table, in any order.
    /// </param>
    /// <param name="eventNames">
    ///     The names published with <c>AddScriptEvent</c>, for the <c>EventName</c> alias.
    /// </param>
    public static void Write(
        string scriptsDirectory,
        IReadOnlyList<BoundModule> modules,
        IReadOnlyList<Type> enums,
        IReadOnlyList<string>? eventNames = null
    )
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(scriptsDirectory);
        Directory.CreateDirectory(scriptsDirectory);
        File.WriteAllText(
            Path.Combine(scriptsDirectory, DefinitionsFile),
            Render(modules, enums, eventNames),
            new UTF8Encoding(false)
        );

        var globals = modules.Select(module => module.Name)
            .Concat(enums.Select(type => type.Name))
            .Append("wait")
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToList();
        var luarc = new LuarcConfig { Diagnostics = new() { Globals = globals } };
        File.WriteAllText(Path.Combine(scriptsDirectory, LuarcFile), luarc.ToJson() + "\n", new UTF8Encoding(false));
    }

    private static void AppendFunction(StringBuilder builder, string moduleName, BoundFunction function)
    {
        if (function.HelpText is not null)
        {
            AppendHelp(builder, function.HelpText);
        }

        var description = LuaFunctionDescriber.Describe(function);

        // LuaLS resolves @param names positionally against the signature, so the varargs are annotated as "...",
        // matching the "..." the signature line below emits.
        foreach (var parameter in description.Parameters)
        {
            builder.Append("---@param ")
                .Append(parameter.Name)
                .Append(parameter.Optional ? "?" : "")
                .Append(' ')
                .Append(parameter.LuaType)
                .Append('\n');
        }

        if (description.Returns is not null)
        {
            builder.Append("---@return ").Append(description.Returns).Append('\n');
        }

        builder.Append("function ")
            .Append(moduleName)
            .Append('.')
            .Append(function.LuaName)
            .Append('(')
            .Append(string.Join(", ", description.Parameters.Select(parameter => parameter.Name)))
            .Append(") end")
            .Append('\n');
        builder.Append('\n');
    }

    /// <summary>
    ///     Writes each line of <paramref name="helpText" /> as its own <c>---</c> comment, so a multi-line summary
    ///     stays valid
    ///     LuaLS annotation syntax.
    /// </summary>
    private static void AppendHelp(StringBuilder builder, string helpText)
    {
        foreach (var line in helpText.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n'))
        {
            builder.Append("---").Append(line).Append('\n');
        }
    }
}
