using System.Globalization;
using System.Reflection;
using System.Text;
using Lua;
using Moongate.Scripting.Data.Binding;
using Moongate.Scripting.Data.Luarc;

namespace Moongate.Scripting.Utils;

/// <summary>Writes the Lua language server files that give editors completion for every bound module, constant and enum.</summary>
internal static class LuaDefinitionsGenerator
{
    private const string DefinitionsFile = "definitions.lua";
    private const string LuarcFile = ".luarc.json";

    /// <summary>
    /// Renders the LuaLS annotation text for every module, its functions and constants, every enum, and the built-in
    /// <c>wait</c>.
    /// </summary>
    /// <param name="modules">Every module bound at startup, in any order.</param>
    /// <param name="enums">Every enum published as a global table, in any order.</param>
    /// <returns>The contents of <c>definitions.lua</c>. Always uses <c>\n</c> line endings, regardless of platform.</returns>
    public static string Render(IReadOnlyList<BoundModule> modules, IReadOnlyList<Type> enums)
    {
        ArgumentNullException.ThrowIfNull(modules);
        ArgumentNullException.ThrowIfNull(enums);
        var builder = new StringBuilder();
        builder.Append("---@meta").Append('\n');
        builder.Append("-- Generated by Moongate at startup. Do not edit: every entry comes from a C# attribute.")
               .Append('\n');
        builder.Append('\n');
        builder.Append("---Suspends the running coroutine and resumes it on the game loop after the given seconds.")
               .Append('\n');
        builder.Append("---@param seconds number").Append('\n');
        builder.Append("---@return number seconds The seconds actually waited.").Append('\n');
        builder.Append("function wait(seconds) end").Append('\n');
        builder.Append('\n');

        foreach (var enumType in enums.OrderBy(type => type.Name, StringComparer.Ordinal))
        {
            builder.Append("---@enum ").Append(enumType.Name).Append('\n');
            builder.Append(enumType.Name).Append(" = {").Append('\n');

            foreach (var name in Enum.GetNames(enumType))
            {
                var value = Convert.ToInt64(Enum.Parse(enumType, name), CultureInfo.InvariantCulture);
                builder.Append("    ")
                       .Append(name)
                       .Append(" = ")
                       .Append(value.ToString(CultureInfo.InvariantCulture))
                       .Append(',')
                       .Append('\n');
            }

            builder.Append('}').Append('\n');
            builder.Append('\n');
        }

        foreach (var module in modules.OrderBy(module => module.Name, StringComparer.Ordinal))
        {
            if (module.HelpText is not null)
            {
                AppendHelp(builder, module.HelpText);
            }

            builder.Append("---@class ").Append(module.Name).Append('\n');

            var constants = module.Constants.OrderBy(constant => constant.LuaName, StringComparer.Ordinal).ToList();

            foreach (var constant in constants)
            {
                builder.Append("---@field ")
                       .Append(constant.LuaName)
                       .Append(' ')
                       .Append(LuaTypeName(constant.Type))
                       .Append('\n');
            }

            builder.Append(module.Name).Append(" = {}").Append('\n');

            foreach (var constant in constants)
            {
                builder.Append(module.Name)
                       .Append('.')
                       .Append(constant.LuaName)
                       .Append(" = ")
                       .Append(LuaLiteral(constant.Value, constant.Type))
                       .Append('\n');
            }

            builder.Append('\n');

            foreach (var function in module.Functions.OrderBy(function => function.LuaName, StringComparer.Ordinal))
            {
                AppendFunction(builder, module.Name, function);
            }
        }

        return builder.ToString();
    }

    /// <summary>
    /// Writes <c>definitions.lua</c> and <c>.luarc.json</c> under <paramref name="scriptsDirectory" />, creating the
    /// directory if needed.
    /// </summary>
    /// <param name="scriptsDirectory">Directory holding the scripts; the two files are written directly under it.</param>
    /// <param name="modules">Every module bound at startup, in any order.</param>
    /// <param name="enums">Every enum published as a global table, in any order.</param>
    public static void Write(string scriptsDirectory, IReadOnlyList<BoundModule> modules, IReadOnlyList<Type> enums)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(scriptsDirectory);
        Directory.CreateDirectory(scriptsDirectory);
        File.WriteAllText(Path.Combine(scriptsDirectory, DefinitionsFile), Render(modules, enums), new UTF8Encoding(false));

        var globals = modules.Select(module => module.Name)
                             .Concat(enums.Select(type => type.Name))
                             .Append("wait")
                             .Distinct(StringComparer.Ordinal)
                             .Order(StringComparer.Ordinal)
                             .ToList();
        var luarc = new LuarcConfig { Diagnostics = new() { Globals = globals } };
        File.WriteAllText(Path.Combine(scriptsDirectory, LuarcFile), luarc.ToJson() + "\n", new UTF8Encoding(false));
    }

    private static void AppendFunction(StringBuilder builder, string moduleName, BoundFunction function)
    {
        if (function.HelpText is not null)
        {
            AppendHelp(builder, function.HelpText);
        }

        var parameters = function.Method.GetParameters();
        var names = new List<string>();

        foreach (var parameter in parameters)
        {
            var isParams = parameter.GetCustomAttribute<ParamArrayAttribute>() is not null;

            // LuaLS resolves @param names positionally against the signature: a params parameter must be
            // annotated as "..." (never its CLR name), matching the "..." the signature line below emits.
            var type = isParams ? parameter.ParameterType.GetElementType()! : parameter.ParameterType;
            var name = isParams ? "..." : parameter.Name!;
            var optional = !isParams && (parameter.HasDefaultValue || IsNullableValueType(parameter.ParameterType))
                               ? "?"
                               : "";

            // The converter also accepts an enum member by name, so a script may pass the string; returns
            // stay the bare enum because the engine always hands back the number.
            var typeName = (Nullable.GetUnderlyingType(type) ?? type).IsEnum
                               ? LuaTypeName(type) + "|string"
                               : LuaTypeName(type);
            builder.Append("---@param ").Append(name).Append(optional).Append(' ').Append(typeName).Append('\n');
            names.Add(name);
        }

        if (function.Method.ReturnType != typeof(void))
        {
            var returnType = function.Method.ReturnType;
            var optional = IsNullableValueType(returnType) ? "?" : "";
            builder.Append("---@return ").Append(LuaTypeName(returnType)).Append(optional).Append('\n');
        }

        builder.Append("function ")
               .Append(moduleName)
               .Append('.')
               .Append(function.LuaName)
               .Append('(')
               .Append(string.Join(", ", names))
               .Append(") end")
               .Append('\n');
        builder.Append('\n');
    }

    /// <summary>
    /// Writes each line of <paramref name="helpText" /> as its own <c>---</c> comment, so a multi-line summary stays valid
    /// LuaLS annotation syntax.
    /// </summary>
    private static void AppendHelp(StringBuilder builder, string helpText)
    {
        foreach (var line in helpText.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n'))
        {
            builder.Append("---").Append(line).Append('\n');
        }
    }

    /// <summary>
    /// Renders a double as a Lua token, mapping the three non-finite values to expressions Lua accepts (it has no numeric
    /// literal for any of them).
    /// </summary>
    private static string DoubleLiteral(double value)
    {
        if (double.IsNaN(value))
        {
            return "0/0";
        }

        if (double.IsPositiveInfinity(value))
        {
            return "math.huge";
        }

        if (double.IsNegativeInfinity(value))
        {
            return "-math.huge";
        }

        return value.ToString(CultureInfo.InvariantCulture);
    }

    /// <summary>Escapes a string constant so it is a single valid Lua string token: backslash, quote and every control character.</summary>
    private static string EscapeLuaString(string text)
    {
        var builder = new StringBuilder(text.Length);

        foreach (var character in text)
        {
            switch (character)
            {
                case '\\':
                    builder.Append("\\\\");

                    break;
                case '"':
                    builder.Append("\\\"");

                    break;
                case '\n':
                    builder.Append("\\n");

                    break;
                case '\r':
                    builder.Append("\\r");

                    break;
                case '\t':
                    builder.Append("\\t");

                    break;
                default:
                    if (char.IsControl(character))
                    {
                        // Lua's \ddd escape greedily consumes up to three following decimal digits, so an
                        // unpadded code (e.g. \7 before a literal "1") would read back as a different escape.
                        // Always emitting three digits keeps every following character its own token.
                        builder.Append('\\').Append(((int)character).ToString("D3", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        builder.Append(character);
                    }

                    break;
            }
        }

        return builder.ToString();
    }

    private static bool IsNullableValueType(Type type)
        => Nullable.GetUnderlyingType(type) is not null;

    private static string LuaLiteral(object? value, Type type)
        => value switch
        {
            null        => "nil",
            string text => "\"" + EscapeLuaString(text) + "\"",
            bool flag   => flag ? "true" : "false",
            _ when type.IsEnum => Convert.ToInt64(value, CultureInfo.InvariantCulture)
                                         .ToString(CultureInfo.InvariantCulture),
            double number       => DoubleLiteral(number),
            float number        => DoubleLiteral(number),
            IFormattable number => number.ToString(null, CultureInfo.InvariantCulture),
            _                   => "nil"
        };

    private static string LuaTypeName(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type) ?? type;

        if (underlying.IsEnum)
        {
            return underlying.Name;
        }

        if (underlying == typeof(int) || underlying == typeof(long))
        {
            return "integer";
        }

        if (underlying == typeof(double) || underlying == typeof(float))
        {
            return "number";
        }

        if (underlying == typeof(bool))
        {
            return "boolean";
        }

        if (underlying == typeof(string))
        {
            return "string";
        }

        if (underlying == typeof(LuaTable))
        {
            return "table";
        }

        return "any";
    }
}
