using System.Globalization;
using System.Reflection;
using System.Text;
using Lua;
using Moongate.Scripting.Data.Luarc;
using Moongate.Scripting.Internal;

namespace Moongate.Scripting.Utils;

/// <summary>Writes the Lua language server files that give editors completion for every bound module, constant and enum.</summary>
internal static class LuaDefinitionsGenerator
{
    private const string DefinitionsFile = "definitions.lua";
    private const string LuarcFile = ".luarc.json";

    /// <summary>Writes <c>definitions.lua</c> and <c>.luarc.json</c> under <paramref name="scriptsDirectory"/>, creating the directory if needed.</summary>
    /// <param name="scriptsDirectory">Directory holding the scripts; the two files are written directly under it.</param>
    /// <param name="modules">Every module bound at startup, in any order.</param>
    /// <param name="enums">Every enum published as a global table, in any order.</param>
    public static void Write(string scriptsDirectory, IReadOnlyList<BoundModule> modules, IReadOnlyList<Type> enums)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(scriptsDirectory);
        Directory.CreateDirectory(scriptsDirectory);
        File.WriteAllText(Path.Combine(scriptsDirectory, DefinitionsFile), Render(modules, enums), new UTF8Encoding(false));

        var globals = modules.Select(module => module.Name)
            .Concat(enums.Select(type => type.Name))
            .Append("wait")
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToList();
        var luarc = new LuarcConfig { Diagnostics = new LuarcDiagnosticsConfig { Globals = globals } };
        File.WriteAllText(Path.Combine(scriptsDirectory, LuarcFile), luarc.ToJson() + Environment.NewLine, new UTF8Encoding(false));
    }

    /// <summary>Renders the LuaLS annotation text for every module, its functions and constants, every enum, and the built-in <c>wait</c>.</summary>
    /// <param name="modules">Every module bound at startup, in any order.</param>
    /// <param name="enums">Every enum published as a global table, in any order.</param>
    /// <returns>The contents of <c>definitions.lua</c>.</returns>
    public static string Render(IReadOnlyList<BoundModule> modules, IReadOnlyList<Type> enums)
    {
        ArgumentNullException.ThrowIfNull(modules);
        ArgumentNullException.ThrowIfNull(enums);
        var builder = new StringBuilder();
        builder.AppendLine("---@meta");
        builder.AppendLine("-- Generated by Moongate at startup. Do not edit: every entry comes from a C# attribute.");
        builder.AppendLine();
        builder.AppendLine("---Suspends the running coroutine and resumes it on the game loop after the given seconds.");
        builder.AppendLine("---@param seconds number");
        builder.AppendLine("---@return number seconds The seconds actually waited.");
        builder.AppendLine("function wait(seconds) end");
        builder.AppendLine();

        foreach (var enumType in enums.OrderBy(type => type.Name, StringComparer.Ordinal))
        {
            builder.Append("---@enum ").AppendLine(enumType.Name);
            builder.Append(enumType.Name).AppendLine(" = {");

            foreach (var name in Enum.GetNames(enumType))
            {
                var value = Convert.ToInt64(Enum.Parse(enumType, name), CultureInfo.InvariantCulture);
                builder.Append("    ").Append(name).Append(" = ").Append(value.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
            }

            builder.AppendLine("}");
            builder.AppendLine();
        }

        foreach (var module in modules.OrderBy(module => module.Name, StringComparer.Ordinal))
        {
            if (module.HelpText is not null)
            {
                builder.Append("---").AppendLine(module.HelpText);
            }

            builder.Append("---@class ").AppendLine(module.Name);

            foreach (var constant in module.Constants.OrderBy(constant => constant.LuaName, StringComparer.Ordinal))
            {
                builder.Append("---@field ").Append(constant.LuaName).Append(' ').AppendLine(LuaTypeName(constant.Type));
            }

            builder.Append(module.Name).AppendLine(" = {}");

            foreach (var constant in module.Constants.OrderBy(constant => constant.LuaName, StringComparer.Ordinal))
            {
                builder.Append(module.Name).Append('.').Append(constant.LuaName).Append(" = ").AppendLine(LuaLiteral(constant.Value, constant.Type));
            }

            builder.AppendLine();

            foreach (var function in module.Functions.OrderBy(function => function.LuaName, StringComparer.Ordinal))
            {
                AppendFunction(builder, module.Name, function);
            }
        }

        return builder.ToString();
    }

    private static void AppendFunction(StringBuilder builder, string moduleName, BoundFunction function)
    {
        if (function.HelpText is not null)
        {
            builder.Append("---").AppendLine(function.HelpText);
        }

        var parameters = function.Method.GetParameters();
        var names = new List<string>();

        foreach (var parameter in parameters)
        {
            var isParams = parameter.GetCustomAttribute<ParamArrayAttribute>() is not null;
            var type = isParams ? parameter.ParameterType.GetElementType()! : parameter.ParameterType;
            var optional = parameter.HasDefaultValue ? "?" : "";
            builder.Append("---@param ").Append(parameter.Name).Append(optional).Append(' ').AppendLine(LuaTypeName(type));
            names.Add(isParams ? "..." : parameter.Name!);
        }

        if (function.Method.ReturnType != typeof(void))
        {
            builder.Append("---@return ").AppendLine(LuaTypeName(function.Method.ReturnType));
        }

        builder.Append("function ").Append(moduleName).Append('.').Append(function.LuaName)
            .Append('(').Append(string.Join(", ", names)).AppendLine(") end");
        builder.AppendLine();
    }

    private static string LuaTypeName(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type) ?? type;

        if (underlying.IsEnum)
        {
            return underlying.Name;
        }

        if (underlying == typeof(int) || underlying == typeof(long))
        {
            return "integer";
        }

        if (underlying == typeof(double) || underlying == typeof(float))
        {
            return "number";
        }

        if (underlying == typeof(bool))
        {
            return "boolean";
        }

        if (underlying == typeof(string))
        {
            return "string";
        }

        if (underlying == typeof(LuaTable))
        {
            return "table";
        }

        if (underlying == typeof(LuaFunction))
        {
            return "function";
        }

        return "any";
    }

    private static string LuaLiteral(object? value, Type type)
    {
        return value switch
        {
            null => "nil",
            string text => "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
            bool flag => flag ? "true" : "false",
            _ when type.IsEnum => Convert.ToInt64(value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture),
            IFormattable number => number.ToString(null, CultureInfo.InvariantCulture),
            _ => "nil"
        };
    }
}
