using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Moongate.Server.PacketHandlers.Generators.Data.Internal;

namespace Moongate.Server.PacketHandlers.Generators;

[Generator]
public sealed class PacketListenerRegistrationGenerator : IIncrementalGenerator
{
    private const string RegisterPacketHandlerAttributeName =
        "Moongate.Server.Attributes.RegisterPacketHandlerAttribute";

    private const string PacketListenerInterfaceName =
        "Moongate.Server.Interfaces.Listener.IPacketListener";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            RegisterPacketHandlerAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntaxContext, _) => CreateModels(syntaxContext)
        );

        var registrationModels = candidates.SelectMany(
            static (models, _) => models ?? []
        );

        var collected = registrationModels
            .Where(static model => model is not null)
            .Collect();

        context.RegisterSourceOutput(
            collected,
            static (productionContext, models) =>
            {
                var registrations = models
                    .Where(static model => model is not null)
                    .Cast<PacketListenerRegistrationModel>()
                    .Distinct()
                    .OrderBy(static model => model.OpCode)
                    .ThenBy(static model => model.ListenerTypeName, StringComparer.Ordinal)
                    .ToArray();

                var source = BuildSource(registrations);
                productionContext.AddSource(
                    "BootstrapPacketHandlerRegistration.Generated.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
            }
        );
    }

    private static string BuildSource(IReadOnlyList<PacketListenerRegistrationModel> registrations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("using DryIoc;");
        sb.AppendLine();
        sb.AppendLine("namespace Moongate.Server.Bootstrap.Internal;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class BootstrapPacketHandlerRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    static partial void RegisterGenerated(Container container)");
        sb.AppendLine("    {");

        foreach (var registration in registrations)
        {
            sb.Append("        RegisterPacketHandler<");
            sb.Append(registration.ListenerTypeName);
            sb.Append(">(container, 0x");
            sb.Append(registration.OpCode.ToString("X2", CultureInfo.InvariantCulture));
            sb.AppendLine(");");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static IReadOnlyList<PacketListenerRegistrationModel>? CreateModels(
        GeneratorAttributeSyntaxContext context
    )
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        if (typeSymbol.IsAbstract)
        {
            return null;
        }

        if (!typeSymbol.AllInterfaces.Any(i => i.ToDisplayString() == PacketListenerInterfaceName))
        {
            return null;
        }

        var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var normalizedTypeName = fullTypeName.StartsWith("global::", StringComparison.Ordinal)
            ? fullTypeName.Substring("global::".Length)
            : fullTypeName;

        var models = new List<PacketListenerRegistrationModel>(context.Attributes.Length);

        foreach (var attribute in context.Attributes)
        {
            if (attribute.ConstructorArguments.Length != 1)
            {
                continue;
            }

            var opCodeValue = attribute.ConstructorArguments[0].Value;

            if (opCodeValue is null)
            {
                continue;
            }

            var opCode = Convert.ToByte(opCodeValue, CultureInfo.InvariantCulture);
            models.Add(new(normalizedTypeName, opCode));
        }

        return models;
    }
}
