using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Moongate.Server.PacketHandlers.Generators.Data.Internal;

namespace Moongate.Server.PacketHandlers.Generators;

[Generator]
public sealed class ScriptModuleRegistrationGenerator : IIncrementalGenerator
{
    private const string ScriptModuleAttributeName = "Moongate.Scripting.Attributes.Scripts.ScriptModuleAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            ScriptModuleAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntaxContext, _) => CreateModel(syntaxContext)
        );

        var collected = candidates
                        .Where(static model => model is not null)
                        .Collect();

        context.RegisterSourceOutput(
            collected,
            static (productionContext, models) =>
            {
                var registrations = models
                                    .Where(static model => model is not null)
                                    .Distinct()
                                    .OrderBy(static model => model.ModuleTypeName, StringComparer.Ordinal)
                                    .ToArray();

                var source = BuildSource(registrations);
                productionContext.AddSource(
                    "BootstrapScriptModuleRegistration.Generated.g.cs",
                    SourceText.From(source, Encoding.UTF8)
                );
            }
        );
    }

    private static string BuildSource(IReadOnlyList<ScriptModuleRegistrationModel> registrations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine("using DryIoc;");
        sb.AppendLine("using Moongate.Scripting.Extensions.Scripts;");
        sb.AppendLine();
        sb.AppendLine("namespace Moongate.Server.Bootstrap.Internal;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class BootstrapScriptModuleRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    static partial void RegisterGenerated(Container container)");
        sb.AppendLine("    {");

        foreach (var registration in registrations)
        {
            sb.Append("        container.RegisterScriptModule<");
            sb.Append(registration.ModuleTypeName);
            sb.AppendLine(">();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static ScriptModuleRegistrationModel? CreateModel(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        if (typeSymbol.IsAbstract || typeSymbol.IsGenericType)
        {
            return null;
        }

        var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var normalizedTypeName = fullTypeName.StartsWith("global::", StringComparison.Ordinal)
                                     ? fullTypeName.Substring("global::".Length)
                                     : fullTypeName;

        return new(normalizedTypeName);
    }
}
