[[mobile]]
id = "base_cursed"
skin_hue = 34872
notoriety = "murderer"

[[mobile]]
id = "lysander_gathenwale"
base_id = "base_cursed"
name = "Lysander Gathenwale"
gender = "male"
race = "human"
strength = "1d10+110"
dexterity = "1d10+70"
intelligence = "1d10+120"
hits = "1d88+277"
mana = "1d39+226"
damage = "1d13+2"
armor = 20
karma = -1000
fame = 5000
loot = ["reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "reagents", "midlevelscrolls", "midlevelscrolls", "lysanders_journals"]
gold = "1d351+349"
[mobile.skills]
evaluating_intelligence = "1d6+94"
magery = "1d6+94"
resisting_spells = "1d11+79"
meditation = "1d11+89"
parrying = "1d9+74"
wrestling = "1d11+79"
tactics = "1d11+89"
[mobile.sounds]
death = 348
[[mobile.equipment]]
items = ["base_studded_tunic", "0x13e2"]
hue = 2415

[[mobile.equipment]]
items = ["base_plate_arms", "0x1417"]
hue = 1433

[[mobile.equipment]]
items = ["base_ring_gloves", "0x13f2"]
hue = 1433

[[mobile.equipment]]
items = ["base_studded_leggings", "0x13e1"]
hue = 2415

[[mobile.equipment]]
items = ["0x0efa_a_spellbook"]

[[mobile.equipment]]
items = ["0x170b_boots", "0x170c"]
hue = 1433

[[mobile.equipment]]
items = ["0x1515_cloak", "0x1530"]
hue = 2415

[[mobile]]
id = "grimmoch_drummel"
base_id = "base_cursed"
name = "Grimmoch Drummel"
gender = "male"
race = "human"
strength = "1d10+110"
dexterity = "1d10+150"
intelligence = "1d10+40"
hits = "1d88+277"
mana = 0
damage = "1d16+6"
armor = 20
karma = -1000
fame = 5000
loot = ["grimmochs_journals"]
gold = "1d351+349"
[mobile.skills]
anatomy = "1d11+89"
resisting_spells = "1d11+59"
parrying = "1d9+74"
swordsmanship = "1d11+59"
tactics = "1d11+89"
wrestling = "1d11+79"
[mobile.sounds]
death = 348
[[mobile.equipment]]
items = ["0x204a_krisna_hair"]

[[mobile.equipment]]
items = ["base_leather_tunic", "0x13d3"]
hue = 2415

[[mobile.equipment]]
items = ["base_leather_gloves", "0x13ce"]
hue = 2415

[[mobile.equipment]]
items = ["base_leather_leggings", "0x13d2"]
hue = 2415

[[mobile.equipment]]
items = ["base_bow", "0x13b2"]

[[mobile.equipment]]
items = ["0x170b_boots", "0x170c"]
hue = 2212

[[mobile.equipment]]
items = ["0x1541_body_sash", "0x1542"]
hue = 2212

[[mobile]]
id = "morg_bergen"
base_id = "base_cursed"
name = "Morg Bergen"
gender = "male"
race = "human"
strength = "1d10+110"
dexterity = "1d10+110"
intelligence = "1d10+50"
hits = "1d88+277"
mana = 0
damage = "1d19+3"
armor = 20
karma = -1000
fame = 5000
gold = "1d351+349"
[mobile.skills]
anatomy = "1d11+89"
resisting_spells = "1d11+79"
parrying = "1d9+54"
swordsmanship = "1d11+89"
tactics = "1d11+89"
wrestling = "1d11+69"
[mobile.sounds]
death = 348
[[mobile.equipment]]
items = ["base_leather_tunic", "0x13d3"]
hue = 2415

[[mobile.equipment]]
items = ["base_leather_gloves", "0x13ce"]
hue = 2415

[[mobile.equipment]]
items = ["base_leather_sleeves", "0x13cd"]
hue = 2415

[[mobile.equipment]]
items = ["base_leather_leggings", "0x13d2"]
hue = 2415

[[mobile.equipment]]
items = ["base_bardiche", "0x0f4e"]
hue = 2415

[[mobile.equipment]]
items = ["0x170b_boots", "0x170c"]
hue = 2212

[[mobile]]
id = "tavara_sewel"
base_id = "base_cursed"
name = "Tavara Sewel"
gender = "female"
race = "human"
strength = "1d10+110"
dexterity = "1d10+110"
intelligence = "1d10+110"
hits = "1d88+277"
mana = 0
stamina = "1d25+125"
damage = "1d16+6"
armor = 14
karma = -1000
fame = 5000
loot = ["tavaras_journals"]
gold = "1d351+349"
[mobile.skills]
anatomy = "1d11+89"
fencing = "1d11+89"
resisting_spells = "1d11+79"
parrying = "1d9+74"
tactics = "1d11+89"
wrestling = "1d11+69"
[mobile.sounds]
death = 337
[[mobile.equipment]]
items = ["base_ring_gloves", "0x13f2"]
hue = 1433

[[mobile.equipment]]
items = ["base_fem_plate"]
hue = 2415

[[mobile.equipment]]
items = ["base_leather_sleeves", "0x13cd"]
hue = 2415

[[mobile.equipment]]
items = ["base_leather_leggings", "0x13d2"]
hue = 2415

[[mobile.equipment]]
items = ["base_kryss", "0x1401"]
hue = 2415

[[mobile.equipment]]
items = ["base_buckler"]
hue = 2415

[[mobile.equipment]]
items = ["0x170b_boots", "0x170c"]
hue = 2212

[[mobile]]
id = "cursed_male"
base_id = "base_cursed"
name = "The Cursed"
gender = "male"
race = "human"
strength = "1d10+110"
dexterity = "1d10+70"
intelligence = "1d10+120"
hits = "1d88+277"
mana = "1d39+226"
damage = "1d13+2"
armor = 20
karma = -2000
fame = 1000
gold = "1d51+49"
[mobile.skills]
evaluating_intelligence = "1d6+94"
magery = "1d6+94"
resisting_spells = "1d11+79"
meditation = "1d11+89"
parrying = "1d9+74"
wrestling = "1d11+79"
tactics = "1d11+89"
[mobile.sounds]
death = 348
[[mobile.equipment]]
items = ["base_ring_sleeves", "0x13ef"]
hue = 1433

[[mobile.equipment]]
items = ["base_ring_gloves", "0x13f2"]
hue = 1433

[[mobile.equipment]]
items = ["0x152e_short_pants", "0x152f"]
hue = 2415

[[mobile.equipment]]
items = ["0x13b6", "0x13b8", "0x13ba", "base_broadsword", "base_cutlass", "0x13ff", "base_hatchet", "base_executioners_axe", "base_axe", "base_double_axe", "base_battle_axe", "0x13fb", "0x0e85_pickaxe", "0x13b0", "base_two_handed_axe", "base_dagger", "base_kryss", "0x13b4", "base_hammer_pick", "base_mace", "base_maul", "0x13e4", "base_war_hammer", "base_war_mace", "0x1405"]

[[mobile]]
id = "cursed_female"
base_id = "base_cursed"
name = "The Cursed"
gender = "female"
race = "human"
strength = "1d10+110"
dexterity = "1d10+70"
intelligence = "1d10+120"
hits = "1d88+277"
mana = "1d39+226"
damage = "1d13+2"
armor = 20
karma = -2000
fame = 1000
gold = "1d51+49"
[mobile.skills]
evaluating_intelligence = "1d6+94"
magery = "1d6+94"
resisting_spells = "1d11+79"
meditation = "1d11+89"
parrying = "1d9+74"
wrestling = "1d11+79"
tactics = "1d11+89"
[mobile.sounds]
death = 337
[[mobile.equipment]]
items = ["0x1517_shirt", "0x1518"]
hue = 2415

[[mobile.equipment]]
items = ["base_ring_sleeves", "0x13ef"]
hue = 1433

[[mobile.equipment]]
items = ["base_ring_gloves", "0x13f2"]
hue = 1433

[[mobile.equipment]]
items = ["0x152e_short_pants", "0x152f"]
hue = 2415

[[mobile.equipment]]
items = ["0x13b6", "0x13b8", "0x13ba", "base_broadsword", "base_cutlass", "0x13ff", "base_hatchet", "base_executioners_axe", "base_axe", "base_double_axe", "base_battle_axe", "0x13fb", "0x0e85_pickaxe", "0x13b0", "base_two_handed_axe", "base_dagger", "base_kryss", "0x13b4", "base_hammer_pick", "base_mace", "base_maul", "0x13e4", "base_war_hammer", "base_war_mace", "0x1405"]

[[mobile]]
id = "cursed"
base_id = "base_cursed"
name = "The Cursed"
gender = "random"
race = "human"
strength = "1d10+110"
dexterity = "1d10+70"
intelligence = "1d10+120"
hits = "1d88+277"
mana = "1d39+226"
damage = "1d13+2"
armor = 20
karma = -2000
fame = 1000
gold = "1d51+49"
[mobile.skills]
evaluating_intelligence = "1d6+94"
magery = "1d6+94"
resisting_spells = "1d11+79"
meditation = "1d11+89"
parrying = "1d9+74"
wrestling = "1d11+79"
tactics = "1d11+89"
[[mobile.equipment]]
items = ["base_ring_sleeves", "0x13ef"]
hue = 1433

[[mobile.equipment]]
items = ["base_ring_gloves", "0x13f2"]
hue = 1433

[[mobile.equipment]]
items = ["0x152e_short_pants", "0x152f"]
hue = 2415

[[mobile.equipment]]
items = ["0x13b6", "0x13b8", "0x13ba", "base_broadsword", "base_cutlass", "0x13ff", "base_hatchet", "base_executioners_axe", "base_axe", "base_double_axe", "base_battle_axe", "0x13fb", "0x0e85_pickaxe", "0x13b0", "base_two_handed_axe", "base_dagger", "base_kryss", "0x13b4", "base_hammer_pick", "base_mace", "base_maul", "0x13e4", "base_war_hammer", "base_war_mace", "0x1405"]

[[mobile.equipment]]
items = ["0x1517_shirt", "0x1518"]
hue = 2415
gender = "female"
