[[mobile]]
id = "base_zealot"
name = "Zealot of Khaldun"
notoriety = "murderer"

[[mobile]]
id = "zealot_knight_male"
base_id = "base_zealot"
title = "the Knight"
gender = "male"
race = "human"
strength = "1d50+350"
dexterity = "1d15+150"
intelligence = "1d25+75"
hits = "1d73+727"
damage = "1d29+5"
armor = 20
karma = -10000
fame = 10000
gold = "1d51+49"
[mobile.skills]
anatomy = 120
resisting_spells = "1d11+89"
parrying = "1d11+89"
swordsmanship = 120
tactics = "1d11+89"
wrestling = "1d11+69"
[mobile.sounds]
death = 348
[[mobile.equipment]]
items = ["base_bone_arms", "0x1453"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_gauntlets", "0x1455"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_helm", "0x1456"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_legs", "0x1457"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_armor", "0x1454"]
hue = 2101

[[mobile.equipment]]
items = ["base_viking_sword", "0x13ba"]
hue = 2101

[[mobile.equipment]]
items = ["0x170b_boots", "0x170c"]

[[mobile]]
id = "zealot_knight_female"
base_id = "base_zealot"
title = "the Knight"
gender = "female"
race = "human"
strength = "1d10+110"
dexterity = "1d10+70"
intelligence = "1d10+120"
hits = "1d88+277"
mana = "1d39+226"
damage = "1d29+5"
armor = 20
karma = -10000
fame = 10000
gold = "1d51+49"
[mobile.skills]
anatomy = 120
resisting_spells = "1d11+89"
parrying = "1d11+89"
swordsmanship = 120
tactics = "1d11+89"
wrestling = "1d11+69"
[mobile.sounds]
death = 337
[[mobile.equipment]]
items = ["base_bone_arms", "0x1453"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_gauntlets", "0x1455"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_helm", "0x1456"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_legs", "0x1457"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_armor", "0x1454"]
hue = 2101

[[mobile.equipment]]
items = ["base_viking_sword", "0x13ba"]
hue = 2101

[[mobile.equipment]]
items = ["0x170b_boots", "0x170c"]

[[mobile]]
id = "zealot_knight"
base_id = "base_zealot"
title = "the Knight"
gender = "random"
race = "human"
strength = "1d50+350"
dexterity = "1d15+150"
intelligence = "1d25+75"
hits = "1d73+727"
damage = "1d29+5"
armor = 20
karma = -10000
fame = 10000
gold = "1d51+49"
[mobile.skills]
anatomy = 120
resisting_spells = "1d11+89"
parrying = "1d11+89"
swordsmanship = 120
tactics = "1d11+89"
wrestling = "1d11+69"
[[mobile.equipment]]
items = ["base_bone_arms", "0x1453"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_gauntlets", "0x1455"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_helm", "0x1456"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_legs", "0x1457"]
hue = 2101

[[mobile.equipment]]
items = ["base_bone_armor", "0x1454"]
hue = 2101

[[mobile.equipment]]
items = ["base_viking_sword", "0x13ba"]
hue = 2101

[[mobile.equipment]]
items = ["0x170b_boots", "0x170c"]

[[mobile]]
id = "zealot_summoner_male"
base_id = "base_zealot"
title = "the Summoner"
gender = "male"
race = "human"
strength = "1d10+110"
dexterity = "1d10+70"
intelligence = "1d10+120"
hits = "1d88+277"
mana = "1d39+226"
damage = "1d13+2"
armor = 20
karma = -2000
fame = 1000
gold = "1d51+49"
[mobile.skills]
evaluating_intelligence = "1d6+94"
magery = "1d6+94"
resisting_spells = "1d11+79"
meditation = "1d11+89"
parrying = "1d9+74"
wrestling = "1d11+79"
tactics = "1d11+89"
[mobile.sounds]
death = 348
[[mobile.equipment]]
items = ["base_ring_sleeves", "0x13ef"]
hue = 1433

[[mobile.equipment]]
items = ["base_ring_gloves", "0x13f2"]
hue = 1433

[[mobile.equipment]]
items = ["0x152e_short_pants", "0x152f"]
hue = 2415

[[mobile.equipment]]
items = ["0x13b6", "0x13b8", "0x13ba", "base_broadsword", "base_cutlass", "0x13ff", "base_hatchet", "base_executioners_axe", "base_axe", "base_double_axe", "base_battle_axe", "0x13fb", "0x0e85_pickaxe", "0x13b0", "base_two_handed_axe", "base_dagger", "base_kryss", "0x13b4", "base_hammer_pick", "base_mace", "base_maul", "0x13e4", "base_war_hammer", "base_war_mace", "0x1405"]

[[mobile]]
id = "zealot_summoner_female"
base_id = "base_zealot"
title = "the Summoner"
gender = "female"
race = "human"
strength = "1d10+110"
dexterity = "1d10+70"
intelligence = "1d10+120"
hits = "1d88+277"
mana = "1d39+226"
damage = "1d13+2"
armor = 20
karma = -2000
fame = 1000
gold = "1d51+49"
[mobile.skills]
evaluating_intelligence = "1d6+94"
magery = "1d6+94"
resisting_spells = "1d11+79"
meditation = "1d11+89"
parrying = "1d9+74"
wrestling = "1d11+79"
tactics = "1d11+89"
[mobile.sounds]
death = 337
[[mobile.equipment]]
items = ["0x1517_shirt", "0x1518"]
hue = 2415

[[mobile.equipment]]
items = ["base_ring_sleeves", "0x13ef"]
hue = 1433

[[mobile.equipment]]
items = ["base_ring_gloves", "0x13f2"]
hue = 1433

[[mobile.equipment]]
items = ["0x152e_short_pants", "0x152f"]
hue = 2415

[[mobile.equipment]]
items = ["0x13b6", "0x13b8", "0x13ba", "base_broadsword", "base_cutlass", "0x13ff", "base_hatchet", "base_executioners_axe", "base_axe", "base_double_axe", "base_battle_axe", "0x13fb", "0x0e85_pickaxe", "0x13b0", "base_two_handed_axe", "base_dagger", "base_kryss", "0x13b4", "base_hammer_pick", "base_mace", "base_maul", "0x13e4", "base_war_hammer", "base_war_mace", "0x1405"]

[[mobile]]
id = "zealot_summoner"
base_id = "base_zealot"
title = "the Summoner"
gender = "random"
race = "human"
strength = "1d10+110"
dexterity = "1d10+70"
intelligence = "1d10+120"
hits = "1d88+277"
mana = "1d39+226"
damage = "1d13+2"
armor = 20
karma = -2000
fame = 1000
gold = "1d51+49"
[mobile.skills]
evaluating_intelligence = "1d6+94"
magery = "1d6+94"
resisting_spells = "1d11+79"
meditation = "1d11+89"
parrying = "1d9+74"
wrestling = "1d11+79"
tactics = "1d11+89"
[[mobile.equipment]]
items = ["base_ring_sleeves", "0x13ef"]
hue = 1433

[[mobile.equipment]]
items = ["base_ring_gloves", "0x13f2"]
hue = 1433

[[mobile.equipment]]
items = ["0x152e_short_pants", "0x152f"]
hue = 2415

[[mobile.equipment]]
items = ["0x13b6", "0x13b8", "0x13ba", "base_broadsword", "base_cutlass", "0x13ff", "base_hatchet", "base_executioners_axe", "base_axe", "base_double_axe", "base_battle_axe", "0x13fb", "0x0e85_pickaxe", "0x13b0", "base_two_handed_axe", "base_dagger", "base_kryss", "0x13b4", "base_hammer_pick", "base_mace", "base_maul", "0x13e4", "base_war_hammer", "base_war_mace", "0x1405"]

[[mobile.equipment]]
items = ["0x1517_shirt", "0x1518"]
hue = 2415
gender = "female"
