<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishSelfContained>true</PublishSelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishDocumentationFile>false</PublishDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="dbup-postgresql" Version="7.0.1" />
    <ProjectReference Include="../Moongate.Persistence.Migrations/Moongate.Persistence.Migrations.csproj" />
    <ProjectReference Include="../Moongate.Core/Moongate.Core.csproj" />
    <InternalsVisibleTo Include="Moongate.MigrationRunner.Tests" />
  </ItemGroup>
</Project>
