-- ==============================================================================
-- Moongate - scripts/mobiles/monster.lua
--
-- What it is for:
--   A mobile script for the monsters that go for everyone, as ModernUO's melee
--   AI: it chases a player, or a townsman with a blue name, and, beside it, fights
--   it (combat.attack: the server swings, hits and kills by its combat rules). The
--   town guards go for it in turn. A mobile template uses it with
--   script_id = "monster": the creatures whose UOX3 NPCAI is evil, evil caster or
--   chaotic (the casters fight in melee until there is magic) do, and so do those
--   based on them. The behaviour is the shared
--   scripts/common/creature.lua with hunts = true.
--
--   The monster is in one of three states (and turns on whoever hits it, as ModernUO's
--   creatures do: the one it fights is the one it chases, whatever it was doing):
--     wander  it strolls around its home, the area of its spawn region, mostly
--             straight ahead, and now and then rests for 15 to 25 seconds with
--             its idle sound and a fidget.
--     chase   it saw a player within 16 tiles, in line of sight: it threatens it
--             with its attack sound, goes into war mode and walks to it, around
--             what stands in the way, never running. Beside the player it faces
--             it and fights it until the player dies, goes or hides.
--     guard   it lost the player: hidden, gone, farther than 32 tiles or out of
--             reach for 20 seconds. It stops fighting, stands in war mode for 10
--             seconds, looking around, then goes back to wandering, and so to its home. A
--             player it could not reach is left alone until it moves.
--   It never sees a hidden player, a game master or an administrator, and it
--   ignores the other monsters.
--
-- Functions:
--   on_think(serial)                 every think of an NPC near a player
--                                    (ultima.npcs.think_interval_ms, 500 ms);
--                                    must not call wait()
--
-- What it keeps:
--   Its state is kept in memory by serial, not saved: after a restart, or once no
--   player is near, a monster starts again from wandering.
-- ==============================================================================

local creature = require("common.creature")

monster = creature.new({ hunts = true })
