[[item]]
id = "0x0b34_table"
base_id = "base_item"
item_id = 2868
name = "table"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x0b35_table"
base_id = "base_item"
item_id = 2869
name = "table"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x0b36_table"
base_id = "base_item"
item_id = 2870
name = "table"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x0b3a_table"
base_id = "base_item"
item_id = 2874
name = "table"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x0b3c_table"
base_id = "base_item"
item_id = 2876
name = "table"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x0b3f_counter"
base_id = "base_item"
item_id = 2879
name = "counter"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0b40_counter"
base_id = "base_item"
item_id = 2880
name = "counter"
rarity = "common"
movable = false
hue = 0
