namespace Moongate.Server.Abstractions.Interfaces.Gumps;

/// <summary>
/// Draws a gump, one layout command per call.
/// <para>
/// The method names and parameter orders are RunUO's, which ModernUO and ServUO also carry, because
/// that is the API every visual gump editor exports against — code generated by one of them
/// translates to these calls line by line. The Lua surface drops the <c>Add</c> prefix and takes a
/// named table instead of positional arguments; this interface is the C# face, for services and
/// plugins.
/// </para>
/// </summary>
public interface IGumpBuilder
{
    /// <summary>Starts a page. Buttons with a page target switch between pages client-side.</summary>
    void AddPage(int page);

    /// <summary>A resizable background frame — the <c>resizepic</c> command.</summary>
    void AddBackground(int x, int y, int width, int height, int gumpId);

    /// <summary>A line of text — the <c>text</c> command. The text itself goes to the strings block.</summary>
    void AddLabel(int x, int y, int hue, string text);

    /// <summary>
    /// A button — the <c>button</c> command. <paramref name="type" /> is 0 for a page switch and 1
    /// for a reply that closes the gump; <paramref name="param" /> is the target page for the former.
    /// Only a reply button's id can come back in a response.
    /// </summary>
    void AddButton(int x, int y, int normalId, int pressedId, int buttonId, int type, int param);

    /// <summary>A checkbox — the <c>checkbox</c> command. Its switch id appears in the response when ticked.</summary>
    void AddCheck(int x, int y, int inactiveId, int activeId, bool initialState, int switchId);

    /// <summary>A text field — the <c>textentry</c> command. Its contents come back keyed by <paramref name="entryId" />.</summary>
    void AddTextEntry(int x, int y, int width, int height, int hue, int entryId, string initialText);

    /// <summary>Opens a radio group, so that only one radio inside it can be selected.</summary>
    void AddGroup(int group);

    /// <summary>A translucent panel — the <c>checkertrans</c> command.</summary>
    void AddAlphaRegion(int x, int y, int width, int height);

    /// <summary>A radio button — the <c>radio</c> command. Its switch id appears in the response when selected.</summary>
    void AddRadio(int x, int y, int inactiveId, int activeId, bool initialState, int switchId);

    /// <summary>Text clipped to a box — the <c>croppedtext</c> command.</summary>
    void AddLabelCropped(int x, int y, int width, int height, int hue, string text);

    /// <summary>An HTML region — the <c>htmlgump</c> command.</summary>
    void AddHtml(int x, int y, int width, int height, string text, bool background, bool scrollbar);

    /// <summary>
    /// A label drawn through the HTML renderer. Colour, size and centring are markup wrapped around
    /// the text rather than parameters, because the underlying command is <c>htmlgump</c>.
    /// </summary>
    void AddLabelHtml(int x, int y, int width, int height, string text, string hue, int size, bool center);

    /// <summary>
    /// A localized HTML region. The command chosen depends on what is supplied: <c>xmfhtmlgump</c>
    /// with neither, <c>xmfhtmlgumpcolor</c> with a colour, <c>xmfhtmltok</c> with arguments.
    /// </summary>
    void AddHtmlLocalized(
        int x,
        int y,
        int width,
        int height,
        int number,
        string? args,
        int? color,
        bool background,
        bool scrollbar
    );

    /// <summary>A gump picture — the <c>gumppic</c> command; the hue is appended only when non-zero.</summary>
    void AddImage(int x, int y, int gumpId, int hue);

    /// <summary>A gump picture tiled across a box — the <c>gumppictiled</c> command.</summary>
    void AddImageTiled(int x, int y, int width, int height, int gumpId);

    /// <summary>A button drawn from item art — the <c>buttontileart</c> command.</summary>
    void AddImageTiledButton(
        int x,
        int y,
        int normalId,
        int pressedId,
        int buttonId,
        int type,
        int param,
        int itemId,
        int hue,
        int width,
        int height
    );

    /// <summary>An item's art — <c>tilepic</c>, or <c>tilepichue</c> when hued.</summary>
    void AddItem(int x, int y, int itemId, int hue);

    /// <summary>A cropped region of a gump image — the <c>picinpic</c> command.</summary>
    void AddSpriteImage(int x, int y, int gumpId, int width, int height, int sx, int sy);

    /// <summary>A cliloc tooltip — the <c>tooltip</c> command, with arguments only when supplied.</summary>
    void AddTooltip(int number, string? args);

    /// <summary>Binds the client's item tooltip to a serial — the <c>itemproperty</c> command.</summary>
    void AddItemProperty(uint serial);

    /// <summary>Overrides the gump art the client frames this gump with — the <c>mastergump</c> command.</summary>
    void AddGumpIdOverride(int gumpId);
}
