namespace Moongate.Server.Abstractions.Interfaces.Gumps;

/// <summary>
/// Draws a gump, one layout command per call.
/// <para>
/// The method names and parameter orders are RunUO's, which ModernUO and ServUO also carry, because
/// that is the API every visual gump editor exports against — code generated by one of them
/// translates to these calls line by line. The Lua surface drops the <c>Add</c> prefix and takes a
/// named table instead of positional arguments; this interface is the C# face, for services and
/// plugins.
/// </para>
/// </summary>
public interface IGumpBuilder
{
    /// <summary>Starts a page. Buttons with a page target switch between pages client-side.</summary>
    void AddPage(int page);

    /// <summary>A resizable background frame — the <c>resizepic</c> command.</summary>
    void AddBackground(int x, int y, int width, int height, int gumpId);

    /// <summary>A line of text — the <c>text</c> command. The text itself goes to the strings block.</summary>
    void AddLabel(int x, int y, int hue, string text);

    /// <summary>
    /// A button — the <c>button</c> command. <paramref name="type" /> is 0 for a page switch and 1
    /// for a reply that closes the gump; <paramref name="param" /> is the target page for the former.
    /// Only a reply button's id can come back in a response.
    /// </summary>
    void AddButton(int x, int y, int normalId, int pressedId, int buttonId, int type, int param);

    /// <summary>A checkbox — the <c>checkbox</c> command. Its switch id appears in the response when ticked.</summary>
    void AddCheck(int x, int y, int inactiveId, int activeId, bool initialState, int switchId);

    /// <summary>A text field — the <c>textentry</c> command. Its contents come back keyed by <paramref name="entryId" />.</summary>
    void AddTextEntry(int x, int y, int width, int height, int hue, int entryId, string initialText);
}
