/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists every account on the shard.
         * @description Passwords are never returned, by any account route.
         */
        get: operations["ListAccounts"];
        put?: never;
        /**
         * Creates an account.
         * @description Username and password are required, and the username must be free — a taken one answers 409. Level
         *     is optional and defaults to Player; when sent it must name an account level, case-insensitively.
         *     A 503 means the game loop did not respond and the account was not created.
         */
        post: operations["CreateAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetches a single account by username.
         * @description Answers 404 when no account carries that username.
         */
        get: operations["GetAccount"];
        put?: never;
        post?: never;
        /**
         * Deletes an account, along with its characters and everything they carry.
         * @description Permanent, and the only account route that changes the world rather than just the account record.
         *     An account whose character is currently being played cannot be deleted: the request answers 409
         *     until that character logs out. A 503 means the game loop did not respond and nothing was deleted.
         */
        delete: operations["DeleteAccount"];
        options?: never;
        head?: never;
        /**
         * Updates an account, changing only the fields that are sent.
         * @description Every field is optional; an omitted one is left as it is. Answers 404 for an unknown account, and
         *     400 when the level does not name one. Returns the account as it stands after the update. A 503
         *     means the game loop did not respond and the account was not updated.
         */
        patch: operations["UpdateAccount"];
        trace?: never;
    };
    "/api/v1/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports the shard's name, build and how many sessions are connected.
         * @description A snapshot taken when the request is served, not a live figure.
         */
        get: operations["GetAdminStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists the plugins this shard activated, each with the HTTP routes it declares.
         * @description Routes belonging to no plugin — the API reference and framework middleware — are gathered under a
         *     final synthetic entry with id `moongate.host`, so that everything the shard serves appears
         *     somewhere. `policy` names the authorization policy guarding a route, and is null when the
         *     route is open.
         */
        get: operations["GetAdminPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trades account credentials for a bearer token.
         * @description The token carries the account's username and level, and every other route reads authorisation from
         *     it. Send it as `Authorization: Bearer <token>`. Any failure answers 401 without saying
         *     which part was wrong.
         */
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchanges a still-valid token for a fresh one, so an active session does not expire mid-use.
         * @description Send the current token as `Authorization: Bearer <token>`; the reply has the same shape as
         *     `/api/v1/auth/login`. The new token keeps the `auth_time` of the one presented, so renewing
         *     never restarts the session: past `http.Jwt.MaxSessionHours` from the original login the answer is
         *     401 and the user must sign in again. A 401 also means the account has been deactivated.
         */
        post: operations["RenewToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every player character on the shard, paged.
         * @description Ordered by character name. Pass search to filter: it is free text, case-insensitive, and matches
         *     either the character's name or the owning account's username, so "find me so-and-so's character" is
         *     one query. Page is 1-based and defaults to 1; pageSize defaults to 25 and cannot exceed 100. NPCs
         *     are not characters and never appear. A search matching nothing is an empty page, not an error.
         */
        get: operations["ListCharacters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/console/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Opens a per-connection SSE feed; its first event carries the connection id to POST with.
         * @description Emits `ready` (data = the connection id), then a `line` per command reply and a
         *                 `done` when a command finishes. The connection is closed when the client disconnects.
         */
        get: operations["StreamConsole"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/console": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Runs a console command; its reply lines stream to the given connection's SSE feed.
         * @description Returns 202 immediately — the command is dispatched onto the game loop and its output
         *                 arrives asynchronously on `GET /api/v1/admin/console/stream`.
         */
        post: operations["SendConsoleCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/items/{id}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Item art as a PNG, optionally hued.
         * @description Open without a token: the art is client data every player already has on disk. The id is hex, with
         *     or without the 0x prefix — 0x1234.png and 1234.png are the same item. Pass hue for a coloured
         *     variant; 0, or omitting it, gives the raw art, and the range is 0 to 3000. Images are decoded on
         *     first request and cached, so the first call for an item is slower than every call after it.
         */
        get: operations["GetItemImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The facets this shard serves, and the shape of each one's tile grid.
         * @description Open without a token. Read this before requesting tiles: the facets' sizes come from the shard's own
         *     client files, so maxZoom and the grid differ between shards and must not be hardcoded.
         */
        get: operations["ListMaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/maps/{map}/full.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A whole facet as one PNG.
         * @description Open without a token. The entire facet at one pixel per map tile — 6144×4096 for Felucca — for
         *     downloading or printing rather than browsing; use the tiles for a viewer. Optional `?style=`
         *     picks `flat` (default) or `relief` as on the tile route. It is generated once and
         *     cached, and the first request is slow and memory-hungry if the staff pre-warm has not run.
         */
        get: operations["GetFullMapImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/maps/{map}/{z}/{x}/{y}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One map tile.
         * @description Open without a token: map data is client data every player already has on disk. The facet is named,
         *     case-insensitively — felucca, trammel, ilshenar, malas, tokuno, termur. Zoom counts up to detail: 0
         *     is the whole facet in one tile, and maxZoom — which GET /api/v1/images/maps reports per facet — is
         *     one pixel per map tile. Tiles are 256×256. A tile at the facet's edge is padded transparent. Tiles
         *     are rendered on first request and cached, so the first call at a low zoom builds everything beneath
         *     it and is slow; the staff pre-warm exists to do that in advance. Optional `?style=` chooses the
         *     render: `flat` (default) is the radar map, `relief` adds altitude shading; each caches on
         *     its own.
         */
        get: operations["GetMapTile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports how far the map image export has got.
         * @description State is Idle before any export has run, then Running, and finally Completed or Failed. Failed counts
         *     images that could not be produced; the reasons are in the server log.
         */
        get: operations["GetMapImageExportStatus"];
        put?: never;
        /**
         * Builds every map tile and whole-facet image into the cache.
         * @description Answers 202 and works in the background; poll this same route with GET for progress. Only one runs
         *     at a time, so a second request while one is going answers 409. Worth running before anyone opens a
         *     viewer: the first request at a low zoom otherwise builds every tile beneath it, and the first
         *     request for a whole facet renders a facet-sized image. Progress is kept in memory and does not
         *     survive a restart.
         */
        post: operations["StartMapImageExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports how far the item image export has got.
         * @description State is Idle before any export has run, then Running, and finally Completed or Failed. Failed
         *     counts items whose art could not be written; the reasons are in the server log.
         */
        get: operations["GetItemImageExportStatus"];
        put?: never;
        /**
         * Generates every item's art into the cache.
         * @description Answers 202 and works in the background; poll this same route with GET for progress. Only one
         *     export runs at a time, so a second request while one is going answers 409. Unhued art only — hued
         *     variants are generated on demand by the public image route. Progress is kept in memory and does
         *     not survive a restart.
         */
        post: operations["StartItemImageExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/items/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every item template, paged.
         * @description Ordered by template id. Pass search to filter: free text, case-insensitive, matching the
         *     template's id, name, category or any tag. Page is 1-based and defaults to 1; pageSize defaults
         *     to 25 and cannot exceed 100. A search matching nothing is an empty page, not an error.
         */
        get: operations["ListItemTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/items/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetches one item template by id, specs included.
         * @description Ids are case-insensitive. Answers 404 when no template carries the id.
         */
        get: operations["GetItemTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/bodies/{body}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serves a body's idle, front-facing frame as PNG.
         * @description The body is a decimal graphic id; pass hue for a skin-hued variant. Generated lazily and cached
         *     on disk. A body with no usable animation answers 404. Anonymous on purpose: it is client data
         *     every player already has on disk.
         */
        get: operations["GetBodyImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/hair/{style}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serves a hair (or facial-hair) style as PNG, rendered over a reference body.
         * @description The style is the hair item's decimal graphic id (see /api/v1/admin/hair-styles). Pass hue to dye
         *     it, body to change the reference body (default 400, the human male), facial=true for beards.
         *     404 when nothing decodes for the pair.
         */
        get: operations["GetHairImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/mobiles/templates/{id}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serves a mobile template's dressed figure as PNG: body, hair and worn equipment.
         * @description Hue specs on the template resolve to their low end so the image is stable and cacheable. 404 on
         *     an unknown template id, or when the template's body has no animation.
         */
        get: operations["GetMobileTemplateImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bodies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every classified body, paged, for the picker.
         * @description Classification comes from mobtypes.txt; Equipment-type bodies never appear. Search matches the
         *     decimal id or the 0x-prefixed hex. Ordered by body id.
         */
        get: operations["ListBodies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/hair-styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The selectable hair (or facial-hair) styles, paged.
         * @description Pass facial=true for beards. Search matches the style name, case-insensitively.
         */
        get: operations["ListHairStyles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/mobiles/templates/{id}/paperdoll.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serves the template's classic client paperdoll as PNG: background, body, hair, equipment.
         * @description Pass background=false to drop the backdrop gump. Hue and gender-random specs on the template
         *     resolve deterministically so the image is stable and cacheable. 404 on an unknown template id or
         *     when its body has no paperdoll gump.
         */
        get: operations["GetMobileTemplatePaperdoll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images/bodies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports how far the body image export has got.
         * @description State is Idle before any export has run, then Running, and finally Completed or Failed.
         */
        get: operations["GetBodyImageExportStatus"];
        put?: never;
        /**
         * Generates every classified body's image into the cache.
         * @description Answers 202 and works in the background; poll this same route with GET for progress. Only one
         *     export runs at a time, so a second request while one is going answers 409. Unhued frames only —
         *     hued variants are generated on demand by the public image route.
         */
        post: operations["StartBodyImageExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists every news entry, drafts included, newest first. */
        get: operations["ListAllNews"];
        put?: never;
        /** Creates a news entry, authored by the calling staff member. */
        post: operations["CreateNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns one news entry in any state. */
        get: operations["GetNewsAdmin"];
        /** Updates a news entry's title, body and published state. */
        put: operations["UpdateNews"];
        post?: never;
        /** Deletes a news entry. */
        delete: operations["DeleteNews"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists published news, newest first. */
        get: operations["ListNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns one published news entry; 404 if it is missing or a draft. */
        get: operations["GetNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports the account the bearer token belongs to.
         * @description Username and level, read straight from the token — useful for confirming a token is still valid
         *     and what it grants. It does not list the account's characters.
         */
        get: operations["GetPlayerMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player/me/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own characters.
         * @description Reports every character on the account the bearer token belongs to, with its stats, appearance and
         *     where it stands. Never another account's. The owner field is null here: the caller is the owner. An
         *     account with no characters gets an empty list, not an error.
         */
        get: operations["GetMyCharacters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/players/online": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists players who have entered the world with map-ready positions.
         * @description Staff only. The response is an unpaged snapshot ordered by character name and serial. Login and
         *     character-selection sessions are excluded. The snapshot is read directly while the game loop may
         *     move or disconnect a player, so one response can be briefly stale or internally inconsistent.
         */
        get: operations["ListOnlinePlayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registers a new account when web registration is open.
         * @description Answers 403 when registration is disabled, 429 when the caller is rate-limited, 409 for a taken
         *     username, 400 for a missing or malformed field, and 202 on success — the account is created
         *     inactive and must verify its email before it can log in.
         */
        post: operations["RegisterAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/register/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verifies an account's email with its token, activating the account.
         * @description Answers 400 for an unknown or already-used token.
         */
        post: operations["VerifyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the shard's public profile: name, description, contacts, asset URLs and whether registration is open. */
        get: operations["GetServerInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server-info/assets/{slot}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Streams a visual asset (logo, favicon or banner) by slot.
         * @description Answers 400 for an unknown slot and 404 when the slot has no asset.
         */
        get: operations["GetServerAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/server-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the full server settings. */
        get: operations["GetServerSettings"];
        /** Updates the server settings; every field is optional and an omitted one is left unchanged. */
        put: operations["UpdateServerSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/server-settings/assets/{slot}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Uploads the image for a slot (logo, favicon or banner), replacing any previous one.
         * @description Answers 400 for an unknown slot, 415 for a non-image type, and 413 when the file is too large.
         */
        post: operations["UploadServerAsset"];
        /** Removes the image for a slot. */
        delete: operations["DeleteServerAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports the shard's public statistics: players online, accounts, world size and loaded content.
         * @description The figures come from a snapshot recomputed on the game loop every `StatsRefreshSeconds`;
         *     `generatedAt` says when it was taken, and equals `0001-01-01T00:00:00+00:00` until the
         *     first one has been computed. The response caches for the same interval.
         */
        get: operations["GetServerStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports the shard's name and build.
         * @description Open without a token, so a launcher or the website can check compatibility before anyone logs in.
         */
        get: operations["GetVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description An account as the API reports it. Deliberately not `AccountEntity`, which carries PasswordHash
         *     and ActivationToken: returning the entity would publish both to every caller, log and proxy cache on
         *     the way. Naming the fields here means a field added to the entity later cannot leak by default.
         */
        AccountResponse: {
            username: string;
            email?: string | null;
            level: string;
            isActive: boolean;
            /** Format: int32 */
            characterCount: number;
        };
        /** @description A staff-level snapshot of the shard. No uptime: there is no "shard started at" to read. */
        AdminStatusResponse: {
            shardName: string;
            version: string;
            /** Format: int32 */
            onlineSessions: number;
        };
        /** @description An issued API token and the moment it stops being valid. */
        ApiTokenResult: {
            token: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description How far the bulk body-image export has got. */
        BodyImageExportStatus: {
            /** @description Idle, Running, Completed or Failed. */
            state: string;
            /**
             * Format: int32
             * @description Bodies processed so far.
             */
            done: number;
            /**
             * Format: int32
             * @description Classified, non-equipment bodies to process. 0 until the export has counted them.
             */
            total: number;
            /**
             * Format: int32
             * @description Bodies whose frame could not be rendered or written. The reasons are in the log.
             */
            failed: number;
            /**
             * Format: date-time
             * @description When the current or last export started; null if none ever has.
             */
            startedAt?: string | null;
        };
        /** @description One row of the staff body picker. */
        BodySummary: {
            /** Format: int32 */
            body: number;
            hex: string;
            type: string;
            imageUrl: string;
        };
        /** @description One page of results, and what a caller needs to walk the rest. */
        BodySummaryPagedResponse: {
            /** @description The results on this page. */
            items: components["schemas"]["BodySummary"][];
            /**
             * Format: int32
             * @description How many results matched in total, before paging.
             */
            total: number;
            /**
             * Format: int32
             * @description The 1-based page this is.
             */
            page: number;
            /**
             * Format: int32
             * @description The page size used. The last page may hold fewer items.
             */
            pageSize: number;
            /**
             * Format: int32
             * @description How many pages exist at this page size. 0 when nothing matched.
             */
            totalPages: number;
        };
        BookSpec: {
            bookId: string;
        };
        /**
         * @description A character as the API reports it. Deliberately not `MobileEntity`, which carries BrainScriptId,
         *     LootTableId and BackpackId: returning the entity would publish the shard's internals to every caller,
         *     and a field added to the entity later would publish itself. Naming the fields here means that cannot
         *     happen by default — the same reason Moongate.Http.Plugin.Data.Api.Accounts.AccountResponse exists rather than returning
         *     AccountEntity with its PasswordHash.
         */
        CharacterResponse: {
            /** @description The character's serial, as `0x40000001`. */
            serial: string;
            name: string;
            /** @description The owning account. Null on the player's own route, where it is the caller. */
            accountUsername?: string | null;
            race: string;
            gender: string;
            /** Format: int32 */
            body: number;
            /** Format: int32 */
            strength: number;
            /** Format: int32 */
            dexterity: number;
            /** Format: int32 */
            intelligence: number;
            /** Format: int32 */
            hits: number;
            /** Format: int32 */
            hitsMax: number;
            /** Format: int32 */
            stamina: number;
            /** Format: int32 */
            staminaMax: number;
            /** Format: int32 */
            mana: number;
            /** Format: int32 */
            manaMax: number;
            /** Format: int32 */
            kills: number;
            /** Format: int32 */
            skinHue: number;
            /** Format: int32 */
            hairStyle: number;
            /** Format: int32 */
            hairHue: number;
            /** Format: int32 */
            mapId: number;
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
            /** Format: int32 */
            z: number;
        };
        /** @description One page of results, and what a caller needs to walk the rest. */
        CharacterResponsePagedResponse: {
            /** @description The results on this page. */
            items: components["schemas"]["CharacterResponse"][];
            /**
             * Format: int32
             * @description How many results matched in total, before paging.
             */
            total: number;
            /**
             * Format: int32
             * @description The 1-based page this is.
             */
            page: number;
            /**
             * Format: int32
             * @description The page size used. The last page may hold fewer items.
             */
            pageSize: number;
            /**
             * Format: int32
             * @description How many pages exist at this page size. 0 when nothing matched.
             */
            totalPages: number;
        };
        /** @description A console command to run and the SSE connection its output should stream to. */
        ConsoleCommandRequest: {
            command: string;
            connectionId: string;
        };
        ContainerSpec: {
            /** Format: int32 */
            weightMax?: number | null;
            /** Format: int32 */
            maxItems?: number | null;
            /** Format: int32 */
            gumpId?: number | null;
            containerLayoutId?: string | null;
            contents?: string[] | null;
            isQuiver?: boolean | null;
            /** Format: int32 */
            weightReduction?: number | null;
            /** Format: int32 */
            quiverDamageIncrease?: number | null;
            /** Format: int32 */
            lowerAmmoCost?: number | null;
            /** Format: int32 */
            defenseChanceIncrease?: number | null;
        };
        /**
         * @description A new account. `Level` is the `AccountLevelType` name; omitted means Player, the safe
         *     default — an account that gains staff rights by accident is the wrong way to fail.
         */
        CreateAccountRequest: {
            username: string;
            password: string;
            email?: string | null;
            level?: string | null;
        };
        /** @description Body for creating a news entry; the author is taken from the caller's token. */
        CreateNewsRequest: {
            title: string;
            body: string;
            isPublished: boolean;
        };
        EquipSpec: {
            layer: components["schemas"]["LayerType"];
            /** Format: int32 */
            hitPoints?: number | null;
            /** Format: int32 */
            strengthReq?: number | null;
            /** Format: int32 */
            dexterityReq?: number | null;
            /** Format: int32 */
            intelligenceReq?: number | null;
        };
        /** @description One row of the staff hair-style picker. */
        HairStyleSummary: {
            /** Format: int32 */
            style: number;
            hex: string;
            name: string;
            facial: boolean;
            imageUrl: string;
        };
        /** @description One page of results, and what a caller needs to walk the rest. */
        HairStyleSummaryPagedResponse: {
            /** @description The results on this page. */
            items: components["schemas"]["HairStyleSummary"][];
            /**
             * Format: int32
             * @description How many results matched in total, before paging.
             */
            total: number;
            /**
             * Format: int32
             * @description The 1-based page this is.
             */
            page: number;
            /**
             * Format: int32
             * @description The page size used. The last page may hold fewer items.
             */
            pageSize: number;
            /**
             * Format: int32
             * @description How many pages exist at this page size. 0 when nothing matched.
             */
            totalPages: number;
        };
        /** @description How far the bulk item-image export has got. */
        ItemImageExportStatus: {
            /** @description Idle, Running, Completed or Failed. */
            state: string;
            /**
             * Format: int32
             * @description Items exported so far.
             */
            done: number;
            /**
             * Format: int32
             * @description Items with art to export. 0 until the export has counted them.
             */
            total: number;
            /**
             * Format: int32
             * @description Items whose art could not be written. The reasons are in the log.
             */
            failed: number;
            /**
             * Format: date-time
             * @description When the current or last export started; null if none ever has.
             */
            startedAt?: string | null;
        };
        ItemParam: {
            type: string;
            value: string;
        };
        /**
         * @description The full template: everything the summary carries plus the typed specs, passed through as the
         *     Moongate.UO.Data types — they are the documented data contract of the YAML templates.
         */
        ItemTemplateResponse: {
            id: string;
            name: string;
            category: string;
            description: string;
            /** Format: int32 */
            itemId: number;
            /** Format: int32 */
            hue: number;
            rarity: string;
            /** Format: int32 */
            goldValue: number;
            /** Format: double */
            weight: number;
            scriptId: string;
            isMovable: boolean;
            stackable?: boolean | null;
            dyeable?: boolean | null;
            visibility?: string | null;
            lootType?: string | null;
            tags: string[];
            flippableItemIds?: number[] | null;
            lootTables?: string[] | null;
            params?: {
                [key: string]: components["schemas"]["ItemParam"];
            } | null;
            equip?: components["schemas"]["EquipSpec"];
            weapon?: components["schemas"]["WeaponSpec"];
            container?: components["schemas"]["ContainerSpec"];
            book?: components["schemas"]["BookSpec"];
            imageUrl: string;
        };
        /** @description One row of the staff item template listing. */
        ItemTemplateSummaryResponse: {
            id: string;
            name: string;
            category: string;
            /** Format: int32 */
            itemId: number;
            /** Format: int32 */
            hue: number;
            rarity: string;
            /** Format: int32 */
            goldValue: number;
            /** Format: double */
            weight: number;
            tags: string[];
            imageUrl: string;
        };
        /** @description One page of results, and what a caller needs to walk the rest. */
        ItemTemplateSummaryResponsePagedResponse: {
            /** @description The results on this page. */
            items: components["schemas"]["ItemTemplateSummaryResponse"][];
            /**
             * Format: int32
             * @description How many results matched in total, before paging.
             */
            total: number;
            /**
             * Format: int32
             * @description The 1-based page this is.
             */
            page: number;
            /**
             * Format: int32
             * @description The page size used. The last page may hold fewer items.
             */
            pageSize: number;
            /**
             * Format: int32
             * @description How many pages exist at this page size. 0 when nothing matched.
             */
            totalPages: number;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        LayerType: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29;
        /** @description Credentials posted to the login endpoint. */
        LoginRequest: {
            username: string;
            password: string;
        };
        /** @description A map facet as the API describes it, so a viewer can configure itself rather than guess. */
        MapFacetInfo: {
            /** @description The facet's name, as used in the tile route. */
            name: string;
            /**
             * Format: int32
             * @description Facet width in map tiles, which is its width in pixels at native zoom.
             */
            width: number;
            /**
             * Format: int32
             * @description Facet height in map tiles.
             */
            height: number;
            /**
             * Format: int32
             * @description The deepest zoom, where one pixel is one map tile. Zoom 0 is always one tile.
             */
            maxZoom: number;
            /**
             * Format: int32
             * @description Tile edge in pixels.
             */
            tileSize: number;
            /**
             * Format: int32
             * @description Tiles across the grid at MaxZoom.
             */
            tilesAcross: number;
            /**
             * Format: int32
             * @description Tiles down the grid at MaxZoom.
             */
            tilesDown: number;
        };
        /** @description How far the map image pre-warm has got. */
        MapImageExportStatus: {
            /** @description Idle, Running, Completed or Failed. */
            state: string;
            /**
             * Format: int32
             * @description Tiles and whole-facet images produced so far.
             */
            done: number;
            /**
             * Format: int32
             * @description How many there are to produce. 0 until the pre-warm has counted them.
             */
            total: number;
            /**
             * Format: int32
             * @description How many could not be produced. The reasons are in the log.
             */
            failed: number;
            /**
             * Format: date-time
             * @description When the current or last pre-warm started; null if none ever has.
             */
            startedAt?: string | null;
        };
        /** @description A news entry as returned by the API. */
        NewsResponse: {
            /** Format: int32 */
            id: number;
            title: string;
            body: string;
            author: string;
            /** Format: date-time */
            publishedAt: string;
            /** Format: date-time */
            updatedAt: string;
            isPublished: boolean;
        };
        /** @description A map-ready snapshot of one player currently in the world. */
        OnlinePlayerMapResponse: {
            /** @description Stable character serial, formatted as hexadecimal. */
            characterSerial: string;
            /** @description Character display name. */
            characterName: string;
            /** @description Owning account serial, formatted as hexadecimal. */
            accountSerial: string;
            /** @description Owning account username. */
            accountUsername: string;
            /**
             * Format: int32
             * @description Numeric UO facet id.
             */
            mapId: number;
            /** @description Known facet name, or Unknown for an unrecognised id. */
            mapName: string;
            /**
             * Format: int32
             * @description World X coordinate.
             */
            x: number;
            /**
             * Format: int32
             * @description World Y coordinate.
             */
            y: number;
            /**
             * Format: int32
             * @description World altitude.
             */
            z: number;
            /** @description Facing direction without the running flag. */
            direction: string;
            /** @description Whether the latest direction carries the running flag. */
            running: boolean;
            /**
             * Format: int32
             * @description Body graphic id.
             */
            body: number;
            /**
             * Format: int32
             * @description Skin hue id.
             */
            skinHue: number;
            /**
             * Format: int32
             * @description Current hit points.
             */
            hits: number;
            /**
             * Format: int32
             * @description Maximum hit points.
             */
            hitsMax: number;
            /** @description Whether the character is in war mode. */
            warmode: boolean;
        };
        /** @description Who the caller's token says they are. Deliberately not their characters — see PlayerEndpoints. */
        PlayerMeResponse: {
            username: string;
            level: string;
        };
        /**
         * @description One activated plugin and everything it exposes over HTTP. `version` goes over the wire as a
         *     string, e.g. `"0.1.0"`.
         */
        PluginInfoResponse: {
            id: string;
            name: string;
            version: string;
            author: string;
            description: string;
            assembly: string;
            isExternal: boolean;
            routes: components["schemas"]["PluginRouteResponse"][];
        };
        /** @description One HTTP route a plugin declares. `policy` is null when the route is open. */
        PluginRouteResponse: {
            method: string;
            path: string;
            policy?: string | null;
        };
        /** @description A web self-registration request. */
        RegisterRequest: {
            username: string;
            password: string;
            email: string;
        };
        /** @description The shard's public contact points. */
        ServerContactsResponse: {
            website?: string | null;
            email?: string | null;
            discord?: string | null;
        };
        /** @description The public server profile a website or launcher reads: identity, contacts, assets, and whether registration is open. */
        ServerInfoResponse: {
            shardName: string;
            description?: string | null;
            tagline?: string | null;
            contacts: components["schemas"]["ServerContactsResponse"];
            registrationEnabled: boolean;
            assets: {
                [key: string]: string;
            };
        };
        /** @description The full settings view returned to staff (identical fields to the public info minus the shard name). */
        ServerSettingsResponse: {
            description?: string | null;
            tagline?: string | null;
            contacts: components["schemas"]["ServerContactsResponse"];
            registrationEnabled: boolean;
            assets: {
                [key: string]: string;
            };
        };
        /** @description The shard's public statistics, as a website or launcher reads them. */
        ServerStatsResponse: {
            /** Format: date-time */
            generatedAt: string;
            /** Format: int64 */
            uptimeSeconds: number;
            players: components["schemas"]["StatsPlayersResponse"];
            accounts: components["schemas"]["StatsAccountsResponse"];
            world: components["schemas"]["StatsWorldResponse"];
            content: components["schemas"]["StatsContentResponse"];
        };
        /** @description The shard's user base: accounts registered, accounts verified, and characters created. */
        StatsAccountsResponse: {
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            active: number;
            /** Format: int32 */
            characters: number;
        };
        /** @description How much content the shard has loaded: the templates available to spawn from. */
        StatsContentResponse: {
            /** Format: int32 */
            itemTemplates: number;
            /** Format: int32 */
            mobileTemplates: number;
        };
        /** @description Who is connected: players in the world, and every open connection including the login screen. */
        StatsPlayersResponse: {
            /** Format: int32 */
            online: number;
            /** Format: int32 */
            connections: number;
        };
        /** @description How much the world holds: creatures nobody plays, and persisted items. */
        StatsWorldResponse: {
            /** Format: int32 */
            npcs: number;
            /** Format: int32 */
            items: number;
        };
        /**
         * @description The fields to change. Every one is optional: absent means "leave alone", which is what makes this a
         *     PATCH rather than a PUT. Password is write-only — it enters here and never appears in a response.
         *     Email is not here: the account service has no setter for it.
         */
        UpdateAccountRequest: {
            level?: string | null;
            isActive?: boolean | null;
            password?: string | null;
        };
        /** @description Body for updating a news entry. */
        UpdateNewsRequest: {
            title: string;
            body: string;
            isPublished: boolean;
        };
        /** @description A partial settings update: an omitted (null) field is left unchanged. */
        UpdateServerSettingsRequest: {
            description?: string | null;
            tagline?: string | null;
            contacts?: components["schemas"]["ServerContactsResponse"];
            registrationEnabled?: boolean | null;
        };
        /** @description Carries the single-use token that verifies an account's email. */
        VerifyEmailRequest: {
            token: string;
        };
        /** @description What the shard calls itself and which build it runs. */
        VersionResponse: {
            shardName: string;
            version: string;
        };
        WeaponSpec: {
            /** Format: int32 */
            lowDamage: number;
            /** Format: int32 */
            highDamage: number;
            /** Format: int32 */
            speed: number;
            /** Format: int32 */
            baseRange: number;
            /** Format: int32 */
            maxRange: number;
            /** Format: int32 */
            hitSound: number;
            /** Format: int32 */
            missSound: number;
            weaponSkill?: string | null;
            /** Format: int32 */
            ammo?: number | null;
            /** Format: int32 */
            ammoFx?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"][];
                };
            };
        };
    };
    CreateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    GetAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    DeleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    GetAdminStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatusResponse"];
                };
            };
        };
    };
    GetAdminPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginInfoResponse"][];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenResult"];
                };
            };
        };
    };
    RenewToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenResult"];
                };
            };
        };
    };
    ListCharacters: {
        parameters: {
            query?: {
                page?: string;
                pageSize?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponsePagedResponse"];
                };
            };
        };
    };
    StreamConsole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    SendConsoleCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsoleCommandRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetItemImage: {
        parameters: {
            query?: {
                hue?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
        };
    };
    ListMaps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapFacetInfo"][];
                };
            };
        };
    };
    GetFullMapImage: {
        parameters: {
            query?: {
                style?: string;
            };
            header?: never;
            path: {
                map: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
        };
    };
    GetMapTile: {
        parameters: {
            query?: {
                style?: string;
            };
            header?: never;
            path: {
                map: string;
                z: string;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
        };
    };
    GetMapImageExportStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapImageExportStatus"];
                };
            };
        };
    };
    StartMapImageExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapImageExportStatus"];
                };
            };
        };
    };
    GetItemImageExportStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemImageExportStatus"];
                };
            };
        };
    };
    StartItemImageExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemImageExportStatus"];
                };
            };
        };
    };
    ListItemTemplates: {
        parameters: {
            query?: {
                page?: string;
                pageSize?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemTemplateSummaryResponsePagedResponse"];
                };
            };
        };
    };
    GetItemTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemTemplateResponse"];
                };
            };
        };
    };
    GetBodyImage: {
        parameters: {
            query?: {
                hue?: number;
            };
            header?: never;
            path: {
                body: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
        };
    };
    GetHairImage: {
        parameters: {
            query?: {
                hue?: number;
                body?: number;
                facial?: boolean;
            };
            header?: never;
            path: {
                style: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
        };
    };
    GetMobileTemplateImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
        };
    };
    ListBodies: {
        parameters: {
            query?: {
                page?: string;
                pageSize?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodySummaryPagedResponse"];
                };
            };
        };
    };
    ListHairStyles: {
        parameters: {
            query?: {
                page?: string;
                pageSize?: string;
                search?: string;
                facial?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HairStyleSummaryPagedResponse"];
                };
            };
        };
    };
    GetMobileTemplatePaperdoll: {
        parameters: {
            query?: {
                background?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
        };
    };
    GetBodyImageExportStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyImageExportStatus"];
                };
            };
        };
    };
    StartBodyImageExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyImageExportStatus"];
                };
            };
        };
    };
    ListAllNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"][];
                };
            };
        };
    };
    CreateNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNewsRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
        };
    };
    GetNewsAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
        };
    };
    UpdateNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNewsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
        };
    };
    DeleteNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"][];
                };
            };
        };
    };
    GetNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
        };
    };
    GetPlayerMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerMeResponse"];
                };
            };
        };
    };
    GetMyCharacters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"][];
                };
            };
        };
    };
    ListOnlinePlayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlinePlayerMapResponse"][];
                };
            };
        };
    };
    RegisterAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VerifyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetServerInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerInfoResponse"];
                };
            };
        };
    };
    GetServerAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    GetServerSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerSettingsResponse"];
                };
            };
        };
    };
    UpdateServerSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServerSettingsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerSettingsResponse"];
                };
            };
        };
    };
    UploadServerAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerSettingsResponse"];
                };
            };
        };
    };
    DeleteServerAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetServerStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatsResponse"];
                };
            };
        };
    };
    GetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
