/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists every account on the shard.
         * @description Passwords are never returned, by any account route.
         */
        get: operations["ListAccounts"];
        put?: never;
        /**
         * Creates an account.
         * @description Username and password are required, and the username must be free — a taken one answers 409. Level
         *     is optional and defaults to Player; when sent it must name an account level, case-insensitively.
         */
        post: operations["CreateAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetches a single account by username.
         * @description Answers 404 when no account carries that username.
         */
        get: operations["GetAccount"];
        put?: never;
        post?: never;
        /**
         * Deletes an account, along with its characters and everything they carry.
         * @description Permanent, and the only account route that changes the world rather than just the account record.
         *     An account whose character is currently being played cannot be deleted: the request answers 409
         *     until that character logs out. A 503 means the game loop did not respond and nothing was deleted.
         */
        delete: operations["DeleteAccount"];
        options?: never;
        head?: never;
        /**
         * Updates an account, changing only the fields that are sent.
         * @description Every field is optional; an omitted one is left as it is. Answers 404 for an unknown account, and
         *     400 when the level does not name one. Returns the account as it stands after the update.
         */
        patch: operations["UpdateAccount"];
        trace?: never;
    };
    "/api/v1/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports the shard's name, build and how many sessions are connected.
         * @description A snapshot taken when the request is served, not a live figure.
         */
        get: operations["GetAdminStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists the plugins this shard activated, each with the HTTP routes it declares.
         * @description Routes belonging to no plugin — the API reference and framework middleware — are gathered under a
         *     final synthetic entry with id `moongate.host`, so that everything the shard serves appears
         *     somewhere. `policy` names the authorization policy guarding a route, and is null when the
         *     route is open.
         */
        get: operations["GetAdminPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trades account credentials for a bearer token.
         * @description The token carries the account's username and level, and every other route reads authorisation from
         *     it. Send it as `Authorization: Bearer <token>`. Any failure answers 401 without saying
         *     which part was wrong.
         */
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchanges a still-valid token for a fresh one, so an active session does not expire mid-use.
         * @description Send the current token as `Authorization: Bearer <token>`; the reply has the same shape as
         *     `/api/v1/auth/login`. The new token keeps the `auth_time` of the one presented, so renewing
         *     never restarts the session: past `http.Jwt.MaxSessionHours` from the original login the answer is
         *     401 and the user must sign in again. A 401 also means the account has been deactivated.
         */
        post: operations["RenewToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every player character on the shard, paged.
         * @description Ordered by character name. Pass search to filter: it is free text, case-insensitive, and matches
         *     either the character's name or the owning account's username, so "find me so-and-so's character" is
         *     one query. Page is 1-based and defaults to 1; pageSize defaults to 25 and cannot exceed 100. NPCs
         *     are not characters and never appear. A search matching nothing is an empty page, not an error.
         */
        get: operations["ListCharacters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/console/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Opens a per-connection SSE feed; its first event carries the connection id to POST with.
         * @description Emits `ready` (data = the connection id), then a `line` per command reply and a
         *                 `done` when a command finishes. The connection is closed when the client disconnects.
         */
        get: operations["StreamConsole"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/console": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Runs a console command; its reply lines stream to the given connection's SSE feed.
         * @description Returns 202 immediately — the command is dispatched onto the game loop and its output
         *                 arrives asynchronously on `GET /api/v1/admin/console/stream`.
         */
        post: operations["SendConsoleCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/items/{id}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Item art as a PNG, optionally hued.
         * @description Open without a token: the art is client data every player already has on disk. The id is hex, with
         *     or without the 0x prefix — 0x1234.png and 1234.png are the same item. Pass hue for a coloured
         *     variant; 0, or omitting it, gives the raw art, and the range is 0 to 3000. Images are decoded on
         *     first request and cached, so the first call for an item is slower than every call after it.
         */
        get: operations["GetItemImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The facets this shard serves, and the shape of each one's tile grid.
         * @description Open without a token. Read this before requesting tiles: the facets' sizes come from the shard's own
         *     client files, so maxZoom and the grid differ between shards and must not be hardcoded.
         */
        get: operations["ListMaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/maps/{map}/full.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A whole facet as one PNG.
         * @description Open without a token. The entire facet at one pixel per map tile — 6144×4096 for Felucca — for
         *     downloading or printing rather than browsing; use the tiles for a viewer. Optional `?style=`
         *     picks `flat` (default) or `relief` as on the tile route. It is generated once and
         *     cached, and the first request is slow and memory-hungry if the staff pre-warm has not run.
         */
        get: operations["GetFullMapImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/maps/{map}/{z}/{x}/{y}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One map tile.
         * @description Open without a token: map data is client data every player already has on disk. The facet is named,
         *     case-insensitively — felucca, trammel, ilshenar, malas, tokuno, termur. Zoom counts up to detail: 0
         *     is the whole facet in one tile, and maxZoom — which GET /api/v1/images/maps reports per facet — is
         *     one pixel per map tile. Tiles are 256×256. A tile at the facet's edge is padded transparent. Tiles
         *     are rendered on first request and cached, so the first call at a low zoom builds everything beneath
         *     it and is slow; the staff pre-warm exists to do that in advance. Optional `?style=` chooses the
         *     render: `flat` (default) is the radar map, `relief` adds altitude shading; each caches on
         *     its own.
         */
        get: operations["GetMapTile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports how far the map image export has got.
         * @description State is Idle before any export has run, then Running, and finally Completed or Failed. Failed counts
         *     images that could not be produced; the reasons are in the server log.
         */
        get: operations["GetMapImageExportStatus"];
        put?: never;
        /**
         * Builds every map tile and whole-facet image into the cache.
         * @description Answers 202 and works in the background; poll this same route with GET for progress. Only one runs
         *     at a time, so a second request while one is going answers 409. Worth running before anyone opens a
         *     viewer: the first request at a low zoom otherwise builds every tile beneath it, and the first
         *     request for a whole facet renders a facet-sized image. Progress is kept in memory and does not
         *     survive a restart.
         */
        post: operations["StartMapImageExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports how far the item image export has got.
         * @description State is Idle before any export has run, then Running, and finally Completed or Failed. Failed
         *     counts items whose art could not be written; the reasons are in the server log.
         */
        get: operations["GetItemImageExportStatus"];
        put?: never;
        /**
         * Generates every item's art into the cache.
         * @description Answers 202 and works in the background; poll this same route with GET for progress. Only one
         *     export runs at a time, so a second request while one is going answers 409. Unhued art only — hued
         *     variants are generated on demand by the public image route. Progress is kept in memory and does
         *     not survive a restart.
         */
        post: operations["StartItemImageExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/items/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every item template, paged.
         * @description Ordered by template id. Pass search to filter: free text, case-insensitive, matching the
         *     template's id, name, category or any tag. Page is 1-based and defaults to 1; pageSize defaults
         *     to 25 and cannot exceed 100. A search matching nothing is an empty page, not an error.
         */
        get: operations["ListItemTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/items/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetches one item template by id, specs included.
         * @description Ids are case-insensitive. Answers 404 when no template carries the id.
         */
        get: operations["GetItemTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/bodies/{body}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serves a body's idle, front-facing frame as PNG.
         * @description The body is a decimal graphic id; pass hue for a skin-hued variant. Generated lazily and cached
         *     on disk. A body with no usable animation answers 404. Anonymous on purpose: it is client data
         *     every player already has on disk.
         */
        get: operations["GetBodyImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/hair/{style}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serves a hair (or facial-hair) style as PNG, rendered over a reference body.
         * @description The style is the hair item's decimal graphic id (see /api/v1/admin/hair-styles). Pass hue to dye
         *     it, body to change the reference body (default 400, the human male), facial=true for beards.
         *     404 when nothing decodes for the pair.
         */
        get: operations["GetHairImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/mobiles/templates/{id}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serves a mobile template's dressed figure as PNG: body, hair and worn equipment.
         * @description Hue specs on the template resolve to their low end so the image is stable and cacheable. 404 on
         *     an unknown template id, or when the template's body has no animation.
         */
        get: operations["GetMobileTemplateImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bodies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every classified body, paged, for the picker.
         * @description Classification comes from mobtypes.txt; Equipment-type bodies never appear. Search matches the
         *     decimal id or the 0x-prefixed hex. Ordered by body id.
         */
        get: operations["ListBodies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/hair-styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The selectable hair (or facial-hair) styles, paged.
         * @description Pass facial=true for beards. Search matches the style name, case-insensitively.
         */
        get: operations["ListHairStyles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/mobiles/templates/{id}/paperdoll.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serves the template's classic client paperdoll as PNG: background, body, hair, equipment.
         * @description Pass background=false to drop the backdrop gump. Hue and gender-random specs on the template
         *     resolve deterministically so the image is stable and cacheable. 404 on an unknown template id or
         *     when its body has no paperdoll gump.
         */
        get: operations["GetMobileTemplatePaperdoll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/images/bodies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports how far the body image export has got.
         * @description State is Idle before any export has run, then Running, and finally Completed or Failed.
         */
        get: operations["GetBodyImageExportStatus"];
        put?: never;
        /**
         * Generates every classified body's image into the cache.
         * @description Answers 202 and works in the background; poll this same route with GET for progress. Only one
         *     export runs at a time, so a second request while one is going answers 409. Unhued frames only —
         *     hued variants are generated on demand by the public image route.
         */
        post: operations["StartBodyImageExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists every news entry, drafts included, newest first. */
        get: operations["ListAllNews"];
        put?: never;
        /** Creates a news entry, authored by the calling staff member. */
        post: operations["CreateNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns one news entry in any state. */
        get: operations["GetNewsAdmin"];
        /** Updates a news entry's title, body and published state. */
        put: operations["UpdateNews"];
        post?: never;
        /** Deletes a news entry. */
        delete: operations["DeleteNews"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists published news, newest first. */
        get: operations["ListNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns one published news entry; 404 if it is missing or a draft. */
        get: operations["GetNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports the account the bearer token belongs to.
         * @description Username and level, read straight from the token — useful for confirming a token is still valid
         *     and what it grants. It does not list the account's characters.
         */
        get: operations["GetPlayerMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/player/me/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own characters.
         * @description Reports every character on the account the bearer token belongs to, with its stats, appearance and
         *     where it stands. Never another account's. The owner field is null here: the caller is the owner. An
         *     account with no characters gets an empty list, not an error.
         */
        get: operations["GetMyCharacters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registers a new account when web registration is open.
         * @description Answers 403 when registration is disabled, 429 when the caller is rate-limited, 409 for a taken
         *     username, 400 for a missing or malformed field, and 202 on success — the account is created
         *     inactive and must verify its email before it can log in.
         */
        post: operations["RegisterAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/register/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verifies an account's email with its token, activating the account.
         * @description Answers 400 for an unknown or already-used token.
         */
        post: operations["VerifyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the shard's public profile: name, description, contacts, asset URLs and whether registration is open. */
        get: operations["GetServerInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server-info/assets/{slot}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Streams a visual asset (logo, favicon or banner) by slot.
         * @description Answers 400 for an unknown slot and 404 when the slot has no asset.
         */
        get: operations["GetServerAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/server-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the full server settings. */
        get: operations["GetServerSettings"];
        /** Updates the server settings; every field is optional and an omitted one is left unchanged. */
        put: operations["UpdateServerSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/server-settings/assets/{slot}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Uploads the image for a slot (logo, favicon or banner), replacing any previous one.
         * @description Answers 400 for an unknown slot, 415 for a non-image type, and 413 when the file is too large.
         */
        post: operations["UploadServerAsset"];
        /** Removes the image for a slot. */
        delete: operations["DeleteServerAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports the shard's public statistics: players online, accounts, world size and loaded content.
         * @description The figures come from a snapshot recomputed on the game loop every `StatsRefreshSeconds`;
         *     `generatedAt` says when it was taken, and equals `0001-01-01T00:00:00+00:00` until the
         *     first one has been computed. The response caches for the same interval.
         */
        get: operations["GetServerStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports the shard's name and build.
         * @description Open without a token, so a launcher or the website can check compatibility before anyone logs in.
         */
        get: operations["GetVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Assembly: {
            readonly definedTypes?: components["schemas"]["TypeInfo"][] | null;
            readonly exportedTypes?: components["schemas"]["Type"][] | null;
            /** @deprecated */
            readonly codeBase?: string | null;
            entryPoint?: components["schemas"]["MethodInfo"];
            readonly fullName?: string | null;
            readonly imageRuntimeVersion?: string | null;
            readonly isDynamic?: boolean;
            readonly location?: string | null;
            readonly reflectionOnly?: boolean;
            readonly isCollectible?: boolean;
            readonly isFullyTrusted?: boolean;
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            /** @deprecated */
            readonly escapedCodeBase?: string | null;
            manifestModule?: components["schemas"]["Module"];
            readonly modules?: components["schemas"]["Module"][] | null;
            /** @deprecated */
            readonly globalAssemblyCache?: boolean;
            /** Format: int64 */
            readonly hostContext?: number;
            securityRuleSet?: components["schemas"]["SecurityRuleSet"];
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        CallingConventions: 1 | 2 | 3 | 32 | 64;
        /** @description A console command to run and the SSE connection its output should stream to. */
        ConsoleCommandRequest: {
            command?: string | null;
            connectionId?: string | null;
        };
        ConstructorInfo: {
            readonly name?: string | null;
            declaringType?: components["schemas"]["Type"];
            reflectedType?: components["schemas"]["Type"];
            module?: components["schemas"]["Module"];
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            readonly isCollectible?: boolean;
            /** Format: int32 */
            readonly metadataToken?: number;
            attributes?: components["schemas"]["MethodAttributes"];
            methodImplementationFlags?: components["schemas"]["MethodImplAttributes"];
            callingConvention?: components["schemas"]["CallingConventions"];
            readonly isAbstract?: boolean;
            readonly isConstructor?: boolean;
            readonly isFinal?: boolean;
            readonly isHideBySig?: boolean;
            readonly isSpecialName?: boolean;
            readonly isStatic?: boolean;
            readonly isVirtual?: boolean;
            readonly isAssembly?: boolean;
            readonly isFamily?: boolean;
            readonly isFamilyAndAssembly?: boolean;
            readonly isFamilyOrAssembly?: boolean;
            readonly isPrivate?: boolean;
            readonly isPublic?: boolean;
            readonly isConstructedGenericMethod?: boolean;
            readonly isGenericMethod?: boolean;
            readonly isGenericMethodDefinition?: boolean;
            readonly containsGenericParameters?: boolean;
            methodHandle?: components["schemas"]["RuntimeMethodHandle"];
            readonly isSecurityCritical?: boolean;
            readonly isSecuritySafeCritical?: boolean;
            readonly isSecurityTransparent?: boolean;
            memberType?: components["schemas"]["MemberTypes"];
        };
        /**
         * @description A new account. `Level` is the `AccountLevelType` name; omitted means Player, the safe
         *     default — an account that gains staff rights by accident is the wrong way to fail.
         */
        CreateAccountRequest: {
            username?: string | null;
            password?: string | null;
            email?: string | null;
            level?: string | null;
        };
        /** @description Body for creating a news entry; the author is taken from the caller's token. */
        CreateNewsRequest: {
            title?: string | null;
            body?: string | null;
            isPublished?: boolean;
        };
        CustomAttributeData: {
            attributeType?: components["schemas"]["Type"];
            constructor?: {
                readonly name?: string | null;
                declaringType?: components["schemas"]["Type"];
                reflectedType?: components["schemas"]["Type"];
                module?: components["schemas"]["Module"];
                readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
                readonly isCollectible?: boolean;
                /** Format: int32 */
                readonly metadataToken?: number;
                attributes?: components["schemas"]["MethodAttributes"];
                methodImplementationFlags?: components["schemas"]["MethodImplAttributes"];
                callingConvention?: components["schemas"]["CallingConventions"];
                readonly isAbstract?: boolean;
                readonly isConstructor?: boolean;
                readonly isFinal?: boolean;
                readonly isHideBySig?: boolean;
                readonly isSpecialName?: boolean;
                readonly isStatic?: boolean;
                readonly isVirtual?: boolean;
                readonly isAssembly?: boolean;
                readonly isFamily?: boolean;
                readonly isFamilyAndAssembly?: boolean;
                readonly isFamilyOrAssembly?: boolean;
                readonly isPrivate?: boolean;
                readonly isPublic?: boolean;
                readonly isConstructedGenericMethod?: boolean;
                readonly isGenericMethod?: boolean;
                readonly isGenericMethodDefinition?: boolean;
                readonly containsGenericParameters?: boolean;
                methodHandle?: components["schemas"]["RuntimeMethodHandle"];
                readonly isSecurityCritical?: boolean;
                readonly isSecuritySafeCritical?: boolean;
                readonly isSecurityTransparent?: boolean;
                memberType?: components["schemas"]["MemberTypes"];
            };
            readonly constructorArguments?: components["schemas"]["CustomAttributeTypedArgument"][] | null;
            readonly namedArguments?: components["schemas"]["CustomAttributeNamedArgument"][] | null;
        };
        CustomAttributeNamedArgument: {
            memberInfo?: components["schemas"]["MemberInfo"];
            typedValue?: components["schemas"]["CustomAttributeTypedArgument"];
            readonly memberName?: string | null;
            readonly isField?: boolean;
        };
        CustomAttributeTypedArgument: {
            argumentType?: components["schemas"]["Type"];
            value?: unknown;
        };
        Endpoint: {
            displayName?: string | null;
            metadata?: unknown[] | null;
            requestDelegate?: components["schemas"]["RequestDelegate"];
        };
        EndpointDataSource: {
            readonly endpoints?: components["schemas"]["Endpoint"][] | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        EventAttributes: 0 | 512 | 1024;
        EventInfo: {
            readonly name?: string | null;
            declaringType?: components["schemas"]["Type"];
            reflectedType?: components["schemas"]["Type"];
            module?: components["schemas"]["Module"];
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            readonly isCollectible?: boolean;
            /** Format: int32 */
            readonly metadataToken?: number;
            memberType?: components["schemas"]["MemberTypes"];
            attributes?: components["schemas"]["EventAttributes"];
            readonly isSpecialName?: boolean;
            addMethod?: components["schemas"]["MethodInfo"];
            removeMethod?: components["schemas"]["MethodInfo"];
            raiseMethod?: components["schemas"]["MethodInfo"];
            readonly isMulticast?: boolean;
            eventHandlerType?: components["schemas"]["Type"];
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        FieldAttributes: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 16 | 32 | 64 | 128 | 256 | 512 | 1024 | 4096 | 8192 | 32768 | 38144;
        FieldInfo: {
            readonly name?: string | null;
            declaringType?: components["schemas"]["Type"];
            reflectedType?: components["schemas"]["Type"];
            module?: components["schemas"]["Module"];
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            readonly isCollectible?: boolean;
            /** Format: int32 */
            readonly metadataToken?: number;
            memberType?: components["schemas"]["MemberTypes"];
            attributes?: components["schemas"]["FieldAttributes"];
            fieldType?: components["schemas"]["Type"];
            readonly isInitOnly?: boolean;
            readonly isLiteral?: boolean;
            /** @deprecated */
            readonly isNotSerialized?: boolean;
            readonly isPinvokeImpl?: boolean;
            readonly isSpecialName?: boolean;
            readonly isStatic?: boolean;
            readonly isAssembly?: boolean;
            readonly isFamily?: boolean;
            readonly isFamilyAndAssembly?: boolean;
            readonly isFamilyOrAssembly?: boolean;
            readonly isPrivate?: boolean;
            readonly isPublic?: boolean;
            readonly isSecurityCritical?: boolean;
            readonly isSecuritySafeCritical?: boolean;
            readonly isSecurityTransparent?: boolean;
            fieldHandle?: components["schemas"]["RuntimeFieldHandle"];
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        GenericParameterAttributes: 0 | 1 | 2 | 3 | 4 | 8 | 16 | 28 | 32;
        ICustomAttributeProvider: Record<string, never>;
        IntPtr: Record<string, never>;
        /**
         * Format: int32
         * @enum {integer}
         */
        LayoutKind: 0 | 2 | 3;
        /** @description Credentials posted to the login endpoint. */
        LoginRequest: {
            username?: string | null;
            password?: string | null;
        };
        MemberInfo: {
            memberType?: components["schemas"]["MemberTypes"];
            readonly name?: string | null;
            declaringType?: components["schemas"]["Type"];
            reflectedType?: components["schemas"]["Type"];
            module?: components["schemas"]["Module"];
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            readonly isCollectible?: boolean;
            /** Format: int32 */
            readonly metadataToken?: number;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        MemberTypes: 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 191;
        /**
         * Format: int32
         * @enum {integer}
         */
        MethodAttributes: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 16 | 32 | 64 | 128 | 256 | 512 | 1024 | 2048 | 4096 | 8192 | 16384 | 32768 | 53248;
        MethodBase: {
            memberType?: components["schemas"]["MemberTypes"];
            readonly name?: string | null;
            declaringType?: components["schemas"]["Type"];
            reflectedType?: components["schemas"]["Type"];
            module?: components["schemas"]["Module"];
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            readonly isCollectible?: boolean;
            /** Format: int32 */
            readonly metadataToken?: number;
            attributes?: components["schemas"]["MethodAttributes"];
            methodImplementationFlags?: components["schemas"]["MethodImplAttributes"];
            callingConvention?: components["schemas"]["CallingConventions"];
            readonly isAbstract?: boolean;
            readonly isConstructor?: boolean;
            readonly isFinal?: boolean;
            readonly isHideBySig?: boolean;
            readonly isSpecialName?: boolean;
            readonly isStatic?: boolean;
            readonly isVirtual?: boolean;
            readonly isAssembly?: boolean;
            readonly isFamily?: boolean;
            readonly isFamilyAndAssembly?: boolean;
            readonly isFamilyOrAssembly?: boolean;
            readonly isPrivate?: boolean;
            readonly isPublic?: boolean;
            readonly isConstructedGenericMethod?: boolean;
            readonly isGenericMethod?: boolean;
            readonly isGenericMethodDefinition?: boolean;
            readonly containsGenericParameters?: boolean;
            methodHandle?: components["schemas"]["RuntimeMethodHandle"];
            readonly isSecurityCritical?: boolean;
            readonly isSecuritySafeCritical?: boolean;
            readonly isSecurityTransparent?: boolean;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        MethodImplAttributes: 0 | 1 | 2 | 3 | 4 | 8 | 16 | 32 | 64 | 128 | 256 | 512 | 4096 | 8192 | 65535;
        MethodInfo: {
            readonly name?: string | null;
            declaringType?: components["schemas"]["Type"];
            reflectedType?: components["schemas"]["Type"];
            module?: components["schemas"]["Module"];
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            readonly isCollectible?: boolean;
            /** Format: int32 */
            readonly metadataToken?: number;
            attributes?: components["schemas"]["MethodAttributes"];
            methodImplementationFlags?: components["schemas"]["MethodImplAttributes"];
            callingConvention?: components["schemas"]["CallingConventions"];
            readonly isAbstract?: boolean;
            readonly isConstructor?: boolean;
            readonly isFinal?: boolean;
            readonly isHideBySig?: boolean;
            readonly isSpecialName?: boolean;
            readonly isStatic?: boolean;
            readonly isVirtual?: boolean;
            readonly isAssembly?: boolean;
            readonly isFamily?: boolean;
            readonly isFamilyAndAssembly?: boolean;
            readonly isFamilyOrAssembly?: boolean;
            readonly isPrivate?: boolean;
            readonly isPublic?: boolean;
            readonly isConstructedGenericMethod?: boolean;
            readonly isGenericMethod?: boolean;
            readonly isGenericMethodDefinition?: boolean;
            readonly containsGenericParameters?: boolean;
            methodHandle?: components["schemas"]["RuntimeMethodHandle"];
            readonly isSecurityCritical?: boolean;
            readonly isSecuritySafeCritical?: boolean;
            readonly isSecurityTransparent?: boolean;
            memberType?: components["schemas"]["MemberTypes"];
            returnParameter?: components["schemas"]["ParameterInfo"];
            returnType?: components["schemas"]["Type"];
            returnTypeCustomAttributes?: components["schemas"]["ICustomAttributeProvider"];
        };
        Module: {
            assembly?: components["schemas"]["Assembly"];
            readonly fullyQualifiedName?: string | null;
            readonly name?: string | null;
            /** Format: int32 */
            readonly mdStreamVersion?: number;
            /** Format: uuid */
            readonly moduleVersionId?: string;
            readonly scopeName?: string | null;
            moduleHandle?: components["schemas"]["ModuleHandle"];
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            /** Format: int32 */
            readonly metadataToken?: number;
        };
        ModuleHandle: {
            /** Format: int32 */
            readonly mdStreamVersion?: number;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ParameterAttributes: 0 | 1 | 2 | 4 | 8 | 16 | 4096 | 8192 | 16384 | 32768 | 61440;
        ParameterInfo: {
            attributes?: components["schemas"]["ParameterAttributes"];
            member?: components["schemas"]["MemberInfo"];
            readonly name?: string | null;
            parameterType?: components["schemas"]["Type"];
            /** Format: int32 */
            readonly position?: number;
            readonly isIn?: boolean;
            readonly isLcid?: boolean;
            readonly isOptional?: boolean;
            readonly isOut?: boolean;
            readonly isRetval?: boolean;
            readonly defaultValue?: unknown;
            readonly rawDefaultValue?: unknown;
            readonly hasDefaultValue?: boolean;
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            /** Format: int32 */
            readonly metadataToken?: number;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        PropertyAttributes: 0 | 512 | 1024 | 4096 | 8192 | 16384 | 32768 | 62464;
        PropertyInfo: {
            readonly name?: string | null;
            declaringType?: components["schemas"]["Type"];
            reflectedType?: components["schemas"]["Type"];
            module?: components["schemas"]["Module"];
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            readonly isCollectible?: boolean;
            /** Format: int32 */
            readonly metadataToken?: number;
            memberType?: components["schemas"]["MemberTypes"];
            propertyType?: components["schemas"]["Type"];
            attributes?: components["schemas"]["PropertyAttributes"];
            readonly isSpecialName?: boolean;
            readonly canRead?: boolean;
            readonly canWrite?: boolean;
            getMethod?: components["schemas"]["MethodInfo"];
            setMethod?: components["schemas"]["MethodInfo"];
        };
        /** @description A web self-registration request. */
        RegisterRequest: {
            username?: string | null;
            password?: string | null;
            email?: string | null;
        };
        RequestDelegate: {
            readonly target?: unknown;
            method?: components["schemas"]["MethodInfo"];
        };
        RuntimeFieldHandle: {
            value?: components["schemas"]["IntPtr"];
        };
        RuntimeMethodHandle: {
            value?: components["schemas"]["IntPtr"];
        };
        RuntimeTypeHandle: {
            value?: components["schemas"]["IntPtr"];
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        SecurityRuleSet: 0 | 1 | 2;
        /** @description The shard's public contact points. */
        ServerContactsResponse: {
            website?: string | null;
            email?: string | null;
            discord?: string | null;
        };
        StructLayoutAttribute: {
            readonly typeId?: unknown;
            value?: components["schemas"]["LayoutKind"];
        };
        Type: {
            readonly name?: string | null;
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            readonly isCollectible?: boolean;
            /** Format: int32 */
            readonly metadataToken?: number;
            memberType?: components["schemas"]["MemberTypes"];
            readonly namespace?: string | null;
            readonly assemblyQualifiedName?: string | null;
            readonly fullName?: string | null;
            assembly?: components["schemas"]["Assembly"];
            module?: components["schemas"]["Module"];
            readonly isInterface?: boolean;
            readonly isNested?: boolean;
            declaringType?: components["schemas"]["Type"];
            declaringMethod?: components["schemas"]["MethodBase"];
            reflectedType?: components["schemas"]["Type"];
            underlyingSystemType?: components["schemas"]["Type"];
            readonly isTypeDefinition?: boolean;
            readonly isArray?: boolean;
            readonly isByRef?: boolean;
            readonly isPointer?: boolean;
            readonly isConstructedGenericType?: boolean;
            readonly isGenericParameter?: boolean;
            readonly isGenericTypeParameter?: boolean;
            readonly isGenericMethodParameter?: boolean;
            readonly isGenericType?: boolean;
            readonly isGenericTypeDefinition?: boolean;
            readonly isSZArray?: boolean;
            readonly isVariableBoundArray?: boolean;
            readonly isByRefLike?: boolean;
            readonly isFunctionPointer?: boolean;
            readonly isUnmanagedFunctionPointer?: boolean;
            readonly hasElementType?: boolean;
            readonly genericTypeArguments?: components["schemas"]["Type"][] | null;
            /** Format: int32 */
            readonly genericParameterPosition?: number;
            genericParameterAttributes?: components["schemas"]["GenericParameterAttributes"];
            attributes?: components["schemas"]["TypeAttributes"];
            readonly isAbstract?: boolean;
            readonly isImport?: boolean;
            readonly isSealed?: boolean;
            readonly isSpecialName?: boolean;
            readonly isClass?: boolean;
            readonly isNestedAssembly?: boolean;
            readonly isNestedFamANDAssem?: boolean;
            readonly isNestedFamily?: boolean;
            readonly isNestedFamORAssem?: boolean;
            readonly isNestedPrivate?: boolean;
            readonly isNestedPublic?: boolean;
            readonly isNotPublic?: boolean;
            readonly isPublic?: boolean;
            readonly isAutoLayout?: boolean;
            readonly isExplicitLayout?: boolean;
            readonly isLayoutSequential?: boolean;
            readonly isAnsiClass?: boolean;
            readonly isAutoClass?: boolean;
            readonly isUnicodeClass?: boolean;
            readonly isCOMObject?: boolean;
            readonly isContextful?: boolean;
            readonly isEnum?: boolean;
            readonly isMarshalByRef?: boolean;
            readonly isPrimitive?: boolean;
            readonly isValueType?: boolean;
            readonly isSignatureType?: boolean;
            readonly isSecurityCritical?: boolean;
            readonly isSecuritySafeCritical?: boolean;
            readonly isSecurityTransparent?: boolean;
            structLayoutAttribute?: components["schemas"]["StructLayoutAttribute"];
            typeInitializer?: components["schemas"]["ConstructorInfo"];
            typeHandle?: components["schemas"]["RuntimeTypeHandle"];
            /** Format: uuid */
            readonly guid?: string;
            baseType?: components["schemas"]["Type"];
            /** @deprecated */
            readonly isSerializable?: boolean;
            readonly containsGenericParameters?: boolean;
            readonly isVisible?: boolean;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        TypeAttributes: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 16 | 24 | 32 | 128 | 256 | 1024 | 2048 | 4096 | 8192 | 16384 | 65536 | 131072 | 196608 | 262144 | 264192 | 1048576 | 12582912;
        TypeInfo: {
            readonly name?: string | null;
            readonly customAttributes?: components["schemas"]["CustomAttributeData"][] | null;
            readonly isCollectible?: boolean;
            /** Format: int32 */
            readonly metadataToken?: number;
            memberType?: components["schemas"]["MemberTypes"];
            readonly namespace?: string | null;
            readonly assemblyQualifiedName?: string | null;
            readonly fullName?: string | null;
            assembly?: components["schemas"]["Assembly"];
            module?: components["schemas"]["Module"];
            readonly isInterface?: boolean;
            readonly isNested?: boolean;
            declaringType?: components["schemas"]["Type"];
            declaringMethod?: components["schemas"]["MethodBase"];
            reflectedType?: components["schemas"]["Type"];
            underlyingSystemType?: components["schemas"]["Type"];
            readonly isTypeDefinition?: boolean;
            readonly isArray?: boolean;
            readonly isByRef?: boolean;
            readonly isPointer?: boolean;
            readonly isConstructedGenericType?: boolean;
            readonly isGenericParameter?: boolean;
            readonly isGenericTypeParameter?: boolean;
            readonly isGenericMethodParameter?: boolean;
            readonly isGenericType?: boolean;
            readonly isGenericTypeDefinition?: boolean;
            readonly isSZArray?: boolean;
            readonly isVariableBoundArray?: boolean;
            readonly isByRefLike?: boolean;
            readonly isFunctionPointer?: boolean;
            readonly isUnmanagedFunctionPointer?: boolean;
            readonly hasElementType?: boolean;
            readonly genericTypeArguments?: components["schemas"]["Type"][] | null;
            /** Format: int32 */
            readonly genericParameterPosition?: number;
            genericParameterAttributes?: components["schemas"]["GenericParameterAttributes"];
            attributes?: components["schemas"]["TypeAttributes"];
            readonly isAbstract?: boolean;
            readonly isImport?: boolean;
            readonly isSealed?: boolean;
            readonly isSpecialName?: boolean;
            readonly isClass?: boolean;
            readonly isNestedAssembly?: boolean;
            readonly isNestedFamANDAssem?: boolean;
            readonly isNestedFamily?: boolean;
            readonly isNestedFamORAssem?: boolean;
            readonly isNestedPrivate?: boolean;
            readonly isNestedPublic?: boolean;
            readonly isNotPublic?: boolean;
            readonly isPublic?: boolean;
            readonly isAutoLayout?: boolean;
            readonly isExplicitLayout?: boolean;
            readonly isLayoutSequential?: boolean;
            readonly isAnsiClass?: boolean;
            readonly isAutoClass?: boolean;
            readonly isUnicodeClass?: boolean;
            readonly isCOMObject?: boolean;
            readonly isContextful?: boolean;
            readonly isEnum?: boolean;
            readonly isMarshalByRef?: boolean;
            readonly isPrimitive?: boolean;
            readonly isValueType?: boolean;
            readonly isSignatureType?: boolean;
            readonly isSecurityCritical?: boolean;
            readonly isSecuritySafeCritical?: boolean;
            readonly isSecurityTransparent?: boolean;
            structLayoutAttribute?: components["schemas"]["StructLayoutAttribute"];
            typeInitializer?: components["schemas"]["ConstructorInfo"];
            typeHandle?: components["schemas"]["RuntimeTypeHandle"];
            /** Format: uuid */
            readonly guid?: string;
            baseType?: components["schemas"]["Type"];
            /** @deprecated */
            readonly isSerializable?: boolean;
            readonly containsGenericParameters?: boolean;
            readonly isVisible?: boolean;
            readonly genericTypeParameters?: components["schemas"]["Type"][] | null;
            readonly declaredConstructors?: components["schemas"]["ConstructorInfo"][] | null;
            readonly declaredEvents?: components["schemas"]["EventInfo"][] | null;
            readonly declaredFields?: components["schemas"]["FieldInfo"][] | null;
            readonly declaredMembers?: components["schemas"]["MemberInfo"][] | null;
            readonly declaredMethods?: components["schemas"]["MethodInfo"][] | null;
            readonly declaredNestedTypes?: components["schemas"]["TypeInfo"][] | null;
            readonly declaredProperties?: components["schemas"]["PropertyInfo"][] | null;
            readonly implementedInterfaces?: components["schemas"]["Type"][] | null;
        };
        /**
         * @description The fields to change. Every one is optional: absent means "leave alone", which is what makes this a
         *     PATCH rather than a PUT. Password is write-only — it enters here and never appears in a response.
         *     Email is not here: the account service has no setter for it.
         */
        UpdateAccountRequest: {
            level?: string | null;
            isActive?: boolean | null;
            password?: string | null;
        };
        /** @description Body for updating a news entry. */
        UpdateNewsRequest: {
            title?: string | null;
            body?: string | null;
            isPublished?: boolean;
        };
        /** @description A partial settings update: an omitted (null) field is left unchanged. */
        UpdateServerSettingsRequest: {
            description?: string | null;
            contacts?: components["schemas"]["ServerContactsResponse"];
            registrationEnabled?: boolean | null;
        };
        /** @description Carries the single-use token that verifies an account's email. */
        VerifyEmailRequest: {
            token?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAdminStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAdminPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RenewToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListCharacters: {
        parameters: {
            query?: {
                page?: string;
                pageSize?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StreamConsole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SendConsoleCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsoleCommandRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetItemImage: {
        parameters: {
            query?: {
                hue?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListMaps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetFullMapImage: {
        parameters: {
            query?: {
                style?: string;
            };
            header?: never;
            path: {
                map: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMapTile: {
        parameters: {
            query?: {
                style?: string;
            };
            header?: never;
            path: {
                map: string;
                z: string;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMapImageExportStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StartMapImageExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetItemImageExportStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StartItemImageExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListItemTemplates: {
        parameters: {
            query?: {
                page?: string;
                pageSize?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetItemTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetBodyImage: {
        parameters: {
            query?: {
                hue?: number;
            };
            header?: never;
            path: {
                body: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetHairImage: {
        parameters: {
            query?: {
                hue?: number;
                body?: number;
                facial?: boolean;
            };
            header?: never;
            path: {
                style: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMobileTemplateImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListBodies: {
        parameters: {
            query?: {
                page?: string;
                pageSize?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListHairStyles: {
        parameters: {
            query?: {
                page?: string;
                pageSize?: string;
                search?: string;
                facial?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMobileTemplatePaperdoll: {
        parameters: {
            query?: {
                background?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetBodyImageExportStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StartBodyImageExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListAllNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreateNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNewsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetNewsAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNewsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetPlayerMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetMyCharacters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RegisterAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VerifyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetServerInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetServerAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetServerSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateServerSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServerSettingsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UploadServerAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteServerAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetServerStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
