[[item]]
id = "0x0f4f_lbr"
base_id = "base_crossbow"
item_id = 0
rarity = "common"
weight = 7.0
damage_min = 8
damage_max = 43
speed = 18
strength_required = 30
max_hits = 80
buy_price = 46
sell_price = 23

[[item]]
id = "0x13fc_lbr"
base_id = "base_heavy_crossbow"
item_id = 0
rarity = "common"
weight = 9.0
damage_min = 11
damage_max = 56
speed = 10
strength_required = 40
max_hits = 100
buy_price = 56
sell_price = 28

[[item]]
id = "0x13b1_lbr"
base_id = "base_bow"
item_id = 0
rarity = "common"
weight = 7.0
damage_min = 8
damage_max = 41
speed = 20
strength_required = 20
max_hits = 60
buy_price = 46
sell_price = 23

[[item]]
id = "0x26c2_lbr"
base_id = "base_composite_bow"
item_id = 0
rarity = "common"
weight = 5.0
damage_min = 8
damage_max = 39
speed = 21
strength_required = 35
max_hits = 70
buy_price = 57
sell_price = 29

[[item]]
id = "0x26c3_lbr"
base_id = "base_repeating_crossbow"
item_id = 0
rarity = "common"
weight = 6.0
damage_min = 5
damage_max = 29
speed = 30
strength_required = 25
max_hits = 70
buy_price = 65
sell_price = 32

[[item]]
id = "0x27a5_lbr"
base_id = "base_yumi"
item_id = 0
rarity = "common"
weight = 9.0
damage_min = 6
damage_max = 33
speed = 26
strength_required = 30
max_hits = 70
buy_price = 60
sell_price = 30

[[item]]
id = "0x2d1e_lbr"
base_id = "base_elven_composite_longbow"
item_id = 0
rarity = "common"
weight = 9.0
damage_min = 7
damage_max = 37
speed = 22
strength_required = 35
max_hits = 70
buy_price = 52
sell_price = 26

[[item]]
id = "0x2d2b_lbr"
base_id = "base_magical_shortbow"
item_id = 0
rarity = "common"
weight = 6.0
damage_min = 6
damage_max = 31
speed = 28
strength_required = 35
max_hits = 70
buy_price = 51
sell_price = 26
