[[item]]
id = "0x13af_lbr"
base_id = "base_war_axe"
item_id = 0
rarity = "common"
weight = 8.0
damage_min = 9
damage_max = 27
speed = 40
strength_required = 35
max_hits = 80
buy_price = 38
sell_price = 19

[[item]]
id = "0x13e3_lbr"
base_id = "base_smiths_hammer"
item_id = 0
rarity = "common"
weight = 8.0
damage_min = 6
damage_max = 18
speed = 30
strength_required = 30
max_hits = 60
buy_price = 36
sell_price = 18

[[item]]
id = "0x13b3_lbr"
base_id = "base_club"
item_id = 0
rarity = "common"
weight = 9.0
damage_min = 8
damage_max = 24
speed = 40
strength_required = 10
max_hits = 40
buy_price = 27
sell_price = 13

[[item]]
id = "0x0fb4_lbr"
base_id = "base_sledge_hammer"
item_id = 0
rarity = "common"
weight = 9.0
damage_min = 12
damage_max = 38
speed = 15
strength_required = 30
max_hits = 60
buy_price = 32
sell_price = 16

[[item]]
id = "0x0f5c_lbr"
base_id = "base_mace"
item_id = 0
rarity = "common"
weight = 14.0
damage_min = 8
damage_max = 32
speed = 30
strength_required = 20
max_hits = 70
buy_price = 38
sell_price = 30

[[item]]
id = "0x1406_lbr"
base_id = "base_war_mace"
item_id = 0
rarity = "common"
weight = 17.0
damage_min = 10
damage_max = 30
speed = 32
strength_required = 30
max_hits = 110
buy_price = 37
sell_price = 18

[[item]]
id = "0x1438_lbr"
base_id = "base_war_hammer"
item_id = 0
rarity = "common"
weight = 10.0
damage_min = 8
damage_max = 36
speed = 31
strength_required = 40
max_hits = 110
buy_price = 27
sell_price = 13

[[item]]
id = "0x143a_lbr"
base_id = "base_maul"
item_id = 0
rarity = "common"
weight = 14.0
damage_min = 10
damage_max = 30
speed = 30
strength_required = 20
max_hits = 70
buy_price = 31
sell_price = 15

[[item]]
id = "0x143c_lbr"
base_id = "base_hammer_pick"
item_id = 0
rarity = "common"
weight = 9.0
damage_min = 6
damage_max = 33
speed = 30
strength_required = 35
max_hits = 70
buy_price = 31
sell_price = 15

[[item]]
id = "0x26bc_lbr"
base_id = "base_scepter"
item_id = 0
rarity = "common"
weight = 8.0
damage_min = 10
damage_max = 31
speed = 28
strength_required = 20
max_hits = 110
buy_price = 48
sell_price = 26

[[item]]
id = "0x27a3_lbr"
base_id = "base_tessen"
item_id = 0
rarity = "common"
weight = 5.0
damage_min = 6
damage_max = 23
speed = 54
strength_required = 25
max_hits = 60
buy_price = 124
sell_price = 68

[[item]]
id = "0x27a6_lbr"
base_id = "base_tetsubo"
item_id = 0
rarity = "common"
weight = 7.0
damage_min = 7
damage_max = 27
speed = 43
strength_required = 25
max_hits = 65
buy_price = 64
sell_price = 35

[[item]]
id = "0x27ae_lbr"
base_id = "base_nunchaku"
item_id = 0
rarity = "common"
weight = 4.0
damage_min = 7
damage_max = 27
speed = 43
strength_required = 15
max_hits = 55
buy_price = 52
sell_price = 28

[[item]]
id = "0x2d24_lbr"
base_id = "base_diamond_mace"
item_id = 0
rarity = "common"
weight = 10.0
damage_min = 9
damage_max = 29
speed = 30
strength_required = 20
max_hits = 60
buy_price = 28
sell_price = 14

[[item]]
id = "0x48c2_lbr"
base_id = "base_gargish_maul"
item_id = 0
rarity = "common"
weight = 14.0
damage_min = 10
damage_max = 30
speed = 30
strength_required = 20
max_hits = 70
buy_price = 31
sell_price = 15

[[item]]
id = "0x0903_lbr"
base_id = "base_disc_mace"
item_id = 0
rarity = "common"
weight = 14.0
damage_min = 8
damage_max = 25
speed = 35
strength_required = 20
max_hits = 110
buy_price = 76
sell_price = 42

[[item]]
id = "0x48c0_lbr"
base_id = "base_gargish_war_hammer"
item_id = 0
rarity = "common"
weight = 10.0
damage_min = 8
damage_max = 36
speed = 31
strength_required = 40
max_hits = 110
buy_price = 27
sell_price = 13

[[item]]
id = "0x48cc_lbr"
base_id = "base_gargish_tessen"
item_id = 0
rarity = "common"
weight = 5.0
damage_min = 6
damage_max = 23
speed = 54
strength_required = 25
max_hits = 60
buy_price = 124
sell_price = 68

[[item]]
id = "0xa289_lbr"
base_id = "base_barbed_whip"
item_id = 0
rarity = "common"
weight = 5.0
damage_min = 9
damage_max = 29
speed = 30
strength_required = 10
max_hits = 50
buy_price = 28
sell_price = 14
