[[item]]
id = "0x090a_lbr"
base_id = "base_soul_glaive"
item_id = 0
rarity = "common"
weight = 9.0
buy_price = 77
sell_price = 39
hue = 0

[[item]]
id = "0x08ff_lbr"
base_id = "base_boomerang"
item_id = 0
rarity = "common"
weight = 4.0
buy_price = 32
sell_price = 16
hue = 0

[[item]]
id = "0x0901_lbr"
base_id = "base_cyclone"
item_id = 0
rarity = "common"
weight = 6.0
buy_price = 53
sell_price = 26
hue = 0
