title = "Lysander's Notebook"
author = "L. Gathenwale"
content = """Day One :
 
At last, it stands
before me.  The doors
of Thy Sanctum will
open to me now, after
all these years of
searching.  I give

myself unto Thee,
Khal Ankur, I have
come for Thy secrets
and I will kneel
prostrate before Thee.
 Blessed are the
Keepers, praise unto
Thee, a thousand

fortunes in the night."""
item_template = "readable_book"
item_id = 0x0FF1
[translations]
[translations.cze]
title = "Lysanderův zápisník"
content = """Den první:
 
Konečně stojí přede
mnou. Dveře Tvé
svatyně se mi nyní
otevřou po všech těch
letech hledání.
Odevzdávám

se Tobě, Khal Ankur,
přišel jsem pro Tvá
tajemství a padnu před
Tebou na kolena.
Požehnaní buďte
Strážci, chvála Tobě,
tisíc

štěstí v noci."""
[translations.fre]
title = "Le carnet de Lysander"
content = """Premier jour :
 
Enfin, il se dresse
devant moi. Les portes
de Ton Sanctuaire vont
maintenant s’ouvrir à
moi, après toutes ces
années de recherche.
Je me donne

à Toi, Khal Ankur ; je
suis venu pour Tes
secrets et je
m’agenouillerai,
prosterné devant Toi.
Bénis soient les
Gardiens, louanges à
Toi, mille

fortunes dans la nuit."""
[translations.ger]
title = "Lysanders Notizbuch"
content = """Erster Tag:
 
Endlich steht es vor
mir. Die Türen Deines
Heiligtums werden sich
mir nun öffnen, nach
all diesen Jahren der
Suche. Ich gebe

mich Dir hin, Khal
Ankur, ich bin um
Deiner Geheimnisse
willen gekommen und
werde mich vor Dir
niederwerfen. Gesegnet
seien die Hüter, Lob
sei Dir, tausend

Glücksgaben in der
Nacht."""
[translations.ita]
title = "Il taccuino di Lysander"
content = """Giorno Uno :
 
Finalmente si erge
davanti a me. Le porte
del Tuo Santuario si
apriranno per me ora,
dopo tutti questi anni
di ricerca. Mi affido

a Te, Khal Ankur; sono
venuto per i Tuoi
segreti e mi
inginocchierò
prostrato davanti a
Te. Benedetti siano i
Custodi, lode a Te,
mille

fortune nella notte."""
[translations.pol]
title = "Notatnik Lysander"
content = """Dzień pierwszy:
 
Nareszcie stoi przede
mną. Drzwi Twego
Sanktuarium otworzą
się teraz dla mnie, po
tych wszystkich latach
poszukiwań. Oddaję

się Tobie, Khal Ankur;
przybyłem po Twe
tajemnice i padnę
przed Tobą na kolana.
Błogosławieni
Strażnicy, chwała
Tobie, tysiąc

pomyślności w nocy."""
[translations.por]
title = "Caderno de Lysander"
content = """Primeiro dia:
 
Enfim, ergue-se diante
de mim. As portas de
Seu Santuário se
abrirão para mim
agora, depois de todos
estes anos de busca.
Entrego

minha pessoa a Você,
Khal Ankur; vim buscar
Seus segredos e me
ajoelharei prostrado
diante de Você.
Benditos sejam os
Guardiões, louvores a
Você, mil

fortunas na noite."""
[translations.spa]
title = "Cuaderno de Lysander"
content = """Día uno:
 
Al fin se alza ante
mí. Las puertas de Tu
Santuario se abrirán
para mí ahora, después
de tantos años de
búsqueda. Me entrego

a Ti, Khal Ankur; he
venido por Tus
secretos y me postraré
de rodillas ante Ti.
Benditos sean los
Guardianes, alabanzas
a Ti, mil

fortunas en la noche."""
