title = "A Song of Samlethe"
author = "Sandra"
content = """The first bear did
swim by day,
And it did sleep by
night.
It kept itself within
its cave
and ate by starry
light.


The second bear it did
cavort
'Neath canopies of
trees,
And danced its
strange bearish sort
Of joy for all to see.


The first bear, well,
'twas hunted,
And today adorns a
floor.
Its ruggish face has
been dented
By footfalls and the

door.

The second bear did
step once
Into a mushroom ring,
And now does dance
the dunce
For wisps and

unseen things.

So do not dance, and
do not sleep,
Or else be led astray!
For bears all end up
six feet deep
At the end of

Samlethe's day."""
item_template = "readable_scroll"

[translations.cze]
title = "Píseň o Samlethe"
content = """
První medvěd
plaval za dne,
a v noci se
spánku oddal.
Zůstával ve
své jeskyni
a pod hvězdami
jídal.


Druhý medvěd
skotačil
pod korunami
stromů,
a tanec medvědí
radosti své
ukazoval každému.


První medvěd, nu,
byl uloven,
a dnes podlahu
zdobí.
Jeho kobercová tvář
je otlačena
kroky a

dveřmi.

Druhý medvěd jednou
vkročil
do kruhu z hub,
a teď tančí
jako hlupák
pro bludičky a

neviděné věci.

Tak netanči a
nespi také,
ať nesvede tě klam!
Vždyť medvědi šest stop
v zemi leží,
na konci

dne Samlethe."""

[translations.fre]
title = "Une chanson de Samlethe"
content = """
Le premier ours nageait le jour,
Et la nuit il dormait.
Il demeurait dans sa caverne
Et sous les étoiles mangeait.


Le second ours gambadait
Sous la voûte des arbres,
Et dansait sa drôle de joie d’ours
Que tous pouvaient voir.


Le premier ours, eh bien, fut chassé,
Et aujourd’hui orne un sol.
Son visage de tapis a été meurtri
Par les pas et la

porte.

Le second ours entra un jour
Dans un cercle de champignons,
Et maintenant danse comme un sot
Pour les feux follets et les

êtres invisibles.

Alors ne dansez pas et ne dormez pas,
Ou vous serez égarés !
Car tous les ours finissent six pieds sous terre
À la fin du jour de

Samlethe."""

[translations.ger]
title = "Ein Lied von Samlethe"
content = """
Der erste Bär schwamm bei Tag,
Und nachts schlief er ein.
Er blieb in seiner Höhle
Und aß im Sternenschein.


Der zweite Bär, er tollte
Unter dem Dach der Bäume,
Und tanzte seine seltsame Bärenfreude,
Dass alle sie sehen konnten.


Der erste Bär, nun ja, ward gejagt,
Und ziert heut einen Boden.
Sein Teppichgesicht ist eingedrückt
Von Schritten und der

Tür.

Der zweite Bär trat einmal
In einen Pilzring hinein,
Und tanzt nun als der Narr
Für Irrlichter und

unsichtbare Wesen.

So tanze nicht, und schlafe nicht,
Sonst wirst du irregeführt!
Denn alle Bären liegen sechs Fuß tief
Am Ende von

Samlethes Tag."""

[translations.ita]
title = "Una canzone di Samlethe"
content = """
Il primo orso nuotava di giorno,
E dormiva di notte.
Se ne stava nella sua caverna
e mangiava alla luce delle stelle.


Il secondo orso si trastullava
Sotto le chiome degli alberi,
E danzava la sua strana gioia da orso
Perché tutti la vedessero.


Il primo orso, be', fu cacciato,
E oggi adorna un pavimento.
Il suo muso da tappeto è stato ammaccato
Dai passi e dalla

porta.

Il secondo orso entrò una volta
In un cerchio di funghi,
E ora danza da sciocco
Per i fuochi fatui e

le cose invisibili.

Quindi non danzate, e non dormite,
Altrimenti sarete sviati!
Poiché tutti gli orsi finiscono sei piedi sotto terra
Alla fine del

giorno di Samlethe."""

[translations.pol]
title = "Pieśń o Samlethe"
content = """
Pierwszy niedźwiedź
pływał za dnia,
A nocą spał.
Trzymał się swojej
jaskini
I przy świetle gwiazd
jadał.


Drugi niedźwiedź
harcował
Pod koronami
drzew,
Tańczył swój dziwny
niedźwiedzi taniec
Radości na oczach wszystkich.


Pierwszy niedźwiedź, cóż,
został upolowany,
A dziś zdobi
podłogę.
Jego dywanową twarz
wygniotły
Kroki i

drzwi.

Drugi niedźwiedź
raz wszedł
W krąg grzybów,
A teraz tańczy
jak dureń
Dla błędnych ogników i

rzeczy niewidzialnych.

Więc nie tańcz
i nie śpij,
Bo zejdziesz na manowce!
Wszystkie niedźwiedzie kończą
sześć stóp pod ziemią
U kresu

dnia Samlethe."""

[translations.por]
title = "Uma canção de Samlethe"
content = """
O primeiro urso
nadava de dia,
E dormia durante
a noite.
Ficava dentro
de sua caverna
e comia à luz
das estrelas.


O segundo urso
brincava
Sob as copas
das árvores,
E dançava sua
estranha alegria de urso
Para que todos a vissem.


O primeiro urso, bem,
foi caçado,
E hoje enfeita
um chão.
Seu rosto de tapete
ficou amassado
Pelos passos e pela

porta.

O segundo urso
pisou certa vez
Num anel de cogumelos,
E agora dança
como um tolo
Para wisps e

coisas invisíveis.

Então não dance e
não durma,
Ou acabará desencaminhado!
Pois todos os ursos ficam
seis pés abaixo da terra
Ao fim do dia de

Samlethe."""

[translations.spa]
title = "Una canción de Samlethe"
content = """
El primer oso nadaba de día
y dormía por la noche.
En su cueva permanecía
y bajo las estrellas comía.


El segundo oso retozaba
bajo las copas de los árboles,
y su extraña dicha de oso bailaba
para que todos la contemplasen.


Al primer oso, pues, lo cazaron,
y hoy adorna un suelo.
Su cara de alfombra hundieron
las pisadas y la

puerta.

El segundo oso entró una vez
en un círculo de hongos,
y ahora baila como un necio
para los wisps y los

seres invisibles.

Así que no bailes ni duermas,
¡o te perderás por el camino!
Pues todos los osos acaban a seis pies bajo tierra
al final del

día de Samlethe."""
