title = "Journal: Discovery of the Tomb"
author = "Tavara Sewel"
content = """Day Sixteen:

Why do I write?  I
must... not so much
because there must be
some record of
this... what's
happened here... as

for my own sanity.
The act of putting pen
to paper calms me,
focuses me, even in
this madness.
Lysander is dead.  So
many are dead.  And
we're trapped here,

trapped forever in
this nightmare.  He
would not let us pass,
wild in his psychosis,
furious, spitting,
covered in blood, he
swung the ancient
dagger at any who

approached.  He
babbled incoherently,
cursed at us, the most
hateful curses,
prophecy, doom upon
us.  Bergen would
have none of it.
Finally, he leapt at

Lysander, his
massive axe at his
side.  But he would not
be the end of the mad
mage... no... they
were... those hands,
covered in the dirt of
the grave, maggots,

filth.  They rose up
behind Lysander.
That look of curiosity
on the mage's face as
Bergen skidded to a
halt... t'was almost a
moment of sanity for
him, surely, to

attempt to comprehend
what could have
stopped the warrior in
his tracks.  And then
they were upon him.
Skeletal hands, arms
and faces with loose,
corrupted flesh

hanging from yellow
bone.  Inhuman, yet
once human,
staggering towards us
as their companions
tore at Lysander,
coming towards us in
droves."""
item_template = "readable_scroll"
