title = "Lysander's Notebook"
author = "L. Gathenwale"
content = """Day Two:

The woman, Tavara
Sewel, is unbearable.
Her entire demeanor
sickens me.  I would
take her life for Thee
now, my Lord.  But I

cannot alert the
others.  Progress is
made too slowly, I
cannot stand this
perpetual waiting.
Today I knelt down
with the workers,
tossing stones and dirt

aside with my very
hands as they dug at
the last of the rubble
covering the entrance
to Thy Sanctum.  The
Sewel woman was
shocked at my
demeanor, dirtying

my robes, on my
knees in the muck as I
clawed at the rocks.
She thought I did this
for those sickly
scholars, or for her,
or for what she
laughably calls 'The

Gift of Discovery', of
learning.  As if I did
not know what I went
to find!  I come for
Thee, Master.  Soon
shall I receive Thy
gifts, Thy blessings.
Patience, eternal

patience.  I must take
my lessons well.  I
have learned from
Thee, Master, I have."""
item_template = "readable_scroll"
