[[item]]
id = "0x2310_formal_shirt"
base_id = "base_clothing"
item_id = 8976
name = "formal shirt"
rarity = "common"
weight = 1.0
layer = "shirt"
strength_required = 1
max_hits = 50
buy_price = 55
sell_price = 27

[[item]]
id = "0x230f"
base_id = "0x2310_formal_shirt"
item_id = 8975
rarity = "common"

[[item]]
id = "0x2307_fur_boots"
base_id = "base_clothing"
item_id = 8967
name = "fur boots"
rarity = "common"
weight = 3.0
layer = "shoes"
strength_required = 10
armor_rating = 6
max_hits = 30
dyeable = true
buy_price = 45
sell_price = 22
decays = true

[[item]]
id = "0x2308"
base_id = "0x2307_fur_boots"
item_id = 8968
rarity = "common"

[[item]]
id = "0x230c_fur_sarong"
base_id = "base_clothing"
item_id = 8972
name = "fur sarong"
rarity = "common"
weight = 2.0
layer = "outer_legs"
armor_rating = 3
max_hits = 50
buy_price = 31
sell_price = 15

[[item]]
id = "0x230b"
base_id = "0x230c_fur_sarong"
item_id = 8971
rarity = "common"

[[item]]
id = "0x230e_gilded_dress"
base_id = "base_clothing"
item_id = 8974
name = "gilded dress"
rarity = "common"
weight = 2.0
layer = "middle_torso"
armor_rating = 4
max_hits = 50
buy_price = 56
sell_price = 28

[[item]]
id = "0x230d"
base_id = "0x230e_gilded_dress"
item_id = 8973
rarity = "common"
