[[item]]
id = "base_clothing"
base_id = "base_item"
item_id = 0
name = "base clothing"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1541_body_sash"
base_id = "base_clothing"
item_id = 5441
name = "body sash"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1542"
base_id = "0x1541_body_sash"
item_id = 5442
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1515_cloak"
base_id = "base_clothing"
item_id = 5397
name = "cloak"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1530"
base_id = "0x1515_cloak"
item_id = 5424
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f7b_doublet"
base_id = "base_clothing"
item_id = 8059
name = "doublet"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f7c"
base_id = "0x1f7b_doublet"
item_id = 8060
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1eff_fancy_dress"
base_id = "base_clothing"
item_id = 7935
name = "fancy dress"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f00"
base_id = "0x1eff_fancy_dress"
item_id = 7936
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1efd_fancy_shirt"
base_id = "base_clothing"
item_id = 7933
name = "fancy shirt"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1efe"
base_id = "0x1efd_fancy_shirt"
item_id = 7934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x153d_full_apron"
base_id = "base_clothing"
item_id = 5437
name = "full apron"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x153e"
base_id = "0x153d_full_apron"
item_id = 5438
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x153b_half_apron"
base_id = "base_clothing"
item_id = 5435
name = "half apron"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x153c"
base_id = "0x153b_half_apron"
item_id = 5436
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f9f_jester_suit"
base_id = "base_clothing"
item_id = 8095
name = "jester suit"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f_a0"
base_id = "0x1f9f_jester_suit"
item_id = 8096
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1537_kilt"
base_id = "base_clothing"
item_id = 5431
name = "kilt"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1538"
base_id = "0x1537_kilt"
item_id = 5432
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1539_long_pants"
base_id = "base_clothing"
item_id = 5433
name = "long pants"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x153a"
base_id = "0x1539_long_pants"
item_id = 5434
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f01_plain_dress"
base_id = "base_clothing"
item_id = 7937
name = "plain dress"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f02"
base_id = "0x1f01_plain_dress"
item_id = 7938
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f03_robe"
base_id = "base_clothing"
item_id = 7939
name = "robe"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f04"
base_id = "0x1f03_robe"
item_id = 7940
rarity = "common"
movable = false
hue = 0

[[item]]
id = "resurrection_robe"
base_id = "base_clothing"
item_id = 7939
name = "resurrection robe"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1517_shirt"
base_id = "base_clothing"
item_id = 5399
name = "shirt"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1518"
base_id = "0x1517_shirt"
item_id = 5400
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x152e_short_pants"
base_id = "base_clothing"
item_id = 5422
name = "short pants"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x152f"
base_id = "0x152e_short_pants"
item_id = 5423
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1531_skirt"
base_id = "base_clothing"
item_id = 5425
name = "skirt"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1516"
base_id = "0x1531_skirt"
item_id = 5398
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1fa1_tunic"
base_id = "base_clothing"
item_id = 8097
name = "tunic"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1fa2"
base_id = "0x1fa1_tunic"
item_id = 8098
rarity = "common"
movable = false
hue = 0
