[[item]]
id = "0x2655_jester_shoes"
base_id = "base_item"
item_id = 9813
name = "jester shoes"
rarity = "common"
weight = 1.0
buy_price = 100
sell_price = 100
decays = true
hue = 0

[[item]]
id = "0x2656"
base_id = "0x2655_jester_shoes"
item_id = 9814
rarity = "common"
hue = 0

[[item]]
id = "0x26af_arcane_thigh_boots"
base_id = "base_item"
item_id = 9903
name = "arcane thigh boots"
rarity = "common"
movable = true
weight = 4.0
buy_price = 50
sell_price = 25
decays = true
hue = 0

[[item]]
id = "0x2653_waraji"
base_id = "base_item"
item_id = 9811
name = "waraji"
rarity = "common"
weight = 1.0
buy_price = 50
sell_price = 25
decays = true
hue = 0

[[item]]
id = "0x2654"
base_id = "0x2653_waraji"
item_id = 9812
rarity = "common"
hue = 0
