<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>mgboot</AssemblyName>
        <IsPackable>false</IsPackable>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishSelfContained>true</PublishSelfContained>
        <PublishDocumentationFile>false</PublishDocumentationFile>
    </PropertyGroup>
</Project>
