[[spawn]]
id = "tokuno_modernuo_shared_fan_dancers_dojo_7"
map = "tokuno"
name = "Tokuno fandancer"
mobile_ids = ["fandancer"]
npc_list_ids = []
item_ids = []
max = 4
min_minutes = 5
max_minutes = 10
call = 1
exclude = []
z = 39
only_outside = false
[[spawn.areas]]
x1 = 962
y1 = 203
x2 = 992
y2 = 233
