[[loot]]
id = "exodus_minion_loot"
[[loot.entries]]
weight = 900
amount = 1

[[loot.entries]]
weight = 75
item_id = "clockwork_assembly"
comment = "clockwork assembly"
amount = 1

[[loot.entries]]
weight = 25
item_id = "power_crystal"
comment = "power crystal"
amount = 1
