[[loot]]
id = "lowlevelarmor"
[[loot.entries]]
weight = 2103
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13c5"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13c5"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13c6"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13c6"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13c6"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13c7"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13c7"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13c7"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13cb"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13cc"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13cd"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13cd"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13ce"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13ce"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13ce"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13d2"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1dba"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1dba"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13d3"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1c00"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1c01"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1c06"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1c08"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1c09"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1c0a"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1c0b"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13d4"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13d4"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13d5"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13d5"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13d5"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13d6"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13d6"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13d6"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13da"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13db"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13dc"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13dc"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13dd"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13dd"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13dd"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13e1"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x13e2"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1c02"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1c03"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1c0c"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1c0d"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x140a"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x140b"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1b72"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1b73"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1b7a"
amount = 1

[[loot.entries]]
weight = 149
item_id = "0x1b7a"
amount = 1
