[[spawn]]
id = "trammel_13550"
map = "trammel"
name = "Deceit Lvl One"
mobile_ids = []
npc_list_ids = ["deceit_lvl_one_light"]
max = 20
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5137
y1 = 577
x2 = 5155
y2 = 627

[[spawn]]
id = "trammel_13551"
map = "trammel"
name = "Deceit Lvl One"
mobile_ids = []
npc_list_ids = ["deceit_lvl_one_medium"]
max = 10
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5216
y1 = 529
x2 = 5231
y2 = 575

[[spawn]]
id = "trammel_13552"
map = "trammel"
name = "Deceit Lvl One"
mobile_ids = []
npc_list_ids = ["deceit_lvl_one_medium"]
max = 6
min_minutes = 15
max_minutes = 30
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5185
y1 = 536
x2 = 5190
y2 = 566

[[spawn]]
id = "trammel_13553"
map = "trammel"
name = "Deceit Lvl One"
mobile_ids = []
npc_list_ids = ["deceit_lvl_one_light"]
max = 20
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5168
y1 = 584
x2 = 5206
y2 = 622

[[spawn]]
id = "trammel_13554"
map = "trammel"
name = "Deceit Lvl One"
mobile_ids = []
npc_list_ids = ["deceit_lvl_one"]
max = 8
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5160
y1 = 560
x2 = 5174
y2 = 574

[[spawn]]
id = "trammel_13555"
map = "trammel"
name = "Deceit Lvl Two"
mobile_ids = []
npc_list_ids = ["deceit_lvl_two"]
max = 20
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5280
y1 = 536
x2 = 5342
y2 = 550

[[spawn]]
id = "trammel_13556"
map = "trammel"
name = "Deceit Lvl Two"
mobile_ids = []
npc_list_ids = ["deceit_lvl_two"]
max = 10
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5280
y1 = 536
x2 = 5286
y2 = 574

[[spawn]]
id = "trammel_13557"
map = "trammel"
name = "Deceit Lvl Two"
mobile_ids = []
npc_list_ids = ["deceit_lvl_two"]
max = 15
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5280
y1 = 576
x2 = 5326
y2 = 590

[[spawn]]
id = "trammel_13558"
map = "trammel"
name = "Deceit Lvl Two"
mobile_ids = []
npc_list_ids = ["deceit_lvl_two"]
max = 15
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5280
y1 = 576
x2 = 5326
y2 = 590

[[spawn]]
id = "trammel_13559"
map = "trammel"
name = "Deceit Lvl Two"
mobile_ids = []
npc_list_ids = ["deceit_lvl_two"]
max = 6
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5296
y1 = 600
x2 = 5310
y2 = 614

[[spawn]]
id = "trammel_13560"
map = "trammel"
name = "Deceit Lvl Two"
mobile_ids = []
npc_list_ids = ["deceit_lvl_two"]
max = 6
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5288
y1 = 616
x2 = 5302
y2 = 630

[[spawn]]
id = "trammel_13561"
map = "trammel"
name = "Deceit Lvl Two"
mobile_ids = []
npc_list_ids = ["deceit_lvl_two"]
max = 10
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5336
y1 = 576
x2 = 5342
y2 = 622

[[spawn]]
id = "trammel_13562"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = []
npc_list_ids = ["deceit_lvl_three_poison"]
max = 4
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5148
y1 = 688
x2 = 5162
y2 = 702

[[spawn]]
id = "trammel_13563"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = []
npc_list_ids = ["deceit_lvl_three_poison"]
max = 8
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5209
y1 = 721
x2 = 5230
y2 = 750

[[spawn]]
id = "trammel_13564"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = ["poisonele"]
npc_list_ids = []
max = 2
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5176
y1 = 721
x2 = 5190
y2 = 734

[[spawn]]
id = "trammel_13565"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = ["poisonele"]
npc_list_ids = []
max = 1
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5184
y1 = 688
x2 = 5198
y2 = 702

[[spawn]]
id = "trammel_13566"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = []
npc_list_ids = ["deceit_lvl_three_light"]
max = 8
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5168
y1 = 656
x2 = 5174
y2 = 702

[[spawn]]
id = "trammel_13567"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = []
npc_list_ids = ["deceit_lvl_three_light"]
max = 8
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5168
y1 = 656
x2 = 5206
y2 = 662

[[spawn]]
id = "trammel_13568"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = []
npc_list_ids = ["deceit_lvl_three_poison"]
max = 3
min_minutes = 15
max_minutes = 30
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5184
y1 = 648
x2 = 5206
y2 = 662

[[spawn]]
id = "trammel_13569"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = []
npc_list_ids = ["deceit_lvl_three_light"]
max = 8
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5217
y1 = 673
x2 = 5230
y2 = 710

[[spawn]]
id = "trammel_13570"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = []
npc_list_ids = ["deceit_lvl_three_light"]
max = 8
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5136
y1 = 673
x2 = 5174
y2 = 678

[[spawn]]
id = "trammel_13571"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = []
npc_list_ids = ["deceit_lvl_three_light"]
max = 6
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5136
y1 = 653
x2 = 5142
y2 = 687

[[spawn]]
id = "trammel_13572"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = []
npc_list_ids = ["deceit_lvl_three_light"]
max = 6
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5128
y1 = 689
x2 = 5136
y2 = 726

[[spawn]]
id = "trammel_13573"
map = "trammel"
name = "Deceit Lvl Three"
mobile_ids = []
npc_list_ids = ["deceit_lvl_three"]
max = 8
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5144
y1 = 712
x2 = 5158
y2 = 734

[[spawn]]
id = "trammel_13574"
map = "trammel"
name = "Deceit Lvl Four"
mobile_ids = []
npc_list_ids = ["deceit_lvl_fourlichroom"]
max = 4
min_minutes = 25
max_minutes = 50
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5304
y1 = 741
x2 = 5327
y2 = 758

[[spawn]]
id = "trammel_13575"
map = "trammel"
name = "Deceit Lvl Four"
mobile_ids = []
npc_list_ids = ["deceit_lvl_four_light"]
max = 6
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5320
y1 = 672
x2 = 5334
y2 = 710

[[spawn]]
id = "trammel_13576"
map = "trammel"
name = "Deceit Lvl Four"
mobile_ids = []
npc_list_ids = ["deceit_lvl_four_light"]
max = 10
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5296
y1 = 664
x2 = 5318
y2 = 686

[[spawn]]
id = "trammel_13577"
map = "trammel"
name = "Deceit Lvl Four"
mobile_ids = []
npc_list_ids = ["deceit_lvl_four_light"]
max = 10
min_minutes = 15
max_minutes = 30
call = 2
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5280
y1 = 688
x2 = 5310
y2 = 702

[[spawn]]
id = "trammel_13579"
map = "trammel"
name = "Deceit Lvl Four"
mobile_ids = []
npc_list_ids = ["deceit_lvl_four_light"]
max = 4
min_minutes = 15
max_minutes = 30
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 5280
y1 = 648
x2 = 5286
y2 = 662
