[[spawn]]
id = "trammel_7500"
map = "trammel"
name = "Minoc - The Oak Throne"
mobile_ids = ["carpenter"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2507
y1 = 475
x2 = 2511
y2 = 477

[[spawn]]
id = "trammel_7501"
map = "trammel"
name = "Minoc - The Matewan (miner)"
mobile_ids = ["miner"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2460
y1 = 485
x2 = 2464
y2 = 487

[[spawn]]
id = "trammel_7502"
map = "trammel"
name = "Minoc - The Matewan (jeweler)"
mobile_ids = ["jeweler"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2453
y1 = 489
x2 = 2457
y2 = 497

[[spawn]]
id = "trammel_7503"
map = "trammel"
name = "Minoc - Gears and Gadgets"
mobile_ids = ["tinker"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2459
y1 = 451
x2 = 2461
y2 = 453

[[spawn]]
id = "trammel_7504"
map = "trammel"
name = "Minoc - The Mystical Lute"
mobile_ids = ["bard"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2417
y1 = 544
x2 = 2422
y2 = 546

[[spawn]]
id = "trammel_7505"
map = "trammel"
name = "Minoc - The Forgery"
mobile_ids = ["blacksmith"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2467
y1 = 559
x2 = 2471
y2 = 561

[[spawn]]
id = "trammel_7506"
map = "trammel"
name = "Minoc - Warrior's Battle Gear"
mobile_ids = ["armourer"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2532
y1 = 573
x2 = 2535
y2 = 576

[[spawn]]
id = "trammel_7507"
map = "trammel"
name = "Minoc - The Healing Hand"
mobile_ids = ["healer"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2571
y1 = 588
x2 = 2573
y2 = 590

[[spawn]]
id = "trammel_7508"
map = "trammel"
name = "Minoc - Survival Threads"
mobile_ids = ["tailor"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2525
y1 = 546
x2 = 2527
y2 = 549

[[spawn]]
id = "trammel_7509"
map = "trammel"
name = "Minoc - The Stretched Hide"
mobile_ids = ["leatherworker"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2518
y1 = 522
x2 = 2519
y2 = 525

[[spawn]]
id = "trammel_7510"
map = "trammel"
name = "Minoc - The Golden Pick Axe"
mobile_ids = ["miner"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2497
y1 = 430
x2 = 2499
y2 = 435

[[spawn]]
id = "trammel_7511"
map = "trammel"
name = "Minoc - The Old Miner's Supplies"
mobile_ids = ["provisioner"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2449
y1 = 427
x2 = 2451
y2 = 429

[[spawn]]
id = "trammel_7512"
map = "trammel"
name = "Minoc - The Slaughtered Cow"
mobile_ids = ["butcher"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2433
y1 = 409
x2 = 2436
y2 = 412

[[spawn]]
id = "trammel_7513"
map = "trammel"
name = "Minoc - The Barnacle"
mobile_ids = ["tavernkeeper"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2458
y1 = 399
x2 = 2461
y2 = 402

[[spawn]]
id = "trammel_7514"
map = "trammel"
name = "Minoc - Stables"
mobile_ids = ["animaltrainer"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2515
y1 = 375
x2 = 2518
y2 = 377

[[spawn]]
id = "trammel_7515"
map = "trammel"
name = "Minoc - Thief Guildmaster"
mobile_ids = []
npc_list_ids = ["thiefguildmaster"]
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = true
[[spawn.areas]]
x1 = 2393
y1 = 377
x2 = 2535
y2 = 595

[[spawn]]
id = "trammel_7516"
map = "trammel"
name = "Minoc - Gypsy Tent 1"
mobile_ids = ["gypsy"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2506
y1 = 633
x2 = 2509
y2 = 640

[[spawn]]
id = "trammel_7517"
map = "trammel"
name = "Minoc - Gypsy Tent 2"
mobile_ids = ["gypsy"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2524
y1 = 635
x2 = 2527
y2 = 641

[[spawn]]
id = "trammel_7518"
map = "trammel"
name = "Minoc - Gypsy Tent 3"
mobile_ids = ["gypsy"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2541
y1 = 633
x2 = 2544
y2 = 640

[[spawn]]
id = "trammel_7519"
map = "trammel"
name = "Minoc - Gypsy Tent 4"
mobile_ids = ["gypsy"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2514
y1 = 650
x2 = 2520
y2 = 659

[[spawn]]
id = "trammel_7520"
map = "trammel"
name = "Minoc - Gypsy Tent 5"
mobile_ids = ["gypsy"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2530
y1 = 653
x2 = 2535
y2 = 660

[[spawn]]
id = "trammel_7521"
map = "trammel"
name = "Minoc - Gypsy Tent 6"
mobile_ids = ["gypsy"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2546
y1 = 650
x2 = 2552
y2 = 659

[[spawn]]
id = "trammel_7522"
map = "trammel"
name = "Minoc - Gypsy Tent 7"
mobile_ids = ["gypsy"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2527
y1 = 671
x2 = 2530
y2 = 678

[[spawn]]
id = "trammel_7523"
map = "trammel"
name = "Minoc - Gypsy Tent 8"
mobile_ids = ["gypsy"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2543
y1 = 673
x2 = 2546
y2 = 679

[[spawn]]
id = "trammel_7524"
map = "trammel"
name = "Minoc - Warrior's Battle Gear"
mobile_ids = ["blacksmith"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2525
y1 = 573
x2 = 2530
y2 = 575

[[spawn]]
id = "trammel_7525"
map = "trammel"
name = "Minoc - Survival Threads"
mobile_ids = ["weaver"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2527
y1 = 544
x2 = 2531
y2 = 548

[[spawn]]
id = "trammel_7526"
map = "trammel"
name = "Minoc - Survival Threads"
mobile_ids = ["spinner"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2527
y1 = 544
x2 = 2531
y2 = 548

[[spawn]]
id = "trammel_7527"
map = "trammel"
name = "Minoc - The Survival Shop"
mobile_ids = ["provisioner"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2529
y1 = 550
x2 = 2532
y2 = 552

[[spawn]]
id = "trammel_7528"
map = "trammel"
name = "Minoc - The Survival Shop"
mobile_ids = ["cobbler"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2529
y1 = 550
x2 = 2532
y2 = 552

[[spawn]]
id = "trammel_7531"
map = "trammel"
name = "Minoc - Town Crier (South)"
mobile_ids = ["towncrier"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2519
y1 = 558
x2 = 2519
y2 = 558

[[spawn]]
id = "trammel_7532"
map = "trammel"
name = "Minoc - The Oak Throne"
mobile_ids = ["architect"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2507
y1 = 475
x2 = 2519
y2 = 477

[[spawn]]
id = "trammel_7533"
map = "trammel"
name = "Minoc - The New World Order"
mobile_ids = ["fighter"]
npc_list_ids = []
max = 2
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2480
y1 = 425
x2 = 2486
y2 = 434

[[spawn]]
id = "trammel_7534"
map = "trammel"
name = "Minoc - The Old Miner's Supplies"
mobile_ids = ["cobbler"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2453
y1 = 427
x2 = 2461
y2 = 429

[[spawn]]
id = "trammel_7535"
map = "trammel"
name = "Minoc - The Barnacle"
mobile_ids = ["waiter"]
npc_list_ids = []
max = 3
min_minutes = 480
max_minutes = 600
call = 3
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2465
y1 = 397
x2 = 2494
y2 = 403

[[spawn]]
id = "trammel_7536"
map = "trammel"
name = "Minoc - The Barnacle"
mobile_ids = ["cook"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2458
y1 = 399
x2 = 2461
y2 = 402

[[spawn]]
id = "trammel_7537"
map = "trammel"
name = "Minoc - Docks 1"
mobile_ids = ["fisher"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2508
y1 = 337
x2 = 2529
y2 = 348

[[spawn]]
id = "trammel_7538"
map = "trammel"
name = "Minoc - Docks 2"
mobile_ids = ["sailor"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2508
y1 = 337
x2 = 2529
y2 = 348

[[spawn]]
id = "trammel_7539"
map = "trammel"
name = "Minoc - Town Crier (North)"
mobile_ids = ["towncrier"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2476
y1 = 414
x2 = 2476
y2 = 414

[[spawn]]
id = "trammel_7540"
map = "trammel"
name = "Minoc - All Townfolk"
mobile_ids = []
npc_list_ids = ["alltownfolk"]
max = 15
min_minutes = 480
max_minutes = 600
call = 5
exclude = []
only_outside = true
[[spawn.areas]]
x1 = 2393
y1 = 377
x2 = 2535
y2 = 595

[[spawn]]
id = "trammel_7541"
map = "trammel"
name = "Minoc - Town Animals"
mobile_ids = []
npc_list_ids = ["britainanimallist"]
max = 20
min_minutes = 480
max_minutes = 600
call = 5
exclude = []
only_outside = true
[[spawn.areas]]
x1 = 2393
y1 = 377
x2 = 2535
y2 = 595

[[spawn]]
id = "trammel_7542"
map = "trammel"
name = "Minoc - The Stretched Hide"
mobile_ids = ["tanner"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2521
y1 = 520
x2 = 2523
y2 = 525

[[spawn]]
id = "trammel_7543"
map = "trammel"
name = "Minoc - The Stretched Hide"
mobile_ids = ["furtrader"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2521
y1 = 527
x2 = 2523
y2 = 532

[[spawn]]
id = "trammel_7544"
map = "trammel"
name = "Minoc - Stables"
mobile_ids = ["veterinarian"]
npc_list_ids = []
max = 1
min_minutes = 480
max_minutes = 600
call = 1
exclude = []
only_outside = false
[[spawn.areas]]
x1 = 2515
y1 = 375
x2 = 2518
y2 = 377
