<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="Grpc.AspNetCore" Version="2.84.0"/>
        <ProjectReference Include="../Moongate.Admin.Contracts/Moongate.Admin.Contracts.csproj"/>
        <ProjectReference Include="../Moongate.Server.Core/Moongate.Server.Core.csproj"/>
        <ProjectReference Include="../Moongate.Server.Ultima/Moongate.Server.Ultima.csproj"/>
        <InternalsVisibleTo Include="Moongate.Tests"/>
    </ItemGroup>
</Project>
