[[item]]
id = "powergenerator"
item_id = 115
name = "power generator"
rarity = "common"
weight = 2.55
hue = 0

[[item]]
id = "powergenerator_2"
item_id = 118
name = "power generator"
rarity = "common"
weight = 2.55
hue = 0

[[item]]
id = "powergenerator_3"
item_id = 117
name = "power generator"
rarity = "common"
weight = 2.55
hue = 0

[[item]]
id = "powergenerator_4"
item_id = 14324
name = "power generator"
rarity = "common"
weight = 2.55
hue = 0

[[item]]
id = "powergenerator_ctrlpanel"
item_id = 3036
name = "control panel"
rarity = "common"
weight = 2.55
hue = 0
