namespace Moongate.Server.Ultima.Types.Items;

/// <summary>
///     The shape of the light an item gives, as the client draws it for a light source (ModernUO's LightType); sent in
///     the light byte of the world item packets.
/// </summary>
public enum LightType : byte
{
    ArchedWindowEast = 0,
    Circle225 = 1,
    Circle150 = 2,
    DoorSouth = 3,
    DoorEast = 4,
    NorthBig = 5,
    NorthEastBig = 6,
    EastBig = 7,
    WestBig = 8,
    SouthWestBig = 9,
    SouthBig = 10,
    NorthSmall = 11,
    NorthEastSmall = 12,
    EastSmall = 13,
    WestSmall = 14,
    SouthSmall = 15,
    DecorationNorth = 16,
    DecorationNorthEast = 17,
    EastTiny = 18,
    DecorationWest = 19,
    DecorationSouthWest = 20,
    SouthTiny = 21,
    RectWindowSouthNoRay = 22,
    RectWindowEastNoRay = 23,
    RectWindowSouth = 24,
    RectWindowEast = 25,
    ArchedWindowSouthNoRay = 26,
    ArchedWindowEastNoRay = 27,
    ArchedWindowSouth = 28,
    Circle300 = 29,
    NorthWestBig = 30,
    DarkSouthEast = 31,
    DarkSouth = 32,
    DarkNorthWest = 33,
    DarkSouthEast2 = 34,
    DarkEast = 35,
    DarkCircle300 = 36,
    DoorOpenSouth = 37,
    DoorOpenEast = 38,
    SquareWindowEast = 39,
    SquareWindowEastNoRay = 40,
    SquareWindowSouth = 41,
    SquareWindowSouthNoRay = 42,
    Empty = 43,
    SkinnyWindowSouthNoRay = 44,
    SkinnyWindowEast = 45,
    SkinnyWindowEastNoRay = 46,
    HoleSouth = 47,
    HoleEast = 48,
    Moongate = 49,
    Strips = 50,
    SmallHoleSouth = 51,
    SmallHoleEast = 52,
    NorthBig2 = 53,
    WestBig2 = 54,
    NorthWestBig2 = 55
}
