[[item]]
id = "0x2042_lord_british"
base_id = "base_item"
item_id = 8258
name = "Lord British"
rarity = "common"
movable = true
weight = 0.3
decays = true
loot_type = "newbied"
hue = 0

[[item]]
id = "0x2043_lord_blackthorne"
base_id = "base_item"
item_id = 8259
name = "Lord Blackthorne"
rarity = "common"
movable = true
weight = 0.3
decays = true
loot_type = "newbied"
hue = 0

[[item]]
id = "0x2050_dupre_the_fighter"
base_id = "base_item"
item_id = 8272
name = "Dupre the Fighter"
rarity = "common"
movable = true
weight = 0.3
decays = true
loot_type = "newbied"
hue = 0

[[item]]
id = "0x204e_death_shroud"
base_id = "base_item"
item_id = 8270
name = "death shroud"
rarity = "common"
movable = true
weight = 0.3
decays = true
loot_type = "newbied"
hue = 0

[[item]]
id = "0x204f_u_gm_robe"
base_id = "base_item"
item_id = 8271
name = "GM Robe"
rarity = "common"
movable = true
weight = 0.3
layer = "inner_torso"
decays = true
loot_type = "newbied"
hue = 0

[[item]]
id = "00x204f_b"
base_id = "base_item"
item_id = 8271
name = "Counselor Robe"
rarity = "common"
movable = true
weight = 0.3
layer = "inner_torso"
decays = true
loot_type = "newbied"
hue = 3

[[item]]
id = "0x204f_r_gamemaster_robe"
base_id = "base_item"
item_id = 8271
name = "Gamemaster Robe"
rarity = "common"
movable = true
weight = 0.3
layer = "inner_torso"
decays = true
loot_type = "newbied"
hue = 37

[[item]]
id = "0x204f_g_seer_robe"
base_id = "base_item"
item_id = 8271
name = "Seer Robe"
rarity = "common"
movable = true
weight = 0.3
layer = "inner_torso"
decays = true
loot_type = "newbied"
hue = 72

[[item]]
id = "0x204f_a_admin_robe"
base_id = "base_item"
item_id = 8271
name = "Admin Robe"
rarity = "common"
movable = true
weight = 0.3
layer = "inner_torso"
decays = true
loot_type = "newbied"
hue = 1
