[[item]]
id = "0x13af_tol"
base_id = "base_war_axe"
item_id = 0
rarity = "common"
weight = 8.0
damage_min = 12
damage_max = 16
speed = 46
strength_required = 35
max_hits = 80
buy_price = 29
sell_price = 14

[[item]]
id = "0x13e3_tol"
base_id = "base_smiths_hammer"
item_id = 0
rarity = "common"
weight = 8.0
damage_min = 13
damage_max = 17
speed = 42
strength_required = 40
max_hits = 70
buy_price = 21
sell_price = 10

[[item]]
id = "0x13b3_tol"
base_id = "base_club"
item_id = 0
rarity = "common"
weight = 9.0
damage_min = 10
damage_max = 14
speed = 50
strength_required = 40
max_hits = 40
buy_price = 16
sell_price = 8

[[item]]
id = "0x0fb4_tol"
base_id = "base_sledge_hammer"
item_id = 0
rarity = "common"
weight = 10.0
damage_min = 13
damage_max = 17
speed = 42
strength_required = 40
max_hits = 70
buy_price = 32
sell_price = 16

[[item]]
id = "0x0f5c_tol"
base_id = "base_mace"
item_id = 0
rarity = "common"
weight = 14.0
damage_min = 11
damage_max = 15
speed = 50
strength_required = 45
max_hits = 70
buy_price = 31
sell_price = 14

[[item]]
id = "0x1406_tol"
base_id = "base_war_mace"
item_id = 0
rarity = "common"
weight = 17.0
damage_min = 15
damage_max = 19
speed = 36
strength_required = 80
max_hits = 110
buy_price = 31
sell_price = 15

[[item]]
id = "0x1438_tol"
base_id = "base_war_hammer"
item_id = 0
rarity = "common"
weight = 10.0
damage_min = 17
damage_max = 20
speed = 36
strength_required = 95
max_hits = 110
buy_price = 25
sell_price = 12

[[item]]
id = "0x143a_tol"
base_id = "base_maul"
item_id = 0
rarity = "common"
weight = 10.0
damage_min = 14
damage_max = 18
speed = 39
strength_required = 45
max_hits = 70
buy_price = 21
sell_price = 10

[[item]]
id = "0x143c_tol"
base_id = "base_hammer_pick"
item_id = 0
rarity = "common"
weight = 9.0
damage_min = 13
damage_max = 17
speed = 42
strength_required = 45
max_hits = 70
buy_price = 26
sell_price = 13

[[item]]
id = "0x26bc_tol"
base_id = "base_scepter"
item_id = 0
rarity = "common"
weight = 8.0
damage_min = 14
damage_max = 18
speed = 39
strength_required = 40
max_hits = 110
buy_price = 39
sell_price = 19

[[item]]
id = "0x27a3_tol"
base_id = "base_tessen"
item_id = 0
rarity = "common"
weight = 6.0
damage_min = 10
damage_max = 13
speed = 68
strength_required = 35
max_hits = 60
buy_price = 83
sell_price = 41

[[item]]
id = "0x27a6_tol"
base_id = "base_tetsubo"
item_id = 0
rarity = "common"
weight = 8.0
damage_min = 12
damage_max = 15
speed = 55
strength_required = 35
max_hits = 65
buy_price = 43
sell_price = 21

[[item]]
id = "0x27ae_tol"
base_id = "base_nunchaku"
item_id = 0
rarity = "common"
weight = 5.0
damage_min = 12
damage_max = 15
speed = 55
strength_required = 15
max_hits = 55
buy_price = 35
sell_price = 17

[[item]]
id = "0x2d24_tol"
base_id = "base_diamond_mace"
item_id = 0
rarity = "common"
weight = 10.0
damage_min = 13
damage_max = 17
speed = 42
strength_required = 35
max_hits = 60
buy_price = 32
sell_price = 16

[[item]]
id = "0x48c2_tol"
base_id = "base_gargish_maul"
item_id = 0
rarity = "common"
weight = 10.0
damage_min = 14
damage_max = 18
speed = 39
strength_required = 45
max_hits = 70
buy_price = 13
sell_price = 6

[[item]]
id = "0x0903_tol"
base_id = "base_disc_mace"
item_id = 0
rarity = "common"
weight = 14.0
damage_min = 11
damage_max = 15
speed = 50
strength_required = 45
max_hits = 110
buy_price = 62
sell_price = 31

[[item]]
id = "0x48c0_tol"
base_id = "base_gargish_war_hammer"
item_id = 0
rarity = "common"
weight = 10.0
damage_min = 17
damage_max = 20
speed = 36
strength_required = 95
max_hits = 110
buy_price = 16
sell_price = 8

[[item]]
id = "0x48cc_tol"
base_id = "base_gargish_tessen"
item_id = 0
rarity = "common"
weight = 6.0
damage_min = 10
damage_max = 13
speed = 68
strength_required = 35
max_hits = 60
buy_price = 23
sell_price = 11

[[item]]
id = "0xa289_tol"
base_id = "base_barbed_whip"
item_id = 0
rarity = "common"
weight = 5.0
damage_min = 13
damage_max = 17
speed = 15
strength_required = 20
max_hits = 48
buy_price = 32
sell_price = 16
