[[item]]
id = "0x0df2_tol"
base_id = "base_wand"
item_id = 0
rarity = "common"
weight = 1.0
damage_min = 11
damage_max = 15
speed = 50
strength_required = 5
max_hits = 110
buy_price = 26
sell_price = 12
