[[item]]
id = "random_magic_item"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_item_1"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_item_2"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_item_3"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_item_4"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_item_5"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_weapon"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_weapon_1"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_weapon_2"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_weapon_3"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_weapon_4"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_weapon_5"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_armor"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_armor_1"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_armor_2"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_armor_3"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_armor_4"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_armor_5"
base_id = "base_item"
item_id = 3934
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_wand"
base_id = "base_item"
item_id = 3570
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_wand_1"
base_id = "base_item"
item_id = 3570
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_wand_2"
base_id = "base_item"
item_id = 3570
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_wand_3"
base_id = "base_item"
item_id = 3570
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_wand_4"
base_id = "base_item"
item_id = 3570
rarity = "common"
movable = false
hue = 0

[[item]]
id = "random_magic_wand_5"
base_id = "base_item"
item_id = 3570
rarity = "common"
movable = false
hue = 0

[[item]]
id = "fireworks_wand"
base_id = "base_item"
item_id = 3570
name = "fireworks wand"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "orcishkinmask"
base_id = "base_item"
item_id = 5148
name = "a mask of orcish kin"
rarity = "common"
movable = false
hue = 0
