<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishSelfContained>true</PublishSelfContained>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <PublishDocumentationFile>false</PublishDocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="ConsoleAppFramework" Version="5.7.13">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <ProjectReference Include="../Moongate.Server.Ultima/Moongate.Server.Ultima.csproj"/>
        <InternalsVisibleTo Include="Moongate.UoxItemConverter.Tests"/>
    </ItemGroup>
</Project>
