<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Moongate.Server.Ultima/Moongate.Server.Ultima.csproj"/>
        <InternalsVisibleTo Include="Moongate.UoxItemConverter.Tests"/>
        <InternalsVisibleTo Include="mgctl"/>
    </ItemGroup>
</Project>
