using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

// Converts RunUO-format decoration .cfg files into the YAML the shard loads.
//
// This runs once, by hand, and never at boot. The .cfg format carries semantics rather than just
// coordinates -- Hue, Facing, PointDest, Content, Spawn and half a dozen more -- and resolving those
// against this codebase's model belongs in a conversion, not in a parser the server re-runs every
// start and can fail on.
//
// It is committed rather than thrown away, unlike the one-off used for the mobile templates: this is
// upstream data that changes, and without the script a re-import means writing the parser again.
//
//   dotnet run scripts/convert-decorations.cs -- <source-dir> <output-dir>
//
// The source directory holds one subdirectory per map. Output is one YAML file per map, plus a report
// on stdout of every attribute the conversion did not consume -- nothing is dropped in silence.

if (args.Length < 2)
{
    Console.Error.WriteLine("usage: convert-decorations <source-dir> <output-dir>");

    return 1;
}

var sourceRoot = args[0];
var outputRoot = args[1];

if (!Directory.Exists(sourceRoot))
{
    Console.Error.WriteLine($"source directory not found: {sourceRoot}");

    return 1;
}

// A declaration: a type name, a 0x graphic, and an optional (k=v; k=v) tail.
var declaration = new Regex(@"^(?<type>[A-Za-z]\w*)\s+0x(?<id>[0-9A-Fa-f]+)\s*(\((?<attrs>[^)]*)\))?\s*$");

// A coordinate line: three signed integers.
var coordinate = new Regex(@"^(?<x>-?\d+)\s+(?<y>-?\d+)\s+(?<z>-?\d+)\s*$");

var unconsumed = new SortedDictionary<string, int>(StringComparer.Ordinal);
var declaredTypes = new SortedDictionary<string, int>(StringComparer.Ordinal);
var totalGroups = 0;
var totalObjects = 0;

Directory.CreateDirectory(outputRoot);

// Sorted so the same input always produces the same output: a re-import has to diff cleanly.
foreach (var mapDirectory in Directory.GetDirectories(sourceRoot).OrderBy(d => d, StringComparer.Ordinal))
{
    var mapName = Path.GetFileName(mapDirectory);
    var groups = new List<Group>();

    foreach (var file in Directory.GetFiles(mapDirectory, "*.cfg", SearchOption.AllDirectories)
                                  .OrderBy(f => f, StringComparer.Ordinal))
    {
        Group? current = null;

        foreach (var raw in File.ReadLines(file, Encoding.UTF8))
        {
            var line = raw.Trim();

            if (line.Length == 0 || line.StartsWith('#'))
            {
                continue;
            }

            var declared = declaration.Match(line);

            if (declared.Success)
            {
                if (current is { Points.Count: > 0 })
                {
                    groups.Add(current);
                }

                var attributes = ParseAttributes(declared.Groups["attrs"].Value);
                var hue = 0;

                if (attributes.TryGetValue("Hue", out var hueText))
                {
                    hue = ParseNumber(hueText);
                    attributes.Remove("Hue");
                }

                // Everything left is semantics this pass does not place -- a teleport destination, a
                // chest's contents, a door's facing. Counted and reported rather than dropped, so the
                // pass that does place them knows what is waiting.
                foreach (var key in attributes.Keys)
                {
                    unconsumed.TryGetValue(key, out var seen);
                    unconsumed[key] = seen + 1;
                }

                var type = declared.Groups["type"].Value;
                declaredTypes.TryGetValue(type, out var typeSeen);
                declaredTypes[type] = typeSeen + 1;

                current = new Group(
                    type,
                    int.Parse(declared.Groups["id"].Value, NumberStyles.HexNumber, CultureInfo.InvariantCulture),
                    hue,
                    []
                );

                continue;
            }

            var point = coordinate.Match(line);

            if (point.Success && current is not null)
            {
                current.Points.Add(
                    (
                        int.Parse(point.Groups["x"].Value, CultureInfo.InvariantCulture),
                        int.Parse(point.Groups["y"].Value, CultureInfo.InvariantCulture),
                        int.Parse(point.Groups["z"].Value, CultureInfo.InvariantCulture)
                    )
                );
            }
        }

        if (current is { Points.Count: > 0 })
        {
            groups.Add(current);
        }
    }

    if (groups.Count == 0)
    {
        continue;
    }

    var yaml = new StringBuilder();
    yaml.AppendLine("# Generated by scripts/convert-decorations.cs -- do not hand-edit.");
    yaml.AppendLine($"# Source: RunUO decoration data for {mapName}.");
    yaml.AppendLine();

    foreach (var group in groups)
    {
        yaml.AppendLine($"- type: {group.Type}");
        yaml.AppendLine($"  itemId: {group.ItemId}");

        if (group.Hue != 0)
        {
            yaml.AppendLine($"  hue: {group.Hue}");
        }

        yaml.AppendLine("  at:");

        foreach (var (x, y, z) in group.Points)
        {
            yaml.AppendLine($"    - [{x}, {y}, {z}]");
        }
    }

    File.WriteAllText(Path.Combine(outputRoot, $"{mapName.ToLowerInvariant()}.yaml"), yaml.ToString());

    totalGroups += groups.Count;
    totalObjects += groups.Sum(g => g.Points.Count);

    Console.WriteLine($"{mapName,-22} {groups.Count,6} groups  {groups.Sum(g => g.Points.Count),7} objects");
}

Console.WriteLine();
Console.WriteLine($"TOTAL{"",-17} {totalGroups,6} groups  {totalObjects,7} objects");

Console.WriteLine();
Console.WriteLine("Declared types (Static is placed as-is; the rest are placed as scenery without behaviour):");

foreach (var (type, count) in declaredTypes.OrderByDescending(t => t.Value).Take(15))
{
    Console.WriteLine($"  {type,-28} {count,6}");
}

Console.WriteLine($"  ... {declaredTypes.Count} distinct types in total");

Console.WriteLine();
Console.WriteLine("Attributes NOT consumed by this conversion -- the behaviour pass needs these:");

if (unconsumed.Count == 0)
{
    Console.WriteLine("  (none)");
}

foreach (var (key, count) in unconsumed.OrderByDescending(a => a.Value))
{
    Console.WriteLine($"  {key,-28} {count,6}");
}

return 0;

// Attributes are semicolon-separated key=value pairs inside one paren group:
//   (Spawn=BlackSolenMatriarch; Count=1; HomeRange=14)
static Dictionary<string, string> ParseAttributes(string tail)
{
    var attributes = new Dictionary<string, string>(StringComparer.Ordinal);

    if (string.IsNullOrWhiteSpace(tail))
    {
        return attributes;
    }

    foreach (var pair in tail.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
    {
        var split = pair.IndexOf('=');

        if (split > 0)
        {
            attributes[pair[..split].Trim()] = pair[(split + 1)..].Trim();
        }
    }

    return attributes;
}

// Hues appear as 0x849 and as plain decimal, depending on the file.
static int ParseNumber(string text)
{
    text = text.Trim();

    if (text.StartsWith("0x", StringComparison.OrdinalIgnoreCase) &&
        int.TryParse(text[2..], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var hex))
    {
        return hex;
    }

    return int.TryParse(text, CultureInfo.InvariantCulture, out var value) ? value : 0;
}

internal sealed record Group(string Type, int ItemId, int Hue, List<(int X, int Y, int Z)> Points);
