#!/usr/bin/env python3
from __future__ import annotations

import argparse
import concurrent.futures
import html
import re
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parent.parent
PACKETS_ROOT = REPO_ROOT / "src" / "Moongate.Network.Packets"
DOCS_ROOT = REPO_ROOT / "docs"
PACKET_REFERENCE_ROOT = DOCS_ROOT / "articles" / "networking" / "packet-reference"
POL_INDEX_URL = "https://docs.polserver.com/packets/"
POL_PACKET_URL_TEMPLATE = "https://docs.polserver.com/packets/index.php?Packet=0x{opcode:02X}"
TIMEOUT_SECONDS = 30
FETCH_RETRY_COUNT = 3

GENERATED_BANNER = """<!--
This file is generated by scripts/generate_packet_reference.py.
Do not edit manually. Re-run the generator instead.
-->
"""


@dataclass(slots=True)
class MoongatePacketClass:
    class_name: str
    namespace: str
    direction: str
    relative_path: str
    sizing: str
    length: str
    description: str
    registry_registered: bool


@dataclass(slots=True)
class PolPacketInfo:
    opcode: int
    name: str
    sent_by: str
    size: str
    packet_build: str
    subcommand_build: str
    notes: str
    last_modified: str
    modified_by: str
    source_url: str


@dataclass(slots=True)
class PacketReference:
    opcode: int
    moongate_classes: list[MoongatePacketClass] = field(default_factory=list)
    pol_info: PolPacketInfo | None = None

    @property
    def page_name(self) -> str:
        return f"0x{self.opcode:02X}.md"

    @property
    def display_opcode(self) -> str:
        return f"0x{self.opcode:02X}"

    @property
    def status(self) -> str:
        return "implemented" if self.moongate_classes else "placeholder"

    @property
    def packet_name(self) -> str:
        if self.pol_info and self.pol_info.name:
            return self.pol_info.name

        if self.moongate_classes:
            if len(self.moongate_classes) == 1:
                return self.moongate_classes[0].description

            return " / ".join(dict.fromkeys(packet.description for packet in self.moongate_classes))

        return f"Opcode {self.display_opcode}"

    @property
    def directions(self) -> str:
        if self.pol_info and self.pol_info.sent_by and self.pol_info.sent_by != "Unknown":
            return self.pol_info.sent_by

        if not self.moongate_classes:
            return "Unknown"

        directions = sorted({packet.direction for packet in self.moongate_classes})

        if directions == ["Incoming", "Outgoing"]:
            return "Both"

        if len(directions) == 1:
            return "Client" if directions[0] == "Incoming" else "Server"

        return ", ".join(directions)

    @property
    def length(self) -> str:
        if self.pol_info and self.pol_info.size and self.pol_info.size != "Unknown":
            return self.pol_info.size

        if not self.moongate_classes:
            return "Unknown"

        lengths = []

        for packet in self.moongate_classes:
            value = packet.length

            if packet.sizing.lower() == "variable":
                value = "Variable"

            lengths.append(value)

        return ", ".join(dict.fromkeys(lengths))


def fetch_text(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "MoongatePacketReferenceGenerator/1.0"})
    last_error: Exception | None = None

    for attempt in range(FETCH_RETRY_COUNT):
        try:
            with urllib.request.urlopen(request, timeout=TIMEOUT_SECONDS) as response:
                return response.read().decode("utf-8", "ignore")
        except (urllib.error.URLError, TimeoutError) as error:
            last_error = error

            if attempt < FETCH_RETRY_COUNT - 1:
                time.sleep(0.25 * (attempt + 1))

    assert last_error is not None
    raise last_error


def clean_html_fragment(fragment: str) -> str:
    text = re.sub(r"(?i)<br\s*/?>", "\n", fragment)
    text = re.sub(r"(?i)</p>", "\n\n", text)
    text = re.sub(r"(?i)</li>", "\n", text)
    text = re.sub(r"(?i)<li[^>]*>", "- ", text)
    text = re.sub(r"(?i)</?(ul|ol)[^>]*>", "\n", text)
    text = re.sub(r"(?i)</?(b|strong|u|i|em)[^>]*>", "", text)
    text = re.sub(r"(?i)<input[^>]*>", "", text)
    text = re.sub(r"<[^>]+>", "", text)
    text = html.unescape(text)
    text = text.replace("\r", "")
    text = re.sub(r"\n{3,}", "\n\n", text)

    lines = [line.rstrip() for line in text.splitlines()]

    return normalize_markdownish_text("\n".join(line for line in lines).strip())


def normalize_markdownish_text(text: str) -> str:
    text = re.sub(r"[ \t]+\n", "\n", text)
    lines = [line.strip() for line in text.splitlines()]
    normalized: list[str] = []
    index = 0

    while index < len(lines):
        line = lines[index]

        if not line:
            if normalized and normalized[-1] != "":
                normalized.append("")
            index += 1
            continue

        if re.fullmatch(r"[A-Za-z0-9 _/+()-]+:", line):
            heading = line.removesuffix(":")
            index += 1
            collected_items = 0
            keyed_items: list[tuple[str, str]] = []
            bullet_items: list[str] = []

            while index < len(lines):
                child = lines[index].strip()

                if not child:
                    index += 1
                    continue

                if re.fullmatch(r"[A-Za-z0-9 _/+()-]+:", child):
                    break

                if collected_items > 0 and (child.startswith("Sex:") or child.startswith("Since client")):
                    break

                if collected_items > 0 and ":" not in child:
                    break

                entry = child.removesuffix(",")
                pair = split_key_value(entry)

                if pair is not None:
                    keyed_items.append(pair)
                else:
                    bullet_items.append(entry)

                collected_items += 1
                index += 1

            normalized.append(f"**{heading}:**")

            if keyed_items and not bullet_items:
                normalized.extend(render_key_value_table("Name", "Value", keyed_items))
            else:
                for key, value in keyed_items:
                    bullet_items.append(f"{key}: {value}")

                for bullet in bullet_items:
                    normalized.append(f"- {bullet}")

            continue

        if line.startswith("Note:"):
            normalized.append(f"**Note:** {line[len('Note:'):].strip()}")
            index += 1
            continue

        if line.startswith("Since client "):
            normalized.append(f"### {line}")
            index += 1
            continue

        if line.startswith("Sex:"):
            normalized.append("**Sex:**")
            normalized.extend(render_enum_table(line[len("Sex:"):].strip()))
            index += 1
            continue

        if re.match(r"^[A-Za-z][A-Za-z0-9 _/+()-]+:", line):
            label, value = line.split(":", 1)
            normalized.append(f"**{label.strip()}:** {value.strip()}")
            index += 1
            continue

        normalized.append(line)
        index += 1

    result = "\n".join(normalized)
    result = re.sub(r"\n{3,}", "\n\n", result)

    return result.strip()


def split_key_value(line: str) -> tuple[str, str] | None:
    if ":" not in line:
        return None

    key, value = line.split(":", 1)
    key = key.strip()
    value = value.strip()

    if not key or not value:
        return None

    return key, value


def render_key_value_table(left_header: str, right_header: str, rows: list[tuple[str, str]]) -> list[str]:
    table = [
        f"| {left_header} | {right_header} |",
        "| --- | --- |"
    ]
    table.extend(f"| `{key}` | `{value}` |" for key, value in rows)

    return table


def render_enum_table(value: str) -> list[str]:
    parts = [part.strip() for part in value.split(",") if part.strip()]
    rows: list[tuple[str, str]] = []

    for part in parts:
        if "=" not in part:
            return [f"- {value}"]

        enum_value, meaning = part.split("=", 1)
        rows.append((enum_value.strip(), meaning.strip()))

    return render_key_value_table("Value", "Meaning", rows)


def format_protocol_section(text: str) -> str:
    stripped = text.strip()

    if stripped in {"N/A", "No POL packet build information found.", "No POL subcommand information found."}:
        return stripped

    lines = [line.strip() for line in stripped.splitlines()]
    output: list[str] = []
    table_rows: list[tuple[str, str]] = []

    def flush_table() -> None:
        nonlocal table_rows
        if not table_rows:
            return
        if output and output[-1] != "":
            output.append("")
        output.extend(render_key_value_table("Type", "Field", table_rows))
        table_rows = []

    for index, line in enumerate(lines):
        if not line:
            next_non_empty = ""

            for candidate in lines[index + 1:]:
                if candidate.strip():
                    next_non_empty = candidate.strip().removeprefix("- ").strip()
                    break

            if table_rows and re.match(r"^(BYTE(?:\[[^\]]+\])?)\s+(.+)$", next_non_empty):
                continue

            flush_table()
            if output and output[-1] != "":
                output.append("")
            continue

        normalized_line = line.removeprefix("- ").strip()
        byte_match = re.match(r"^(BYTE(?:\[[^\]]+\])?)\s+(.+)$", normalized_line)

        if byte_match:
            table_rows.append((byte_match.group(1), byte_match.group(2)))
            continue

        flush_table()

        if line.startswith("If (") or line.startswith("Subcommand ") or line.startswith("Subsubcommand "):
            output.append(f"**{line}**")
            continue

        if line.startswith("----"):
            output.append(f"**{line}**")
            continue

        output.append(line)

    flush_table()

    result = "\n".join(output)
    result = re.sub(r"\n{3,}", "\n\n", result)

    return result.strip()


def extract_section(page_html: str, heading: str, next_headings: Iterable[str]) -> str:
    heading_pattern = re.escape(heading)
    start_match = re.search(rf"<B>{heading_pattern}</B><BR\s*/?>", page_html, re.IGNORECASE | re.DOTALL)

    if not start_match:
        return ""

    start_index = start_match.end()
    remaining = page_html[start_index:]

    if next_headings:
        next_patterns = [rf"<B>{re.escape(next_heading)}</B>" for next_heading in next_headings]
        next_match = re.search("|".join(next_patterns), remaining, re.IGNORECASE | re.DOTALL)
        section_html = remaining[: next_match.start()] if next_match else remaining
    else:
        paragraph_end = re.search(r"</P>", remaining, re.IGNORECASE | re.DOTALL)
        section_html = remaining[: paragraph_end.start()] if paragraph_end else remaining

    return clean_html_fragment(section_html)


def parse_pol_index(index_html: str) -> dict[int, str]:
    packets: dict[int, str] = {}

    for match in re.finditer(
        r'href="/packets/index\.php\?Packet=(0x[0-9A-Fa-f]{2})"[^>]*>\[(0x[0-9A-Fa-f]{2})\]\s*([^<]+)</a>',
        index_html,
        re.IGNORECASE
    ):
        opcode = int(match.group(2), 16)
        name = match.group(3)
        packets[opcode] = name.strip()

    return packets


def parse_pol_packet_page(opcode: int, page_html: str, fallback_name: str) -> PolPacketInfo:
    packet_name = fallback_name
    last_modified = ""
    modified_by = ""
    sent_by = ""
    size = ""

    header_match = re.search(
        r"<b>Packet Name:\s*</b>(.*?)<BR\s*/?>\s*Last Modified:\s*(.*?)<BR\s*/?>\s*Modified By:\s*(.*?)<BR\s*/?>",
        page_html,
        re.IGNORECASE | re.DOTALL
    )

    if header_match:
        packet_name = clean_html_fragment(header_match.group(1))
        last_modified = clean_html_fragment(header_match.group(2))
        modified_by = clean_html_fragment(header_match.group(3))

    meta_match = re.search(
        r"</b>Sent By:\s*(.*?)<BR\s*/?>\s*Size:\s*(.*?)<BR\s*/?>",
        page_html,
        re.IGNORECASE | re.DOTALL
    )

    if meta_match:
        sent_by = clean_html_fragment(meta_match.group(1))
        size = clean_html_fragment(meta_match.group(2))

    packet_build = extract_section(page_html, "Packet Build", ["Subcommand Build", "Notes"])
    subcommand_build = extract_section(page_html, "Subcommand Build", ["Notes"])
    notes = extract_section(page_html, "Notes", [])

    return PolPacketInfo(
        opcode=opcode,
        name=packet_name or fallback_name,
        sent_by=sent_by or "Unknown",
        size=size or "Unknown",
        packet_build=packet_build or "N/A",
        subcommand_build=subcommand_build or "N/A",
        notes=notes or "N/A",
        last_modified=last_modified or "Unknown",
        modified_by=modified_by or "Unknown",
        source_url=POL_PACKET_URL_TEMPLATE.format(opcode=opcode)
    )


def parse_moongate_packets() -> dict[int, list[MoongatePacketClass]]:
    packets: dict[int, list[MoongatePacketClass]] = {}

    for path in sorted(PACKETS_ROOT.rglob("*.cs")):
        relative_path = path.relative_to(REPO_ROOT).as_posix()

        if not ("/Incoming/" in relative_path or "/Outgoing/" in relative_path):
            continue

        content = path.read_text(encoding="utf-8")
        namespace_match = re.search(r"namespace\s+([A-Za-z0-9_.]+);", content)
        class_match = re.search(r"\b(class|record)\s+([A-Za-z0-9_]+Packet)\b", content)

        if not namespace_match or not class_match:
            continue

        namespace = namespace_match.group(1)
        class_name = class_match.group(2)
        direction = "Incoming" if ".Incoming." in namespace else "Outgoing"

        attribute_match = re.search(
            r"\[PacketHandler\(\s*(0x[0-9A-Fa-f]{2})\s*,\s*PacketSizing\.(Fixed|Variable)(?:\s*,[^\]]*)?\)\]",
            content
        )
        length_match = re.search(r"Length\s*=\s*(-?\d+)", content)
        description_match = re.search(r'Description\s*=\s*"([^"]+)"', content)

        opcode = None
        sizing = ""
        length = ""
        registry_registered = False

        if attribute_match:
            opcode = int(attribute_match.group(1), 16)
            sizing = attribute_match.group(2)
            length = length_match.group(1) if length_match else ("-1" if sizing == "Variable" else "")
            registry_registered = True
        else:
            base_match = re.search(r":\s*base\(\s*(0x[0-9A-Fa-f]{2})\s*,\s*(-?\d+)\s*\)", content)
            if base_match:
                opcode = int(base_match.group(1), 16)
                raw_length = base_match.group(2)
                sizing = "Variable" if raw_length == "-1" else "Fixed"
                length = raw_length

        if opcode is None:
            summary_match = re.search(r"///\s*.*?\((0x[0-9A-Fa-f]{2})\)", content)
            if summary_match:
                opcode = int(summary_match.group(1), 16)
                sizing = "Inherited"
                length = "Inherited"

        if opcode is None:
            continue

        description = description_match.group(1) if description_match else class_name.removesuffix("Packet")
        packet_class = MoongatePacketClass(
            class_name=class_name,
            namespace=namespace,
            direction=direction,
            relative_path=relative_path,
            sizing=sizing or "Unknown",
            length=length or "Unknown",
            description=description,
            registry_registered=registry_registered
        )
        packets.setdefault(opcode, []).append(packet_class)

    for classes in packets.values():
        classes.sort(key=lambda item: (item.direction, item.class_name))

    return packets


def build_packet_references() -> list[PacketReference]:
    moongate_packets = parse_moongate_packets()
    pol_index_html = fetch_text(POL_INDEX_URL)
    pol_packets = parse_pol_index(pol_index_html)
    all_opcodes = sorted(set(moongate_packets) | set(pol_packets))
    references = [PacketReference(opcode=opcode, moongate_classes=list(moongate_packets.get(opcode, []))) for opcode in all_opcodes]

    def load_pol_info(reference: PacketReference) -> PacketReference:
        try:
            page_html = fetch_text(POL_PACKET_URL_TEMPLATE.format(opcode=reference.opcode))
            reference.pol_info = parse_pol_packet_page(
                reference.opcode,
                page_html,
                pol_packets.get(reference.opcode, reference.packet_name)
            )
        except urllib.error.URLError:
            reference.pol_info = None

        return reference

    with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:
        references = list(executor.map(load_pol_info, references))

    return references


def render_packet_page(reference: PacketReference) -> str:
    moongate_classes = "\n".join(
        f"- `{packet.class_name}` ({packet.direction}, {packet.sizing}, length `{packet.length}`)"
        f" from `{packet.relative_path}`"
        for packet in reference.moongate_classes
    ) or "- None yet"

    status_lines = [
        f"- Status: `{reference.status}`",
        f"- Direction: `{reference.directions}`",
        f"- Length: `{reference.length}`"
    ]

    if reference.pol_info:
        status_lines.append(f"- POL reference: <{reference.pol_info.source_url}>")
        status_lines.append(f"- Last modified in POL docs: `{reference.pol_info.last_modified}` by `{reference.pol_info.modified_by}`")

    current_behavior = (
        "Moongate currently has packet classes for this opcode."
        if reference.moongate_classes
        else "Moongate does not currently implement this opcode. This page is a placeholder generated from the POL catalog."
    )

    packet_build = reference.pol_info.packet_build if reference.pol_info else "No POL packet build information found."
    subcommand_build = reference.pol_info.subcommand_build if reference.pol_info else "No POL subcommand information found."
    notes = reference.pol_info.notes if reference.pol_info else "No POL notes found."
    formatted_packet_build = format_protocol_section(packet_build)
    formatted_subcommand_build = format_protocol_section(subcommand_build)

    return (
        GENERATED_BANNER
        + f"# {reference.packet_name} ({reference.display_opcode})\n\n"
        + "\n".join(status_lines)
        + "\n\n## Moongate Packet Classes\n\n"
        + moongate_classes
        + "\n\n## Current Moongate Behavior\n\n"
        + current_behavior
        + "\n\n## Packet Build\n\n"
        + formatted_packet_build
        + "\n\n## Subcommand Build\n\n"
        + formatted_subcommand_build
        + "\n\n## Notes\n\n"
        + notes
        + "\n"
    )


def render_index(references: list[PacketReference]) -> str:
    lines = [
        GENERATED_BANNER.rstrip(),
        "# Packet Reference",
        "",
        "Static packet reference generated from Moongate packet classes plus POL packet documentation.",
        "",
        f"Generated packet pages: `{len(references)}`",
        "",
        "| Opcode | Name | Status | Direction | Length | Moongate Classes | Page |",
        "| --- | --- | --- | --- | --- | --- | --- |"
    ]

    for reference in references:
        moongate_class_names = ", ".join(packet.class_name for packet in reference.moongate_classes) or "None"
        lines.append(
            f"| `{reference.display_opcode}` | {reference.packet_name} | `{reference.status}` | {reference.directions} | {reference.length} | {moongate_class_names} | [{reference.page_name}]({reference.page_name}) |"
        )

    lines.extend(
        [
            "",
            "## Generation",
            "",
            "Re-generate these pages with:",
            "",
            "```bash",
            "python3 scripts/generate_packet_reference.py",
            "```"
        ]
    )

    return "\n".join(lines) + "\n"


def update_docs_index() -> None:
    path = DOCS_ROOT / "index.md"
    content = path.read_text(encoding="utf-8")
    needle = "- [Packet Handler Performance](articles/networking/packet-handler-performance.md)\n"
    replacement = (
        "- [Packet Handler Performance](articles/networking/packet-handler-performance.md)\n"
        "- [Packet Reference](articles/networking/packet-reference/index.md)\n"
    )

    if "- [Packet Reference](articles/networking/packet-reference/index.md)\n" in content:
        return

    path.write_text(content.replace(needle, replacement), encoding="utf-8")


def update_docs_toc() -> None:
    path = DOCS_ROOT / "toc.yml"
    content = path.read_text(encoding="utf-8")
    needle = "  - name: Packet Handler Performance\n    href: articles/networking/packet-handler-performance.md\n"
    replacement = (
        "  - name: Packet Handler Performance\n"
        "    href: articles/networking/packet-handler-performance.md\n"
        "  - name: Packet Reference\n"
        "    href: articles/networking/packet-reference/index.md\n"
    )

    if "  - name: Packet Reference\n    href: articles/networking/packet-reference/index.md\n" in content:
        return

    path.write_text(content.replace(needle, replacement), encoding="utf-8")


def write_outputs(references: list[PacketReference]) -> None:
    PACKET_REFERENCE_ROOT.mkdir(parents=True, exist_ok=True)
    (PACKET_REFERENCE_ROOT / "index.md").write_text(render_index(references), encoding="utf-8")

    for reference in references:
        (PACKET_REFERENCE_ROOT / reference.page_name).write_text(
            render_packet_page(reference),
            encoding="utf-8"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate static packet reference docs from Moongate and POL.")
    parser.parse_args()

    references = build_packet_references()
    write_outputs(references)
    update_docs_index()
    update_docs_toc()
    print(f"Generated {len(references)} packet reference pages in {PACKET_REFERENCE_ROOT.relative_to(REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
