[[item]]
id = "0x1453"
item_id = 5203
rarity = "common"
hue = 0

[[item]]
id = "0x1454"
item_id = 5204
rarity = "common"
hue = 0

[[item]]
id = "0x1455"
item_id = 5205
rarity = "common"
hue = 0

[[item]]
id = "0x1456"
item_id = 5206
rarity = "common"
hue = 0

[[item]]
id = "0x1457"
item_id = 5207
rarity = "common"
hue = 0
