[[item]]
id = "0x3163"
item_id = 12643
rarity = "common"
hue = 0

[[item]]
id = "0x315e"
item_id = 12638
rarity = "common"
hue = 0

[[item]]
id = "0x3164"
item_id = 12644
rarity = "common"
hue = 0

[[item]]
id = "0x3161"
item_id = 12641
rarity = "common"
hue = 0

[[item]]
id = "0x3162"
item_id = 12642
rarity = "common"
hue = 0

[[item]]
id = "0x3160"
item_id = 12640
rarity = "common"
hue = 0

[[item]]
id = "0x3168"
item_id = 12648
rarity = "common"
hue = 0

[[item]]
id = "0x3169"
item_id = 12649
rarity = "common"
hue = 0

[[item]]
id = "0x316a"
item_id = 12650
rarity = "common"
hue = 0
