[[item]]
id = "0x1026_chisels"
base_id = "base_item"
item_id = 4134
name = "chisels"
rarity = "common"
weight = 1.0
buy_price = 14
sell_price = 7
decays = true
hue = 0

[[item]]
id = "0x1027_chisels"
base_id = "base_item"
item_id = 4135
name = "chisels"
rarity = "common"
weight = 1.0
buy_price = 14
sell_price = 7
decays = true
hue = 0

[[item]]
id = "0x1028_dovetail_saw"
base_id = "base_item"
item_id = 4136
name = "dovetail saw"
rarity = "common"
weight = 1.0
buy_price = 14
sell_price = 7
decays = true
hue = 0

[[item]]
id = "0x1029_dovetail_saw"
base_id = "base_item"
item_id = 4137
name = "dovetail saw"
rarity = "common"
weight = 1.0
buy_price = 14
sell_price = 7
decays = true
hue = 0

[[item]]
id = "0x102a_hammer"
base_id = "base_item"
item_id = 4138
name = "hammer"
rarity = "common"
weight = 2.0
buy_price = 28
sell_price = 14
decays = true
hue = 0

[[item]]
id = "0x102b_hammer"
base_id = "base_item"
item_id = 4139
name = "hammer"
rarity = "common"
weight = 2.0
buy_price = 28
sell_price = 14
decays = true
hue = 0

[[item]]
id = "0x102c_moulding_plane"
base_id = "base_item"
item_id = 4140
name = "moulding plane"
rarity = "common"
weight = 2.0
buy_price = 12
sell_price = 6
decays = true
hue = 0

[[item]]
id = "0x102d_moulding_plane"
base_id = "base_item"
item_id = 4141
name = "moulding plane"
rarity = "common"
weight = 2.0
buy_price = 12
sell_price = 6
decays = true
hue = 0

[[item]]
id = "0x102e_nails"
base_id = "base_item"
item_id = 4142
name = "nails"
rarity = "common"
weight = 2.0
buy_price = 2
sell_price = 1
decays = true
hue = 0

[[item]]
id = "0x102f_nails"
base_id = "base_item"
item_id = 4143
name = "nails"
rarity = "common"
weight = 2.0
buy_price = 2
sell_price = 1
decays = true
hue = 0

[[item]]
id = "0x1030_jointing_plane"
base_id = "base_item"
item_id = 4144
name = "jointing plane"
rarity = "common"
weight = 1.0
buy_price = 12
sell_price = 6
decays = true
hue = 0

[[item]]
id = "0x1031_jointing_plane"
base_id = "base_item"
item_id = 4145
name = "jointing plane"
rarity = "common"
weight = 1.0
buy_price = 12
sell_price = 6
decays = true
hue = 0

[[item]]
id = "0x1032_smoothing_plane"
base_id = "base_item"
item_id = 4146
name = "smoothing plane"
rarity = "common"
weight = 1.0
buy_price = 12
sell_price = 6
decays = true
hue = 0

[[item]]
id = "0x1033_smoothing_plane"
base_id = "base_item"
item_id = 4147
name = "smoothing plane"
rarity = "common"
weight = 1.0
buy_price = 12
sell_price = 6
decays = true
hue = 0

[[item]]
id = "0x1034_saw"
base_id = "base_item"
item_id = 4148
name = "saw"
rarity = "common"
weight = 2.0
buy_price = 18
sell_price = 9
decays = true
hue = 0

[[item]]
id = "0x1035_saw"
base_id = "base_item"
item_id = 4149
name = "saw"
rarity = "common"
weight = 2.0
buy_price = 18
sell_price = 9
decays = true
hue = 0

[[item]]
id = "0x10e4_draw_knife"
base_id = "base_item"
item_id = 4324
name = "draw knife"
rarity = "common"
weight = 1.0
buy_price = 14
sell_price = 7
decays = true
hue = 0

[[item]]
id = "0x10e5_froe"
base_id = "base_item"
item_id = 4325
name = "froe"
rarity = "common"
weight = 1.0
buy_price = 12
sell_price = 6
decays = true
hue = 0

[[item]]
id = "0x10e6_inshave"
base_id = "base_item"
item_id = 4326
name = "inshave"
rarity = "common"
weight = 1.0
buy_price = 12
sell_price = 6
decays = true
hue = 0

[[item]]
id = "0x10e7_scorp"
base_id = "base_item"
item_id = 4327
name = "scorp"
rarity = "common"
weight = 1.0
buy_price = 12
sell_price = 6
decays = true
hue = 0
