[[item]]
id = "0x0e20_bloody_bandage"
base_id = "base_item"
item_id = 3616
name = "bloody bandage"
rarity = "common"
weight = 1.0
stackable = true
decays = true
hue = 0

[[item]]
id = "0x0e21_clean_bandage"
base_id = "base_item"
item_id = 3617
name = "clean bandage"
rarity = "common"
weight = 1.0
stackable = true
buy_price = 6
sell_price = 3
decays = true
hue = 0

[[item]]
id = "0x0e22_bloody_bandage"
base_id = "base_item"
item_id = 3618
name = "bloody bandage"
rarity = "common"
weight = 1.0
stackable = true
decays = true
hue = 0

[[item]]
id = "0x0ee9_clean_bandage"
base_id = "base_item"
item_id = 3817
name = "clean bandage"
rarity = "common"
weight = 1.0
stackable = true
buy_price = 6
sell_price = 3
decays = true
hue = 0
