[[item]]
id = "0x0f62_aos"
base_id = "base_spear"
item_id = 0
rarity = "common"
weight = 7.0
buy_price = 38
sell_price = 36
hue = 0

[[item]]
id = "tribalspear_aos"
base_id = "base_spear"
item_id = 0
rarity = "common"
weight = 7.0
buy_price = 38
sell_price = 36
hue = 0

[[item]]
id = "0x1400_aos"
base_id = "base_kryss"
item_id = 0
rarity = "common"
weight = 1.0
buy_price = 42
sell_price = 21
hue = 0

[[item]]
id = "0x1402_aos"
base_id = "base_short_spear"
item_id = 0
rarity = "common"
weight = 4.0
buy_price = 32
sell_price = 16
hue = 0

[[item]]
id = "0x1404_aos"
base_id = "base_war_fork"
item_id = 0
rarity = "common"
weight = 9.0
buy_price = 32
sell_price = 17
hue = 0

[[item]]
id = "0x0e87_aos"
base_id = "base_pitchfork"
item_id = 0
rarity = "common"
weight = 10.0
buy_price = 25
sell_price = 12
hue = 0

[[item]]
id = "0x26be_aos"
base_id = "base_pike"
item_id = 0
rarity = "common"
weight = 8.0
buy_price = 53
sell_price = 27
hue = 0

[[item]]
id = "0x26c0_aos"
base_id = "base_lance"
item_id = 0
rarity = "common"
weight = 12.0
buy_price = 46
sell_price = 23
hue = 0

[[item]]
id = "0x27a7_aos"
base_id = "base_lajatang"
item_id = 0
rarity = "common"
weight = 12.0
buy_price = 145
sell_price = 73
hue = 0

[[item]]
id = "0x27ab_aos"
base_id = "base_tekagi"
item_id = 0
rarity = "common"
weight = 5.0
buy_price = 74
sell_price = 37
hue = 0

[[item]]
id = "0x27af_aos"
base_id = "base_sai"
item_id = 0
rarity = "common"
weight = 7.0
buy_price = 75
sell_price = 38
hue = 0

[[item]]
id = "0x2d23_aos"
base_id = "base_war_cleaver"
item_id = 0
rarity = "common"
weight = 5.0
buy_price = 39
sell_price = 20
hue = 0

[[item]]
id = "0x2d20_aos"
base_id = "base_elven_spellblade"
item_id = 0
rarity = "common"
weight = 5.0
buy_price = 73
sell_price = 37
hue = 0

[[item]]
id = "0x48be_aos"
base_id = "base_gargish_war_fork"
item_id = 0
rarity = "common"
weight = 9.0
buy_price = 32
sell_price = 17
hue = 0

[[item]]
id = "0x0907_aos"
base_id = "base_shortblade"
item_id = 0
rarity = "common"
weight = 9.0
buy_price = 45
sell_price = 23
hue = 0

[[item]]
id = "0x08fe_aos"
base_id = "base_bloodblade"
item_id = 0
rarity = "common"
weight = 4.0
buy_price = 37
sell_price = 19
hue = 0

[[item]]
id = "0x48bc_aos"
base_id = "base_gargish_kryss"
item_id = 0
rarity = "common"
weight = 1.0
buy_price = 42
sell_price = 21
hue = 0

[[item]]
id = "0x48ca_aos"
base_id = "base_gargish_lance"
item_id = 0
rarity = "common"
weight = 12.0
buy_price = 49
sell_price = 25
hue = 0

[[item]]
id = "0x48c8_aos"
base_id = "base_gargish_pike"
item_id = 0
rarity = "common"
weight = 8.0
buy_price = 57
sell_price = 29
hue = 0

[[item]]
id = "0x0904_aos"
base_id = "base_dual_pointed_spear"
item_id = 0
rarity = "common"
weight = 7.0
buy_price = 70
sell_price = 35
hue = 0

[[item]]
id = "0x48ce_aos"
base_id = "base_gargish_tekagi"
item_id = 0
rarity = "common"
weight = 5.0
buy_price = 80
sell_price = 40
hue = 0

[[item]]
id = "0xa28a_aos"
base_id = "base_spiked_whip"
item_id = 0
rarity = "common"
weight = 5.0
buy_price = 25
sell_price = 13
hue = 0
