[[item]]
id = "0x090a_aos"
base_id = "base_soul_glaive"
item_id = 0
rarity = "common"
weight = 8.0
damage_min = 17
damage_max = 19
speed = 27
strength_required = 60
max_hits = 65
buy_price = 69
sell_price = 32

[[item]]
id = "0x08ff_aos"
base_id = "base_boomerang"
item_id = 0
rarity = "common"
weight = 4.0
damage_min = 12
damage_max = 14
speed = 40
strength_required = 25
max_hits = 60
buy_price = 29
sell_price = 13

[[item]]
id = "0x0901_aos"
base_id = "base_cyclone"
item_id = 0
rarity = "common"
weight = 6.0
damage_min = 14
damage_max = 16
speed = 33
strength_required = 40
max_hits = 60
buy_price = 48
sell_price = 22
