[[item]]
id = "stoneandplastermini"
item_id = 5360
name = "Mini House: Stone and Plaster"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "fieldstonemini"
item_id = 5360
name = "Mini House: Field Stone"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "smallbrickmini"
item_id = 5360
name = "Mini House: Small Brick"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "woodenmini"
item_id = 5360
name = "Mini House: Wooden"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "woodandplastermini"
item_id = 5360
name = "Mini House: Wood and Plaster"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "thatchedroofcottage"
item_id = 5360
name = "Mini House: Thatched-Roof Cottage"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "brickmini"
item_id = 5360
name = "Mini House: Brick"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "twostorywoodandplastermini"
item_id = 5360
name = "Mini House: Two-Story Wood and Plaster"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "malasmountainpassmini"
item_id = 5360
name = "Mini House: Malas Mountain Pass"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "churchatnightmini"
item_id = 5360
name = "Mini House: Church at Night"
rarity = "common"
movable = false
hue = 0
