[[item]]
id = "townstonedeed"
item_id = 5360
name = "Townstone deed"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "guildstonedeed"
item_id = 5360
name = "Guildstone deed"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "playervendordeed"
item_id = 5360
name = "Player vendor deed"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "hairrestyledeed"
item_id = 5360
name = "a coupon for a free hair restyling"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "smallbod_oldid"
item_id = 5359
rarity = "common"
movable = false
hue = 0

[[item]]
id = "smallbod_blacksmith"
base_id = "base_item"
item_id = 8792
name = "a bulk order deed"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "smallbod_tailor"
base_id = "base_item"
item_id = 8792
name = "a bulk order deed"
rarity = "common"
movable = false
hue = 0
