[[item]]
id = "tribalpaint"
base_id = "base_item"
item_id = 2540
name = "savage kin paint"
rarity = "common"
weight = 2.0
stackable = true
hue = 2101

[[item]]
id = "haironlydye"
base_id = "base_item"
item_id = 3839
name = "a hair-only dye"
rarity = "common"
weight = 1.0
buy_price = 30000
sell_price = 15000
hue = 0

[[item]]
id = "beardonlydye"
base_id = "base_item"
item_id = 3839
name = "a beard-only dye"
rarity = "common"
weight = 1.0
buy_price = 30000
sell_price = 15000
hue = 0

[[item]]
id = "hairdye"
base_id = "base_item"
item_id = 3839
name = "a hair dye"
rarity = "common"
weight = 1.0
buy_price = 50
sell_price = 25
hue = 0

[[item]]
id = "specialhaironlydye"
base_id = "base_item"
item_id = 3839
name = "a special hair-only dye"
rarity = "common"
weight = 1.0
buy_price = 30000
sell_price = 15000
hue = 0

[[item]]
id = "specialbeardonlydye"
base_id = "base_item"
item_id = 3839
name = "a special beard-only dye"
rarity = "common"
weight = 1.0
buy_price = 30000
sell_price = 15000
hue = 0

[[item]]
id = "specialhairdye"
base_id = "base_item"
item_id = 3839
name = "a special hair dye"
rarity = "common"
weight = 1.0
buy_price = 50
sell_price = 25
hue = 0

[[item]]
id = "manadraught"
base_id = "base_item"
item_id = 4091
name = "mana draught"
rarity = "common"
weight = 1.0
decays = true
hue = 1162
[item.tags]
consumableID = "1"

[[item]]
id = "seedoflife"
base_id = "base_item"
item_id = 5927
name = "seed of life"
rarity = "common"
weight = 1.0
stackable = true
decays = true
hue = 1169
[item.tags]
consumableID = "2"

[[item]]
id = "balmofprotection"
base_id = "base_item"
item_id = 7192
name = "balm of protection"
rarity = "common"
weight = 1.0
decays = true
hue = 1177
[item.tags]
consumableID = "3"

[[item]]
id = "balmofstrength"
base_id = "base_item"
item_id = 3835
name = "balm of strength"
rarity = "common"
weight = 1.0
decays = true
hue = 0
[item.tags]
consumableID = "4"

[[item]]
id = "balmofswiftness"
base_id = "base_item"
item_id = 6216
name = "balm of swiftness"
rarity = "common"
weight = 1.0
decays = true
hue = 0
[item.tags]
consumableID = "5"

[[item]]
id = "balmofwisdom"
base_id = "base_item"
item_id = 6215
name = "balm of wisdom"
rarity = "common"
weight = 1.0
decays = true
hue = 0
[item.tags]
consumableID = "6"

[[item]]
id = "lifeshieldlotion"
base_id = "base_item"
item_id = 3836
name = "life shield lotion"
rarity = "common"
weight = 1.0
decays = true
hue = 0
[item.tags]
consumableID = "7"

[[item]]
id = "stoneskinlotion"
base_id = "base_item"
item_id = 3837
name = "stone skin lotion"
rarity = "common"
weight = 1.0
decays = true
hue = 0
[item.tags]
consumableID = "8"

[[item]]
id = "gemofsalvation"
base_id = "base_item"
item_id = 7955
name = "gem of salvation"
rarity = "common"
loot_type = "newbied"
hue = 286
[item.tags]
consumableID = "9"

[[item]]
id = "newplayerticket"
base_id = "base_item"
item_id = 5360
name = "new player ticket"
rarity = "common"
loot_type = "newbied"
hue = 0

[[item]]
id = "elixirofmetalconversion"
base_id = "base_item"
item_id = 3628
name = "Elixir of Metal Conversion"
rarity = "common"
amount = 1
stackable = true
decays = true
hue = 0
[item.tags]
typeID = "1"

[[item]]
id = "powderoftranslocation"
base_id = "base_item"
item_id = 9912
name = "powder of translocation"
rarity = "common"
weight = 0.01
amount = 1
stackable = true
hue = 2101

[[item]]
id = "zoogifungus"
base_id = "base_item"
item_id = 9911
name = "a zoogi fungus"
rarity = "common"
amount = 1
stackable = true
decays = true
hue = 0
