[[item]]
id = "0x0fa2_playing_cards"
base_id = "base_item"
item_id = 4002
name = "playing cards"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0fa3_playing_cards"
base_id = "base_item"
item_id = 4003
name = "playing cards"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0fad_backgammon_game"
base_id = "base_item"
item_id = 4013
name = "backgammon game"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x0fa6_a_checker_board"
base_id = "base_item"
item_id = 4006
name = "a checker board"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x0fa6_chess_a_chess_board"
base_id = "base_item"
item_id = 4006
name = "a chess board"
rarity = "common"
movable = true
hue = 0
max_weight = 1000

[[item]]
id = "0x0fa7_dice_and_cup"
base_id = "base_item"
item_id = 4007
name = "dice and Cup"
rarity = "common"
movable = true
hue = 0

[[item]]
id = "0x0e15_cards"
base_id = "base_item"
item_id = 3605
name = "cards"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0e16_cards"
base_id = "base_item"
item_id = 3606
name = "cards"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0e17_cards"
base_id = "base_item"
item_id = 3607
name = "cards"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0e18_cards"
base_id = "base_item"
item_id = 3608
name = "cards"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0e19_cards"
base_id = "base_item"
item_id = 3609
name = "cards"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0e1c_backgammon_board"
base_id = "base_item"
item_id = 3612
name = "backgammon board"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3584_white_checker"
base_id = "base_item"
item_id = 13700
name = "white checker"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x358b_black_checker"
base_id = "base_item"
item_id = 13707
name = "black checker"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3585_white_bishop"
base_id = "base_item"
item_id = 13701
name = "white bishop"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3586_white_rook"
base_id = "base_item"
item_id = 13702
name = "white rook"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3587_white_king"
base_id = "base_item"
item_id = 13703
name = "white king"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3588_white_knight"
base_id = "base_item"
item_id = 13704
name = "white knight"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3589_white_pawn"
base_id = "base_item"
item_id = 13705
name = "white pawn"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x358a_white_queen"
base_id = "base_item"
item_id = 13706
name = "white queen"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x358c_black_bishop"
base_id = "base_item"
item_id = 13708
name = "black bishop"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x358d_black_rook"
base_id = "base_item"
item_id = 13709
name = "black rook"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x358e_black_king"
base_id = "base_item"
item_id = 13710
name = "black king"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x358f_black_knight"
base_id = "base_item"
item_id = 13711
name = "black knight"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3590_black_pawn"
base_id = "base_item"
item_id = 13712
name = "black pawn"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x3591_black_queen"
base_id = "base_item"
item_id = 13713
name = "black queen"
rarity = "common"
movable = false
hue = 0
