[[item]]
id = "0x100e_copper_key"
base_id = "base_item"
item_id = 4110
name = "copper key"
rarity = "common"
weight = 1.0
buy_price = 2
sell_price = 1
decays = true
hue = 0

[[item]]
id = "0x100f_gold_key"
base_id = "base_item"
item_id = 4111
name = "gold key"
rarity = "common"
weight = 1.0
buy_price = 9
sell_price = 4
decays = true
hue = 0

[[item]]
id = "0x1010_iron_key"
base_id = "base_item"
item_id = 4112
name = "iron key"
rarity = "common"
weight = 1.0
buy_price = 9
sell_price = 4
decays = true
hue = 0

[[item]]
id = "0x1011_key_ring"
base_id = "base_item"
item_id = 4113
name = "key ring"
rarity = "common"
weight = 1.0
buy_price = 9
sell_price = 4
decays = true
hue = 0

[[item]]
id = "0x1012_magic_key"
base_id = "base_item"
item_id = 4114
name = "magic key"
rarity = "common"
weight = 1.0
buy_price = 9
sell_price = 4
decays = true
hue = 0

[[item]]
id = "0x1013_rusty_iron_key"
base_id = "base_item"
item_id = 4115
name = "rusty iron key"
rarity = "common"
weight = 1.0
buy_price = 9
sell_price = 4
decays = true
hue = 0
