[[item]]
id = "0x09f1_cut_of_raw_ribs"
item_id = 2545
name = "cut of raw ribs"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e15_raw_fish"
item_id = 7701
name = "raw fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e16_raw_fish"
item_id = 7702
name = "raw fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e17_raw_fish"
item_id = 7703
name = "raw fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e18_raw_fish"
item_id = 7704
name = "raw fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e19_fish_head"
item_id = 7705
name = "fish head"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e1b_fish_heads"
item_id = 7707
name = "fish heads"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1e1a_fish_head"
item_id = 7706
name = "fish head"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1609_raw_leg_of_lamb"
item_id = 5641
name = "raw leg of lamb"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1607_raw_chicken_leg"
item_id = 5639
name = "raw chicken leg"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1042_unbaked_pie"
item_id = 4162
name = "unbaked pie"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x097a_raw_fish_steak"
item_id = 2426
name = "raw fish steak"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09b9_raw_bird"
item_id = 2489
name = "raw bird"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09ba_raw_bird"
item_id = 2490
name = "raw bird"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09cc_fish"
item_id = 2508
name = "fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09cd_fish"
item_id = 2509
name = "fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09ce_fish"
item_id = 2510
name = "fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09cf_fish"
item_id = 2511
name = "fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0dd6_small_fish"
item_id = 3542
name = "small fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0dd7_small_fish"
item_id = 3543
name = "small fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0dd8_small_fish"
item_id = 3544
name = "small fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0dd9_small_fish"
item_id = 3545
name = "small fish"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1083_uncooked_pizza"
item_id = 4227
name = "uncooked pizza"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09b5_eggs"
item_id = 2485
name = "eggs"
rarity = "common"
movable = false
hue = 0
