[[item]]
id = "interiordecorator"
base_id = "base_item"
item_id = 4033
name = "an interior decorator"
rarity = "common"
weight = 1.0
buy_price = 5000
sell_price = 2500
decays = true
loot_type = "newbied"
hue = 0

[[item]]
id = "taxidermykit"
base_id = "base_item"
item_id = 7866
name = "a taxidermy kit"
rarity = "common"
weight = 1.0
buy_price = 90000
sell_price = 45000
decays = true
hue = 0
