[[item]]
id = "0x0fac_fire_pit"
base_id = "base_item"
item_id = 4012
name = "fire pit"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0f64_torch"
base_id = "base_item"
item_id = 3940
name = "torch"
rarity = "common"
weight = 1.0
layer = "two_handed"
buy_price = 7
sell_price = 3
decays = true
hue = 0
