[[item]]
id = "0x1f9e_pitcher_of_water"
item_id = 8094
name = "pitcher of water"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f9d_pitcher_of_water"
item_id = 8093
name = "pitcher of water"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f9c_pitcher_of_wine"
item_id = 8092
name = "pitcher of wine"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f9b_pitcher_of_wine"
item_id = 8091
name = "pitcher of wine"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f9a_pitcher_of_liquor"
item_id = 8090
name = "pitcher of liquor"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f99_pitcher_of_liquor"
item_id = 8089
name = "pitcher of liquor"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f98_pitcher_of_ale"
item_id = 8088
name = "pitcher of ale"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f97_pitcher_of_ale"
item_id = 8087
name = "pitcher of ale"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f96_pitcher_of_ale"
item_id = 8086
name = "pitcher of ale"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f95_pitcher_of_ale"
item_id = 8085
name = "pitcher of ale"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f94_glass_of_water"
item_id = 8084
name = "glass of water"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f93_glass_of_water"
item_id = 8083
name = "glass of water"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f92_glass_of_water"
item_id = 8082
name = "glass of water"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f91_glass_of_water"
item_id = 8081
name = "glass of water"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f90_glass_of_wine"
item_id = 8080
name = "glass of wine"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f8f_glass_of_wine"
item_id = 8079
name = "glass of wine"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f8e_glass_of_wine"
item_id = 8078
name = "glass of wine"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f8d_glass_of_wine"
item_id = 8077
name = "glass of wine"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f8c_glass_of_milk"
item_id = 8076
name = "glass of milk"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f8b_glass_of_milk"
item_id = 8075
name = "glass of milk"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f8a_glass_of_milk"
item_id = 8074
name = "glass of milk"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f89_glass_of_milk"
item_id = 8073
name = "glass of milk"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f88_glass_of_liquor"
item_id = 8072
name = "glass of liquor"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f87_glass_of_liquor"
item_id = 8071
name = "glass of liquor"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f86_glass_of_liquor"
item_id = 8070
name = "glass of liquor"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f85_glass_of_liquor"
item_id = 8069
name = "glass of liquor"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f80_glass_of_cider"
item_id = 8064
name = "glass of cider"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f7f_glass_of_cider"
item_id = 8063
name = "glass of cider"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f7e_glass_of_cider"
item_id = 8062
name = "glass of cider"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x1f7d_glass_of_cider"
item_id = 8061
name = "glass of cider"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x099b_bottle_of_liquor"
item_id = 2459
name = "bottle of liquor"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x099c_bottles_of_liquor"
item_id = 2460
name = "bottles of liquor"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x099d_bottles_of_liquor"
item_id = 2461
name = "bottles of liquor"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x099e_bottles_of_liquor"
item_id = 2462
name = "bottles of liquor"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x099f_bottle_of_ale"
item_id = 2463
name = "bottle of ale"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09a0_bottles_of_ale"
item_id = 2464
name = "bottles of ale"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09a1_bottles_of_ale"
item_id = 2465
name = "bottles of ale"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09a2_bottles_of_ale"
item_id = 2466
name = "bottles of ale"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09ad_pitcher_of_milk"
item_id = 2477
name = "pitcher of milk"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0ff8_pitcher_of_water"
item_id = 4088
name = "pitcher of water"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x0ff9_pitcher_of_water"
item_id = 4089
name = "pitcher of water"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09c7_bottle_of_wine"
item_id = 2503
name = "bottle of wine"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09c6_bottles_of_wine"
item_id = 2502
name = "bottles of wine"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09c5_bottles_of_wine"
item_id = 2501
name = "bottles of wine"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09c4_bottles_of_wine"
item_id = 2500
name = "bottles of wine"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09c8_jug_of_cider"
item_id = 2504
name = "jug of cider"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09ec_jar_of_honey"
item_id = 2540
name = "jar of honey"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09f0_pitcher_of_milk"
item_id = 2544
name = "pitcher of milk"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09ee_mug_of_ale"
item_id = 2542
name = "mug of ale"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x09ef_mug_of_ale"
item_id = 2543
name = "mug of ale"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x098d_jugs_of_cider"
item_id = 2445
name = "jugs of cider"
rarity = "common"
movable = false
hue = 0

[[item]]
id = "0x098e_jugs_of_cider"
item_id = 2446
name = "jugs of cider"
rarity = "common"
movable = false
hue = 0
