[[item]]
id = "0x09d0_apple"
base_id = "base_item"
item_id = 2512
name = "apple"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x09d1_grape_bunch"
base_id = "base_item"
item_id = 2513
name = "grape bunch"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x0d1a_grape_bunch"
base_id = "base_item"
item_id = 3354
name = "grape bunch"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x09d2_peach"
base_id = "base_item"
item_id = 2514
name = "peach"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x172c_peach"
base_id = "base_item"
item_id = 5932
name = "peach"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x0994_pear"
base_id = "base_item"
item_id = 2452
name = "pear"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x172d_pear"
base_id = "base_item"
item_id = 5933
name = "pear"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x172b_lemons"
base_id = "base_item"
item_id = 5931
name = "lemons"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x172a_lemon"
base_id = "base_item"
item_id = 5930
name = "lemon"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x1729_limes"
base_id = "base_item"
item_id = 5929
name = "limes"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x1728_lime"
base_id = "base_item"
item_id = 5928
name = "lime"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x1727_bunch_of_dates"
base_id = "base_item"
item_id = 5927
name = "bunch of dates"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x1726_coconut"
base_id = "base_item"
item_id = 5926
name = "coconut"
rarity = "common"
movable = true
weight = 2.0
stackable = true
buy_price = 12
sell_price = 6
hue = 0

[[item]]
id = "0x1725_coconut"
base_id = "base_item"
item_id = 5925
name = "coconut"
rarity = "common"
movable = true
weight = 2.0
stackable = true
buy_price = 12
sell_price = 6
hue = 0

[[item]]
id = "0x1724_coconut"
base_id = "base_item"
item_id = 5924
name = "coconut"
rarity = "common"
movable = true
weight = 2.0
stackable = true
buy_price = 12
sell_price = 6
hue = 0

[[item]]
id = "0x1723_coconut"
base_id = "base_item"
item_id = 5923
name = "coconut"
rarity = "common"
movable = true
weight = 2.0
stackable = true
buy_price = 12
sell_price = 6
hue = 0

[[item]]
id = "0x1722_bananas"
base_id = "base_item"
item_id = 5922
name = "bananas"
rarity = "common"
weight = 3.0
stackable = true
buy_price = 6
sell_price = 3
hue = 0

[[item]]
id = "0x1721_bananas"
base_id = "base_item"
item_id = 5921
name = "bananas"
rarity = "common"
weight = 3.0
stackable = true
buy_price = 6
sell_price = 3
hue = 0

[[item]]
id = "0x1720_banana"
base_id = "base_item"
item_id = 5920
name = "banana"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x171f_banana"
base_id = "base_item"
item_id = 5919
name = "banana"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x171e_banana"
base_id = "base_item"
item_id = 5918
name = "banana"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x171d_banana"
base_id = "base_item"
item_id = 5917
name = "banana"
rarity = "common"
movable = true
weight = 1.0
stackable = true
buy_price = 3
sell_price = 1
hue = 0

[[item]]
id = "0x0c5c_watermelon"
base_id = "base_item"
item_id = 3164
name = "watermelon"
rarity = "common"
movable = true
weight = 5.0
stackable = true
buy_price = 8
sell_price = 4
hue = 0

[[item]]
id = "0x0c5d_watermelon"
base_id = "base_item"
item_id = 3165
name = "watermelon"
rarity = "common"
movable = true
weight = 5.0
stackable = true
buy_price = 8
sell_price = 4
hue = 0

[[item]]
id = "0x0993_fruit_basket"
base_id = "base_item"
item_id = 2451
name = "fruit basket"
rarity = "common"
movable = true
weight = 5.0
buy_price = 100
sell_price = 50
hue = 0

[[item]]
id = "tribalberry"
base_id = "base_item"
item_id = 2512
name = "tribal berry"
rarity = "common"
weight = 1.0
stackable = true
hue = 0
